import { SQL, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { getTableConfig, PgDialect, type PgTable } from "drizzle-orm/pg-core";
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { orders, orderItems, combinedOrderGroups, warehouseSettings } from "@shared/schema";
import { createInventoryCutoverTestDatabase, type InventoryCutoverTestDatabase } from "../../../inventory/__tests__/fixtures/inventory-cutover-database";
import { validatePostgresTestEnvironment } from "../../../../../scripts/ci/postgres-tests";

vi.mock("../../shipment-rollup", () => ({ recomputeOrderStatusFromShipments: vi.fn() }));
import { createOrderCombiningService } from "../../combining.service";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
if (databaseUrl && disposable) validatePostgresTestEnvironment(process.env);
const integration = databaseUrl && disposable ? describe.sequential : describe.skip;
const quote = (name: string) => `"${name.replaceAll('"', '""')}"`;

// Current columns/defaults support actual Drizzle reads and writes. This suite
// proves service transactions and row locking; migration258 has its own suite.
function tableFixture(table: PgTable): string {
  const config = getTableConfig(table);
  const columns = config.columns.map(column => {
    let definition = `${quote(column.name)} ${column.getSQLType()}`;
    if (column.primary) return `${definition} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    if (column.default !== undefined) {
      const literal = column.default instanceof SQL ? new PgDialect().sqlToQuery(column.default).sql
        : typeof column.default === "string" ? `'${column.default.replaceAll("'", "''")}'` : String(column.default);
      definition += ` DEFAULT ${literal}`;
    }
    return definition + (column.notNull ? " NOT NULL" : "");
  });
  return `CREATE TABLE ${quote(config.schema!)}.${quote(config.name)} (${columns.join(",")});`;
}

const fixture = `CREATE SCHEMA wms; CREATE SCHEMA inventory; CREATE SCHEMA oms;
  ${[orders, orderItems, combinedOrderGroups, warehouseSettings].map(tableFixture).join("\n")}
  CREATE TABLE oms.oms_orders(id integer PRIMARY KEY,external_order_number text,cancelled_at timestamp);
  CREATE UNIQUE INDEX combined_group_code_unique ON wms.combined_order_groups(group_code);`;

integration("combining country guards with real PostgreSQL", () => {
  let database: InventoryCutoverTestDatabase;
  let orm: ReturnType<typeof drizzle>;
  let service: ReturnType<typeof createOrderCombiningService>;

  beforeAll(async () => {
    database = await createInventoryCutoverTestDatabase(databaseUrl, disposable, fixture);
    orm = drizzle(database.pool);
    service = createOrderCombiningService(orm);
  });
  beforeEach(async () => {
    await database.pool.query("TRUNCATE wms.order_items,wms.orders,wms.combined_order_groups,inventory.warehouse_settings RESTART IDENTITY");
    await orm.insert(warehouseSettings).values({ warehouseId: 1, enableOrderCombining: 1 });
  });
  afterAll(async () => { await database?.close(); });

  async function seed(country: string | null, number: string) {
    const [order] = await orm.insert(orders).values({
      orderNumber: number, customerName: "Test", customerEmail: "test@example.invalid",
      warehouseId: 1, shippingCountry: country, shippingAddress: "A long fictional destination address ".repeat(4),
      shippingCity: "Test City", shippingState: "Test Region", shippingPostalCode: "10001",
    }).returning();
    return order;
  }

  it("persists canonical country and a bounded hash for a real manual combine", async () => {
    const a = await seed("UK", "ONE");
    const b = await seed("United Kingdom", "TWO");
    const result = await service.combineOrders([a.id, b.id], "test-staff");
    expect(result.group.shippingCountry).toBe("GB");
    expect(result.group.addressHash).toMatch(/^[a-f0-9]{64}$/);
    expect((await orm.select().from(orders)).map(row => row.combinedGroupId)).toEqual([result.group.id, result.group.id]);
  });

  it("runs the outer-join FOR UPDATE auto-combine and keeps different or unknown countries separate", async () => {
    await seed("Canada", "ONE");
    await seed("CA", "TWO");
    await seed("US", "THREE");
    await seed(null, "FOUR");
    await seed("XX", "FIVE");
    expect(await service.combineAll("test-staff")).toEqual({ groupsCreated: 1, totalOrdersCombined: 2 });
    expect((await orm.select().from(combinedOrderGroups)).map(row => row.shippingCountry)).toEqual(["CA"]);
    expect((await orm.select().from(orders).orderBy(orders.id)).map(row => row.combinedGroupId !== null))
      .toEqual([true, true, false, false, false]);
  });

  it("rejects an unselected historical member before any group changes", async () => {
    const a = await seed("US", "ONE");
    const b = await seed("US", "TWO");
    const c = await seed("US", "THREE");
    const original = await service.combineOrders([a.id, b.id], "test-staff");
    await orm.update(orders).set({ shippingCountry: "CA" }).where(eq(orders.id, b.id));
    await expect(service.combineOrders([a.id, c.id], "test-staff")).rejects.toThrow("different destination countries");
    expect((await orm.select().from(orders).orderBy(orders.id)).map(row => row.combinedGroupId))
      .toEqual([original.group.id, original.group.id, null]);
    expect(await orm.select().from(combinedOrderGroups)).toHaveLength(1);
  });

  it("rolls back the new group if a later membership write fails", async () => {
    const a = await seed("US", "ONE");
    const b = await seed("US", "TWO");
    await database.pool.query(`CREATE FUNCTION wms.reject_test_membership() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN IF NEW.id=${b.id} AND NEW.combined_group_id IS NOT NULL THEN RAISE EXCEPTION 'test failure'; END IF; RETURN NEW; END $$;
      CREATE TRIGGER reject_test_membership BEFORE UPDATE ON wms.orders FOR EACH ROW EXECUTE FUNCTION wms.reject_test_membership();`);
    try {
      await expect(service.combineOrders([a.id, b.id], "test-staff")).rejects.toThrow();
      expect(await orm.select().from(combinedOrderGroups)).toEqual([]);
      expect((await orm.select().from(orders)).every(row => row.combinedGroupId === null)).toBe(true);
    } finally {
      await database.pool.query("DROP TRIGGER reject_test_membership ON wms.orders; DROP FUNCTION wms.reject_test_membership()");
    }
  });

  it("holds country rows against concurrent edits while combine waits on another table", async () => {
    const a = await seed("US", "ONE");
    const b = await seed("US", "TWO");
    const blocker = await database.pool.connect();
    let combining: Promise<unknown> | undefined;
    try {
      await blocker.query("BEGIN; LOCK TABLE inventory.warehouse_settings IN ACCESS EXCLUSIVE MODE");
      combining = service.combineOrders([a.id, b.id], "test-staff");
      const deadline = Date.now() + 5_000;
      let observed = false;
      while (Date.now() < deadline) {
        const result = await database.pool.query(`SELECT 1 FROM pg_locks
          WHERE database=(SELECT oid FROM pg_database WHERE datname=current_database())
            AND relation='inventory.warehouse_settings'::regclass AND NOT granted
            AND pid<>pg_backend_pid()`);
        if (result.rowCount) { observed = true; break; }
        await new Promise(resolve => setTimeout(resolve, 10));
      }
      expect(observed).toBe(true);
      const updater = await database.pool.connect();
      try {
        await updater.query("BEGIN; SET LOCAL lock_timeout='100ms'");
        await expect(updater.query("UPDATE wms.orders SET shipping_country='CA' WHERE id=$1", [a.id]))
          .rejects.toMatchObject({ code: "55P03" });
      } finally { await updater.query("ROLLBACK"); updater.release(); }
      await blocker.query("COMMIT");
      await combining;
      expect((await orm.select().from(combinedOrderGroups))[0].shippingCountry).toBe("US");
    } finally {
      await blocker.query("ROLLBACK"); blocker.release();
      if (combining) await Promise.allSettled([combining]);
    }
  });

  it("serializes overlapping combines without member/group lock cycles", async () => {
    const rows = await Promise.all([seed("US", "ONE"), seed("US", "TWO"), seed("US", "THREE"), seed("US", "FOUR")]);
    const original = await service.combineOrders([rows[0].id, rows[1].id], "test-staff");
    await Promise.all([
      service.combineOrders([rows[0].id, rows[2].id], "test-staff"),
      service.combineOrders([rows[1].id, rows[3].id], "test-staff"),
    ]);
    expect((await orm.select().from(orders)).every(row => row.combinedGroupId === original.group.id)).toBe(true);
    expect((await orm.select().from(combinedOrderGroups))[0].orderCount).toBe(4);
  });
});
