import { SQL, eq, getTableColumns } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { getTableConfig, PgDialect, type PgTable } from "drizzle-orm/pg-core";
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import * as schema from "@shared/schema";
import { buildWmsOrderBucketCounts, orderMatchesBucket, WMS_ORDER_BUCKETS } from "@shared/wms-order-listing";
import { createInventoryCutoverTestDatabase, type InventoryCutoverTestDatabase } from "../../../inventory/__tests__/fixtures/inventory-cutover-database";
import { OrderListRepository, ORDER_LIST_STATEMENT_TIMEOUT_MS } from "../../order-list.repository";
import { PickingHistoryRepository } from "../../picking-history.repository";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const describeDatabase = databaseUrl && disposable ? describe.sequential : describe.skip;
const quote = (name: string) => `"${name.replaceAll('"', '""')}"`;

// Current-column read fixture, not a migration/trigger test. No production
// records are used. The shared harness owns and drops a unique test database.
function readFixture(table: PgTable): string {
  const config = getTableConfig(table);
  const columns = Object.values(getTableColumns(table)).map(column => {
    let definition = `${quote(column.name)} ${column.getSQLType()}`;
    if (column.primary) return `${definition} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    if (column.default !== undefined) {
      const literal = column.default instanceof SQL
        ? new PgDialect().sqlToQuery(column.default).sql
        : typeof column.default === "string" ? `'${column.default.replaceAll("'", "''")}'` : String(column.default);
      definition += ` DEFAULT ${literal}`;
    }
    return definition + (column.notNull ? " NOT NULL" : "");
  });
  return `CREATE TABLE ${quote(config.schema!)}.${quote(config.name)} (${columns.join(",")});`;
}
const fixture = `CREATE SCHEMA wms;
  CREATE SCHEMA oms;
  CREATE SCHEMA channels;
  ${readFixture(schema.omsOrders)}
  ${readFixture(schema.omsOrderLines)}
  ${readFixture(schema.channels)}
  ${readFixture(schema.wmsOrders)}
  ${readFixture(schema.wmsOrderItems)}
  ${readFixture(schema.pickingLogs)}
  CREATE INDEX order_items_order_id ON wms.order_items(order_id);
  CREATE INDEX picking_logs_order_id ON wms.picking_logs(order_id);
  CREATE INDEX orders_created_id ON wms.orders(created_at DESC, id DESC);
  CREATE TABLE public.orders (id integer);
  CREATE TABLE public.order_items (id integer);
`;

describeDatabase("bounded order listing PostgreSQL reads", () => {
  let database: InventoryCutoverTestDatabase;
  let orm: ReturnType<typeof drizzle<typeof schema>>;
  let repository: OrderListRepository;
  let history: typeof import("../../order-history.storage").orderHistoryMethods;
  const queries: { query: string; parameters: unknown[] }[] = [];

  beforeAll(async () => {
    database = await createInventoryCutoverTestDatabase(databaseUrl, disposable, fixture);
    orm = drizzle(database.pool, { schema, logger: { logQuery(query, parameters) { queries.push({ query, parameters }); } } });
    repository = new OrderListRepository(orm);
    vi.doMock("../../../../storage/base", async importOriginal => ({
      ...await importOriginal<typeof import("../../../../storage/base")>(), db: orm,
    }));
    history = (await import("../../order-history.storage")).orderHistoryMethods;
  });
  beforeEach(async () => {
    await database.pool.query("TRUNCATE wms.order_items, wms.orders, wms.picking_logs, oms.oms_orders, oms.oms_order_lines, channels.channels RESTART IDENTITY");
    queries.length = 0;
  });
  afterAll(async () => { vi.doUnmock("../../../../storage/base"); await database?.close(); });

  async function seed(status: string, overrides: Partial<typeof schema.wmsOrders.$inferInsert> = {}) {
    const [order] = await orm.insert(schema.wmsOrders).values({
      orderNumber: "ORDER", customerName: "Test customer", warehouseStatus: status,
      channelId: 1, warehouseId: 1, source: "oms", ...overrides,
    }).returning();
    await orm.insert(schema.wmsOrderItems).values({
      orderId: order.id, name: "Sleeves", sku: "SKU-1", quantity: 3, pickedQuantity: 2,
    });
    return order;
  }

  it("matches every operational bucket including held/unknown statuses and scoped counts", async () => {
    const rows = [];
    for (const status of ["ready", "in_progress", "partially_shipped", "completed", "ready_to_ship", "exception", "on_hold", "shipped", "cancelled", "unknown", " READY "]) {
      rows.push(await seed(status));
      rows.push(await seed(status, { onHold: 1 }));
    }
    await seed("ready", { channelId: 2 });
    await seed("ready", { warehouseId: 2 });
    await seed("ready", { source: "other" });
    for (const bucket of WMS_ORDER_BUCKETS) {
      const page = await repository.page({ bucket, channelId: 1, warehouseId: 1, source: "oms", limit: 2 });
      expect(page.buckets).toEqual(buildWmsOrderBucketCounts(rows));
      expect(page.total).toBe(rows.filter(order => orderMatchesBucket(order, bucket)).length);
      expect(page.orders.length).toBeLessThanOrEqual(2);
      for (const order of page.orders) expect(orderMatchesBucket(order, bucket)).toBe(true);
    }
  });

  it("searches all matching orders before pagination, with literal wildcard and injection characters", async () => {
    await seed("ready", { orderNumber: "older-match" });
    const exact = await seed("completed", { orderNumber: "62770", externalOrderId: "external-999", customerEmail: "Search@Example.test" });
    await orm.update(schema.wmsOrderItems).set({ sku: "A%_\\B'", name: "Rare searchable item" }).where(eq(schema.wmsOrderItems.orderId, exact.id));
    await seed("ready", { customerName: "Newest unrelated" });
    for (const search of ["62770", "external-999", "SEARCH@EXAMPLE.TEST", "a%_\\b'", "rare searchable"]) {
      const page = await repository.page({ bucket: "all", search, limit: 1 });
      expect(page.total).toBe(1);
      expect(page.orders[0].id).toBe(exact.id);
      expect(page.orders[0].items[0]).toMatchObject({ orderId: exact.id, pickedQuantity: 2, quantity: 3 });
    }
    expect((await repository.page({ bucket: "all", search: "' OR true --" })).total).toBe(0);
  });

  it("provides deterministic pages, empty-page counts and legacy status filtering", async () => {
    const instant = new Date("2026-01-01T00:00:00Z");
    const first = await seed("ready", { createdAt: instant });
    const second = await seed("ready", { createdAt: instant, onHold: 1 });
    const third = await seed("completed", { createdAt: instant });
    const pages = await Promise.all([0, 1, 2].map(offset => repository.page({ bucket: "all", limit: 1, offset })));
    expect(pages.map(page => page.orders[0].id)).toEqual([third.id, second.id, first.id]);
    expect(await repository.page({ bucket: "all", offset: 99 })).toMatchObject({ orders: [], total: 3, buckets: { all: 3 } });
    const legacy = await repository.page({ statuses: ["ready"] });
    expect(legacy.total).toBe(2); // Legacy status query includes holds, as before.
    expect(legacy.orders.map(order => order.id)).toEqual([second.id, first.id]);
    expect(await repository.page({ search: "absent" })).toMatchObject({ total: 0, orders: [], buckets: { all: 0 } });
  });

  it("rejects oversized or invalid reads before querying", async () => {
    const initial = queries.length;
    for (const input of [{ limit: 0 }, { limit: 251 }, { offset: -1 }, { offset: Infinity }, { search: "x".repeat(201) }, { warehouseId: -1 }]) {
      await expect(repository.page(input)).rejects.toThrow();
    }
    expect(queries).toHaveLength(initial);
  });

  it("keyset scans do not skip orders when statuses change, or chase newly added orders", async () => {
    await database.pool.query(`INSERT INTO wms.orders (order_number, customer_name, warehouse_status)
      SELECT 'batch-' || n, 'Test', 'ready' FROM generate_series(1, 205) n`);
    const visited: number[] = [];
    let batchIndex = 0;
    for await (const batch of repository.scan({ excludedStatuses: ["shipped", "cancelled"] })) {
      expect(batch.length).toBeLessThanOrEqual(100);
      visited.push(...batch.map(order => order.id));
      await database.pool.query("UPDATE wms.orders SET warehouse_status = 'shipped' WHERE id = ANY($1::int[])", [batch.map(order => order.id)]);
      if (batchIndex++ === 0) await seed("ready");
    }
    expect(visited).toEqual(Array.from({ length: 205 }, (_, index) => index + 1));
    expect((await repository.page({ bucket: "needs_pick" })).total).toBe(1);
  });

  it("keeps concurrent reads page-sized with 60,000 orders and 180,000 lines", async () => {
    await database.pool.query(`INSERT INTO wms.orders (order_number, customer_name, warehouse_status, created_at)
      SELECT 'LOAD-' || n, 'Synthetic customer', 'completed', '2026-01-01'::timestamp FROM generate_series(1, 60000) n;
      INSERT INTO wms.order_items (order_id, sku, name, quantity)
      SELECT o.id, 'SLEEVE', 'Synthetic line', 1 FROM wms.orders o CROSS JOIN generate_series(1, 3);
      ANALYZE wms.orders; ANALYZE wms.order_items;`);
    queries.length = 0;
    const pages = await Promise.all(Array.from({ length: 8 }, (_, index) => repository.page({ bucket: "picked", offset: index * 100 })));
    for (const page of pages) {
      expect(page.total).toBe(60000);
      expect(page.orders).toHaveLength(100);
      expect(page.orders.flatMap(order => order.items)).toHaveLength(300);
    }
    const itemReads = queries.filter(entry => entry.query.startsWith("select") && entry.query.includes('from "wms"."order_items"'));
    expect(itemReads).toHaveLength(8);
    for (const entry of itemReads) expect(entry.parameters).toHaveLength(100);
    const headerReads = queries.filter(entry => entry.query.startsWith('select "id"') && entry.query.includes('from "wms"."orders"'));
    expect(headerReads).toHaveLength(8);
    for (const entry of headerReads) expect(entry.query).toContain("limit");
  });

  it("filters order history SKU matches inside PostgreSQL without materializing all matching line IDs", async () => {
    await database.pool.query(`INSERT INTO oms.oms_orders (channel_id, external_order_id, ordered_at)
      SELECT 1, 'history-' || n, '2026-01-01'::timestamp FROM generate_series(1, 300) n;
      INSERT INTO oms.oms_order_lines (order_id, sku, quantity)
      SELECT id, 'COMMON-SKU', 2 FROM oms.oms_orders;`);
    queries.length = 0;
    const page = await history.getOrderHistory({ sku: "common", limit: 2, offset: 2 });
    const count = await history.getOrderHistoryCount({ sku: "common" });
    expect(count).toBe(300);
    expect(page.map(order => order.id)).toEqual([298, 297]);
    expect(page.map(order => order.items.length)).toEqual([1, 1]);
    const matchingIdScans = queries.filter(entry => entry.query.startsWith('select "order_id"'));
    expect(matchingIdScans).toEqual([]);
    expect(queries.filter(entry => entry.query.includes("exists (select 1"))).toHaveLength(2);
  });

  it("finds old picks after shipping, cancellation or release without inventing scan evidence", async () => {
    const historyReader = new PickingHistoryRepository(orm);
    const old = new Date("2020-01-01T12:00:00Z");
    const complete = await seed("completed", { orderNumber: "#62770", completedAt: old, createdAt: old });
    const shipped = await seed("shipped", { createdAt: old });
    const cancelled = await seed("cancelled", { createdAt: old });
    const released = await seed("ready", { createdAt: old });
    const untouched = await seed("ready", { createdAt: old });
    // A released/cancelled order may have no remaining picked quantity, but
    // its earlier audit must remain discoverable. No inference from status.
    await database.pool.query("UPDATE wms.order_items SET picked_quantity = 0 WHERE order_id = ANY($1::int[])", [[cancelled.id, released.id, untouched.id]]);
    await orm.insert(schema.pickingLogs).values([
      { orderId: complete.id, actionType: "item_quantity_adjusted", timestamp: old, pickerName: "First picker" },
      { orderId: complete.id, actionType: "item_picked", timestamp: old, pickerName: "Final picker" },
      { orderId: complete.id, actionType: "inventory_auto_resolved", timestamp: new Date("2020-01-02"), pickerName: "System" },
      { orderId: cancelled.id, actionType: "item_picked", timestamp: old },
      { orderId: released.id, actionType: "item_unpicked", timestamp: old, sku: "REMOVED-LINE" },
    ]);
    queries.length = 0;
    const page = await historyReader.page();
    expect(page.orders.map(order => order.id)).toEqual([released.id, cancelled.id, shipped.id, complete.id]);
    expect(page.orders.find(order => order.id === complete.id)).toMatchObject({
      orderNumber: "#62770", lastPickerName: "Final picker", lastPickAt: old.toISOString(), completedAt: old.toISOString(),
      items: [expect.objectContaining({ pickedQuantity: 2, quantity: 3 })],
    });
    expect(page.orders.find(order => order.id === shipped.id)).toMatchObject({ lastPickAt: null, lastPickerName: null });
    expect((await historyReader.page({ search: "removed-line" })).orders.map(order => order.id)).toEqual([released.id]);
    expect((await historyReader.page({ search: "62770" })).orders.map(order => order.id)).toEqual([complete.id]);
    expect(queries.some(entry => entry.query.includes("read only"))).toBe(true);
    expect(queries.some(entry => /^\s*(insert|update|delete)\b/i.test(entry.query))).toBe(false);
  });

  it("pages historical orders deterministically and keeps same-number orders scoped across stores and warehouses", async () => {
    const historyReader = new PickingHistoryRepository(orm);
    await orm.insert(schema.channels).values([{ name: "Store A", provider: "shopify" }, { name: "Store B", provider: "shopify" }, { name: "Store C", provider: "ebay" }]);
    const old = new Date("2020-01-01T00:00:00Z");
    const a = await seed("completed", { orderNumber: "same-order", createdAt: old });
    const b = await seed("completed", { orderNumber: "same-order", channelId: 2, createdAt: old });
    const c = await seed("completed", { orderNumber: "same-order", channelId: 3, warehouseId: 2, createdAt: old });
    const pages = await Promise.all([0, 1, 2].map(offset => historyReader.page({ limit: 1, offset })));
    expect(pages.map(page => page.orders[0].id)).toEqual([c.id, b.id, a.id]);
    expect(pages.map(page => page.orders[0].items.length)).toEqual([1, 1, 1]);
    expect(await historyReader.page({ offset: 999 })).toMatchObject({ orders: [], total: 3 });
    expect((await historyReader.page({ provider: "shopify", search: "same-order" })).total).toBe(2);
    expect((await historyReader.page({ channelId: 2, warehouseId: 1 })).orders.map(order => order.id)).toEqual([b.id]);
    expect((await historyReader.page({ channelId: 2, warehouseId: 2 })).total).toBe(0);
    await orm.update(schema.wmsOrderItems).set({ sku: "A%_\\B'" }).where(eq(schema.wmsOrderItems.orderId, a.id));
    expect((await historyReader.page({ search: "a%_\\b'" })).orders.map(order => order.id)).toEqual([a.id]);
    expect((await historyReader.page({ search: "' OR true --" })).total).toBe(0);
  });

  it("bounds concurrent picking-history hydration even with 60,000 old orders and 180,000 audit events", async () => {
    await database.pool.query(`INSERT INTO wms.orders (order_number, customer_name, warehouse_status, created_at)
      SELECT 'HISTORY-' || n, 'Synthetic customer', 'shipped', '2020-01-01'::timestamp FROM generate_series(1, 60000) n;
      INSERT INTO wms.order_items (order_id, sku, name, quantity, picked_quantity)
      SELECT o.id, 'SLEEVE', 'Synthetic line', 2, 2 FROM wms.orders o CROSS JOIN generate_series(1, 3);
      INSERT INTO wms.picking_logs (order_id, action_type, timestamp, picker_name)
      SELECT o.id, 'item_picked', '2020-01-01'::timestamp, 'Test picker' FROM wms.orders o CROSS JOIN generate_series(1, 3);
      ANALYZE wms.orders; ANALYZE wms.order_items; ANALYZE wms.picking_logs;`);
    queries.length = 0;
    const historyReader = new PickingHistoryRepository(orm);
    const pages = await Promise.all([0, 50, 100, 150].map(offset => historyReader.page({ offset })));
    for (const page of pages) {
      expect(page.total).toBe(60000);
      expect(page.orders).toHaveLength(50);
      expect(page.orders.flatMap(order => order.items)).toHaveLength(150);
      expect(page.orders.every(order => order.lastPickerName === "Test picker")).toBe(true);
    }
    const auditReads = queries.filter(entry => entry.query.startsWith("select distinct on"));
    expect(auditReads).toHaveLength(4);
    for (const entry of auditReads) expect(entry.parameters).toHaveLength(52); // 50 IDs, 2 action types
    const itemReads = queries.filter(entry => entry.query.startsWith("select") && entry.query.includes('from "wms"."order_items"') && !entry.query.includes("exists"));
    expect(itemReads).toHaveLength(4);
    for (const entry of itemReads) expect(entry.parameters).toHaveLength(50);
  });

  it("times out blocked list SQL, rolls back, and leaves the pooled connection usable", async () => {
    const blocker = await database.pool.connect();
    try {
      await blocker.query("BEGIN");
      await blocker.query("LOCK TABLE wms.orders IN ACCESS EXCLUSIVE MODE");
      const error = await repository.page({ bucket: "all" }).then(() => null, failure => failure);
      expect(error).not.toBeNull();
      const code = error?.cause?.code ?? error?.code;
      expect(code).toBe("57014");
      expect(queries.some(entry => entry.query.includes("set_config('statement_timeout'") &&
        entry.parameters.includes(String(ORDER_LIST_STATEMENT_TIMEOUT_MS)))).toBe(true);
    } finally {
      await blocker.query("ROLLBACK");
      blocker.release();
    }
    expect((await repository.page({ bucket: "all" })).orders).toEqual([]);
    const timeout = await database.pool.query("SHOW statement_timeout");
    expect(timeout.rows[0].statement_timeout).not.toBe(`${ORDER_LIST_STATEMENT_TIMEOUT_MS}ms`);
    expect(timeout.rows[0].statement_timeout).not.toBe("5s");
  }, 15_000);
});
