import { SQL, getTableColumns } from "drizzle-orm";
import type { QueryResult } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { getTableConfig, PgDialect, type PgTable } from "drizzle-orm/pg-core";
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import * as schema from "@shared/schema";
import { createInventoryCutoverTestDatabase, type InventoryCutoverTestDatabase } from "../../../inventory/__tests__/fixtures/inventory-cutover-database";
import { createPickingAssignmentReleaseRepository } from "../../picking-assignment-release.repository";
import { releasePickingAssignment, type PickingAssignmentReleaseRepository } from "../../picking-assignment-release.service";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const describeDatabase = databaseUrl && disposable ? describe.sequential : describe.skip;
const quote = (name: string) => `"${name.replaceAll('"', '""')}"`;

// Current schema columns/defaults for real repository/locking tests. Not a full
// migration fixture. The harness creates and drops its own unique database.
function tableFixture(table: PgTable): string {
  const config = getTableConfig(table);
  const columns = Object.values(getTableColumns(table)).map(column => {
    let definition = `${quote(column.name)} ${column.getSQLType()}`;
    if (column.primary && column.getSQLType() === "integer") return `${definition} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    if (column.default !== undefined) {
      const literal = column.default instanceof SQL ? new PgDialect().sqlToQuery(column.default).sql
        : typeof column.default === "string" ? `'${column.default.replaceAll("'", "''")}'` : String(column.default);
      definition += ` DEFAULT ${literal}`;
    }
    return definition + (column.primary ? " PRIMARY KEY" : column.notNull ? " NOT NULL" : "");
  });
  return `CREATE TABLE ${quote(config.schema!)}.${quote(config.name)} (${columns.join(",")});`;
}
const fixture = `CREATE SCHEMA wms; CREATE SCHEMA identity;
  ${[schema.users, schema.authRoles, schema.authPermissions, schema.authRolePermissions, schema.authUserRoles,
    schema.wmsOrders, schema.wmsOrderItems, schema.pickingLogs].map(tableFixture).join("\n")}
  ALTER TABLE identity.auth_user_roles ADD FOREIGN KEY(user_id) REFERENCES identity.users(id);
  ALTER TABLE identity.auth_user_roles ADD FOREIGN KEY(role_id) REFERENCES identity.auth_roles(id);
  ALTER TABLE identity.auth_role_permissions ADD FOREIGN KEY(role_id) REFERENCES identity.auth_roles(id);
  ALTER TABLE identity.auth_role_permissions ADD FOREIGN KEY(permission_id) REFERENCES identity.auth_permissions(id);
  ALTER TABLE wms.picking_logs ADD FOREIGN KEY(order_id) REFERENCES wms.orders(id);
`;
const expectedAssignment = { assignedPickerId: "picker", startedAt: "2026-10-03T10:00:00.000Z" };
const clock = () => new Date("2026-10-03T12:00:00.000Z");

describeDatabase("picking assignment release PostgreSQL safety", () => {
  let database: InventoryCutoverTestDatabase;
  let repository: PickingAssignmentReleaseRepository;
  let orderId: number;
  const queries: string[] = [];
  beforeAll(async () => {
    // pg's raw timestamp parser otherwise follows the developer machine's TZ.
    vi.stubEnv("TZ", "UTC");
    database = await createInventoryCutoverTestDatabase(databaseUrl, disposable, fixture);
    const orm = drizzle(database.pool, { schema, logger: { logQuery(query) { queries.push(query); } } });
    repository = createPickingAssignmentReleaseRepository(orm);
  });
  beforeEach(async () => {
    await database.pool.query(`TRUNCATE wms.picking_logs, wms.order_items, wms.orders,
      identity.auth_user_roles, identity.auth_role_permissions, identity.auth_roles, identity.auth_permissions, identity.users RESTART IDENTITY;
      INSERT INTO identity.users (id, username, password, role) VALUES
        ('picker', 'picker', 'not-a-login', 'picker'), ('other', 'other', 'not-a-login', 'admin'),
        ('supervisor', 'supervisor', 'not-a-login', 'picker');
      INSERT INTO identity.auth_roles (id, name) VALUES (1, 'Ordinary picking'), (2, 'Release assignment override');
      INSERT INTO identity.auth_permissions (id, resource, action, category) VALUES
        (1, 'picking', 'perform', 'picking'), (2, 'picking', 'release_any', 'picking');
      INSERT INTO identity.auth_role_permissions (role_id, permission_id) VALUES (1, 1), (2, 2);
      INSERT INTO identity.auth_user_roles (user_id, role_id) VALUES ('picker', 1), ('other', 1), ('supervisor', 2);`);
    const order = await database.pool.query(`INSERT INTO wms.orders (order_number, customer_name, warehouse_status,
      assigned_picker_id, started_at, on_hold, held_at, picked_count)
      VALUES ('TEST-RELEASE', 'Test', 'in_progress', 'picker', $1, 1, $1, 2) RETURNING id`, [expectedAssignment.startedAt]);
    orderId = order.rows[0].id;
    await database.pool.query(`INSERT INTO wms.order_items (order_id, sku, name, quantity, picked_quantity, on_hold)
      VALUES ($1, 'PICKED', 'Picked line', 2, 2, false), ($1, 'HELD', 'Held line', 1, 0, true)`, [orderId]);
    queries.length = 0;
  });
  afterAll(async () => { try { await database?.close(); } finally { vi.unstubAllEnvs(); } });
  const command = (userId = "picker") => ({ orderId, userId, expectedAssignment });
  const state = async () => (await database.pool.query("SELECT * FROM wms.orders WHERE id = $1", [orderId])).rows[0];
  const logs = async () => (await database.pool.query("SELECT * FROM wms.picking_logs ORDER BY id")).rows;

  it("preserves the complete order except assignment fields, every line, and records an atomic before/after audit", async () => {
    const before = await state();
    const itemsBefore = (await database.pool.query("SELECT * FROM wms.order_items ORDER BY id")).rows;
    const result = await releasePickingAssignment(repository, command(), clock);
    expect(result).toMatchObject({ warehouseStatus: "ready", assignedPickerId: null, startedAt: null, onHold: 1, pickedCount: 2 });
    expect(await state()).toEqual({ ...before, warehouse_status: "ready", assigned_picker_id: null, started_at: null });
    expect((await database.pool.query("SELECT * FROM wms.order_items ORDER BY id")).rows).toEqual(itemsBefore);
    expect(await logs()).toEqual([expect.objectContaining({ picker_id: "picker", action_type: "order_released", timestamp: clock(),
      metadata: expect.objectContaining({ authority: "own_assignment",
        before: expect.objectContaining({ assignedPickerId: "picker", onHold: 1, pickedCount: 2 }),
        after: expect.objectContaining({ assignedPickerId: null, onHold: 1, pickedCount: 2 }),
      }) })]);
    const writes = queries.filter(query => /^(update|insert|delete)/i.test(query));
    expect(writes).toHaveLength(2);
    expect(writes[0]).toMatch(/^update "wms"\."orders" set "warehouse_status" = \$1, "assigned_picker_id" = \$2, "started_at" = \$3 /);
    expect(writes[1]).toMatch(/^insert into "wms"\."picking_logs"/);
  });
  it("allows a custom supervisor grant, but no override from the legacy admin role alone", async () => {
    await expect(releasePickingAssignment(repository, command("other"), clock)).rejects.toMatchObject({ statusCode: 403 });
    expect((await state()).assigned_picker_id).toBe("picker");
    await releasePickingAssignment(repository, command("supervisor"), clock);
    expect((await logs())[0].metadata.authority).toBe("picking:release_any");
  });
  it.each(["inactive", "revoked", "constrained"])("fails closed for a %s grant/account", async kind => {
    if (kind === "inactive") await database.pool.query("UPDATE identity.users SET active = 0 WHERE id = 'picker'");
    if (kind === "revoked") await database.pool.query("DELETE FROM identity.auth_user_roles WHERE user_id = 'picker'");
    if (kind === "constrained") await database.pool.query(`UPDATE identity.auth_role_permissions SET constraints = '{"warehouseId":2}' WHERE role_id = 1`);
    await expect(releasePickingAssignment(repository, command(), clock)).rejects.toMatchObject({ statusCode: 403 });
    expect((await state()).assigned_picker_id).toBe("picker");
    expect(await logs()).toHaveLength(0);
  });
  it("rolls back the assignment when the audit insert fails", async () => {
    const before = await state();
    await database.pool.query(`ALTER TABLE wms.picking_logs ADD CONSTRAINT reject_release_test CHECK (action_type <> 'order_released')`);
    try {
      await expect(releasePickingAssignment(repository, command(), clock)).rejects.toMatchObject({ code: "23514", constraint: "reject_release_test" });
      expect(await state()).toEqual(before);
      expect(await logs()).toHaveLength(0);
    } finally { await database.pool.query("ALTER TABLE wms.picking_logs DROP CONSTRAINT reject_release_test"); }
  });
  it("serializes simultaneous retries and records one release", async () => {
    const results = await Promise.all([releasePickingAssignment(repository, command(), clock), releasePickingAssignment(repository, command(), clock)]);
    expect(results.every(order => order.warehouseStatus === "ready")).toBe(true);
    expect(await logs()).toHaveLength(1);
  });
  it("does not clear a replacement assignment, including a new claim by the same picker", async () => {
    await releasePickingAssignment(repository, command(), clock);
    await database.pool.query(`UPDATE wms.orders SET warehouse_status = 'in_progress', assigned_picker_id = 'picker',
      started_at = '2026-10-03T13:00:00Z' WHERE id = $1`, [orderId]);
    const replacement = await state();
    await expect(releasePickingAssignment(repository, command(), clock)).rejects.toMatchObject({ statusCode: 409 });
    expect(await state()).toEqual(replacement);
    expect(await logs()).toHaveLength(1);
  });
  it("holds the order lock until the audit commits, then protects the newly claimed assignment", async () => {
    let notifyLocked!: () => void;
    let unlock!: () => void;
    const locked = new Promise<void>(resolve => { notifyLocked = resolve; });
    const proceed = new Promise<void>(resolve => { unlock = resolve; });
    const paused: PickingAssignmentReleaseRepository = { transaction: run => repository.transaction(tx => run({ ...tx,
      lockOrder: async id => { const order = await tx.lockOrder(id); notifyLocked(); await proceed; return order; },
    })) };
    const releasing = releasePickingAssignment(paused, command(), clock);
    await Promise.race([locked, releasing.then(() => { throw new Error("Release completed without reaching the lock barrier"); })]);
    const claimant = await database.pool.connect();
    let claiming: Promise<QueryResult> | undefined;
    try {
      await claimant.query("SET application_name = 'picking-release-contender'");
      claiming = claimant.query(`UPDATE wms.orders SET warehouse_status = 'in_progress', assigned_picker_id = 'other',
        started_at = '2026-10-03T13:00:00Z' WHERE id = $1`, [orderId]);
      await expect.poll(async () => Number((await database.pool.query(`SELECT count(*) AS n FROM pg_stat_activity
        WHERE application_name = 'picking-release-contender' AND wait_event_type = 'Lock'`)).rows[0].n)).toBe(1);
      unlock();
      await releasing;
      await claiming;
      const replacement = await state();
      await expect(releasePickingAssignment(repository, command("supervisor"), clock)).rejects.toMatchObject({ statusCode: 409 });
      expect(await state()).toEqual(replacement);
    } finally { unlock(); await releasing; await claiming; claimant.release(); }
  });
  it.each(["completed", "shipped", "cancelled"])("cannot reopen an order which became %s", async status => {
    await database.pool.query("UPDATE wms.orders SET warehouse_status = $1 WHERE id = $2", [status, orderId]);
    const before = await state();
    await expect(releasePickingAssignment(repository, command("supervisor"), clock)).rejects.toMatchObject({ statusCode: 409 });
    expect(await state()).toEqual(before);
    expect(await logs()).toHaveLength(0);
  });
});
