import { dispatchRuntimeFixtureSql, dispatchRuntimeSeedSql } from "../../../inventory-planning/__tests__/fixtures/inventory-availability-dispatch-runtime-fixture";

// Reduced prerequisites for the actual0662 +183 +234 migrations and real OMS
// materializer. This is deliberately not a full historical-schema replay.
export const shipmentCompatibilityFixtureSql = `${dispatchRuntimeFixtureSql}
ALTER TABLE inventory.inventory_transactions ADD COLUMN voided_at timestamp;
ALTER TABLE warehouse.warehouses ADD COLUMN is_active integer NOT NULL DEFAULT 1,
 ADD COLUMN inventory_source_type text NOT NULL DEFAULT 'internal';
ALTER TABLE warehouse.warehouse_locations ADD COLUMN is_active integer NOT NULL DEFAULT 1,
 ADD COLUMN is_pickable integer NOT NULL DEFAULT 1, ADD COLUMN cycle_count_freeze_id integer,
 ADD COLUMN location_type text NOT NULL DEFAULT 'pick', ADD COLUMN pick_sequence integer;
ALTER TABLE catalog.product_variants ADD COLUMN sku text DEFAULT 'SKU-A';
ALTER TABLE wms.order_items ADD COLUMN sku text DEFAULT 'SKU-A', ADD COLUMN oms_order_line_id bigint,
 ADD COLUMN quantity integer NOT NULL DEFAULT 5, ADD COLUMN picked_quantity integer NOT NULL DEFAULT 5,
 ADD COLUMN picked_at timestamp, ADD COLUMN short_reason text;
ALTER TABLE wms.orders ADD COLUMN oms_fulfillment_order_id text, ADD COLUMN sort_rank integer,
 ADD COLUMN shipping_name text, ADD COLUMN shipping_company text, ADD COLUMN shipping_address text,
 ADD COLUMN shipping_address2 text, ADD COLUMN shipping_city text, ADD COLUMN shipping_state text,
 ADD COLUMN shipping_postal_code text, ADD COLUMN shipping_country text,
 ADD COLUMN picked_count integer DEFAULT 5, ADD COLUMN item_count integer DEFAULT 1,
 ADD COLUMN unit_count integer DEFAULT 5, ADD COLUMN completed_at timestamp, ADD COLUMN exception_at timestamp;
ALTER TABLE wms.outbound_shipments ADD COLUMN shipping_engine text, ADD COLUMN engine_order_ref text,
 ADD COLUMN shipstation_order_id bigint, ADD COLUMN shipstation_order_key text,
 ADD COLUMN external_fulfillment_id text, ADD COLUMN tracking_number text, ADD COLUMN carrier text,
 ADD COLUMN review_reason text;
ALTER TABLE wms.outbound_shipments ADD COLUMN replacement_authorized_at timestamp,
 ADD COLUMN replacement_authorized_by text;
ALTER TABLE wms.physical_shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY,
 ADD COLUMN shipping_engine_order_id bigint, ADD COLUMN shipment_request_id bigint,
 ADD COLUMN provider text, ADD COLUMN provider_physical_shipment_id text, ADD COLUMN tracking_number text,
 ADD COLUMN carrier text, ADD COLUMN service_code text, ADD COLUMN ship_date timestamp,
 ADD COLUMN metadata jsonb, ADD COLUMN created_at timestamp, ADD COLUMN updated_at timestamp;
ALTER TABLE wms.physical_shipment_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY,
 ADD COLUMN shipment_request_item_id bigint, ADD COLUMN fulfillment_plan_line_id bigint,
 ADD COLUMN sku text, ADD COLUMN created_at timestamp;
CREATE SCHEMA channels;
CREATE TABLE channels.channels(id integer PRIMARY KEY, provider text);
CREATE TABLE oms.oms_orders(id bigint PRIMARY KEY, channel_id integer, external_order_id text,
 status text, financial_status text);
CREATE TABLE oms.oms_order_lines(id bigint PRIMARY KEY, order_id bigint, fulfillment_provider text,
 external_line_item_id text, paid_quantity integer, authority_fulfillable_quantity integer);
CREATE TABLE oms.oms_order_line_authority_events(id bigint PRIMARY KEY, order_line_id bigint, paid_quantity integer);
CREATE TABLE wms.shipping_engine_orders(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 shipment_request_id bigint, provider text, command_key text, provider_order_id text, provider_order_key text,
 provider_status text, last_sync_at timestamp, metadata jsonb, created_at timestamp, updated_at timestamp);
CREATE TABLE wms.shipping_engine_order_provider_refs(shipping_engine_order_id bigint,
 provider text, provider_order_id text, source text, first_observed_at timestamp, last_observed_at timestamp,
 metadata jsonb, created_at timestamp, updated_at timestamp, UNIQUE(provider, provider_order_id));
CREATE TABLE wms.shipping_engine_order_requests(shipping_engine_order_id bigint,
 shipment_request_id bigint, relationship_type text, created_at timestamp,
 UNIQUE(shipping_engine_order_id,shipment_request_id));
`;

export const shipmentCompatibilitySeedSql = `
TRUNCATE wms.shipping_engine_order_requests, wms.shipping_engine_order_provider_refs,
 wms.shipping_engine_orders RESTART IDENTITY;
${dispatchRuntimeSeedSql.replace("TRUNCATE inventory.availability_claim_dispatch_movements",
  "TRUNCATE inventory.operational_shipment_dispatch_lots, inventory.operational_shipment_dispatch_receipts, inventory.availability_claim_dispatch_movements").replace(
  "INSERT INTO wms.outbound_shipment_items VALUES(101,90),(102,91);",
  "INSERT INTO wms.outbound_shipment_items(id,shipment_id,order_item_id,product_variant_id,from_location_id) VALUES(101,90,71,105,50),(102,91,71,105,50);",
)}
`;
