import { SQL } from "drizzle-orm";
import { getTableConfig, PgDialect, type PgTable } from "drizzle-orm/pg-core";
import * as schema from "@shared/schema";

const quote = (name: string) => `"${name.replaceAll('"', '""')}"`;
const introducedColumns = new Set(["inventory_tracking_default", "inventory_tracking_override", "inventory_tracking", "catalog_product_id"]);
const tables = [schema.shippingGroups, schema.products, schema.productVariants, schema.channels, schema.channelFeeds,
  schema.channelListings, schema.omsOrders, schema.omsOrderLines, schema.omsOrderEvents,
  schema.omsOrderLineAuthorityEvents, schema.wmsOrders, schema.wmsOrderItems,
  schema.inventoryLevels, schema.inventoryLots, schema.inventoryAvailabilityClaimLines,
  schema.inventoryAvailabilityClaimResources, schema.auditEvents, schema.productLocations, schema.warehouseLocations,
  schema.allocationExceptions, schema.pickingLogs, schema.inventoryAvailabilityRuntimeAuthority, schema.inventoryAvailabilityClaimCommands];

/** Existing table columns are a query fixture. The new policy columns/constraints come only from migration 0694. */
export const inventoryTrackingPolicyBaseFixture = [...new Set(tables.map(t => getTableConfig(t).schema ?? "public"))]
  .map(name => `CREATE SCHEMA IF NOT EXISTS ${quote(name)};`).join("\n") + tables.map((table: PgTable) => {
    const config = getTableConfig(table);
    const columns = config.columns.filter(column => !introducedColumns.has(column.name)).map(column => {
      let definition = `${quote(column.name)} ${column.getSQLType()}`;
      if (column.primary && ["integer", "bigint"].includes(column.getSQLType())) return `${definition} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
      if (column.primary) definition += " PRIMARY KEY";
      if (column.default !== undefined) {
        if (column.default instanceof SQL) {
          const compiled = new PgDialect().sqlToQuery(column.default);
          if (compiled.params.length) throw new Error("Parameterized fixture default");
          definition += ` DEFAULT ${compiled.sql}`;
        } else if (typeof column.default === "string") definition += ` DEFAULT '${column.default.replaceAll("'", "''")}'`;
        else if (["number", "boolean", "bigint"].includes(typeof column.default)) definition += ` DEFAULT ${column.default}`;
        else definition += ` DEFAULT '${JSON.stringify(column.default).replaceAll("'", "''")}'`;
      }
      return definition + (column.notNull ? " NOT NULL" : "");
    });
    return `CREATE TABLE ${quote(config.schema ?? "public")}.${quote(config.name)} (${columns.join(",")});`;
  }).join("\n") + `
    CREATE SCHEMA membership;
    CREATE TABLE membership.shopify_metafield_outbox (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      target_type text, target_id text, namespace text, key text, value jsonb, operation text, dedupe_key text,
      status text NOT NULL DEFAULT 'pending', scheduled_for timestamp, attempts integer DEFAULT 0, last_error text);
    CREATE UNIQUE INDEX policy_test_metafield_uq ON membership.shopify_metafield_outbox(dedupe_key) WHERE status = 'pending';
    CREATE TABLE inventory.replen_tasks (id integer, order_id integer, pick_product_variant_id integer, status text, exception_reason text, notes text, blocks_shipment boolean, created_at timestamp);
    CREATE TABLE inventory.inventory_publication_outbox (id integer, product_variant_id integer, state text);
    CREATE UNIQUE INDEX policy_test_order_uq ON oms.oms_orders(channel_id, external_order_id);
    CREATE UNIQUE INDEX policy_test_authority_event_uq ON oms.oms_order_line_authority_events(event_key);
    CREATE UNIQUE INDEX availability_claim_commands_idempotency_uq ON inventory.availability_claim_commands(idempotency_key);
  `;
