import { readFileSync } from "node:fs";
import { PRODUCT_102_COUNT_IDS } from "../../domain/product-102-cleanup";
import { buildPurchasingForecastPolicyCohort } from "../../../procurement/purchasing-forecast-policy";

export const cleanupMigrationFile =
  "0695_catalog_forecast_identity_history.sql";
export const readCleanupMigration = (name: string): string =>
  readFileSync(
    new URL(`../../../../../migrations/${name}`, import.meta.url),
    "utf8",
  );
const rfqMigration = readCleanupMigration("148_purchase_rfq_requests.sql");
const guardStart = rfqMigration.indexOf(
  "CREATE OR REPLACE FUNCTION procurement.guard_purchasing_evidence_delete()",
);
const guardEnd = rfqMigration.indexOf(
  "CREATE TRIGGER purchase_recommendation_runs_update_guard_trg",
  guardStart,
);
if (guardStart < 0 || guardEnd <= guardStart)
  throw new Error("Real purchasing evidence guards could not be loaded.");

export const cleanupTestPolicy = buildPurchasingForecastPolicyCohort({
  method: "recent_order_velocity_v1",
});
export const cleanupTestTime = new Date("2026-09-21T23:00:00.000Z");

// Reduced supporting tables, real supplier/forecast/overlay/policy migrations.
// This is not a claim of a full production-schema replay. No default app DB.
export const product102CleanupFixture =
  `
  CREATE SCHEMA catalog; CREATE SCHEMA procurement; CREATE SCHEMA inventory; CREATE SCHEMA wms; CREATE SCHEMA identity;
  CREATE TABLE _migrations(filename text PRIMARY KEY,content_hash text);
  CREATE TABLE identity.users(id varchar PRIMARY KEY,active int NOT NULL,role text);
  CREATE TABLE identity.auth_roles(id int PRIMARY KEY,name text);
  CREATE TABLE identity.auth_permissions(id int PRIMARY KEY,resource text,action text);
  CREATE TABLE identity.auth_user_roles(id int PRIMARY KEY,user_id varchar REFERENCES identity.users(id),role_id int REFERENCES identity.auth_roles(id));
  CREATE TABLE identity.auth_role_permissions(id int PRIMARY KEY,role_id int REFERENCES identity.auth_roles(id),permission_id int REFERENCES identity.auth_permissions(id),constraints jsonb);
  INSERT INTO identity.users VALUES('owner-test',1,'admin'),('no-grant',1,'admin'),('inactive',0,'admin');
  INSERT INTO identity.auth_roles VALUES(1,'Administrator');
  INSERT INTO identity.auth_permissions VALUES(1,'inventory','delete');
  INSERT INTO identity.auth_role_permissions VALUES(1,1,1,null);
  INSERT INTO identity.auth_user_roles VALUES(1,'owner-test',1),(2,'inactive',1);
  CREATE TABLE public.audit_events(id bigserial PRIMARY KEY,timestamp timestamptz NOT NULL,level text,actor text,
    action text,target text,changes jsonb,context jsonb);
  ALTER SEQUENCE public.audit_events_id_seq RESTART WITH 9007199254740993;
  CREATE TABLE catalog.products(id int PRIMARY KEY,sku text NOT NULL,is_active boolean NOT NULL,status text NOT NULL);
  CREATE TABLE catalog.product_variants(id int PRIMARY KEY,product_id int REFERENCES catalog.products(id),sku text NOT NULL UNIQUE,
    units_per_variant int NOT NULL,is_active boolean NOT NULL DEFAULT true,UNIQUE(id,product_id));
  CREATE TABLE procurement.vendor_products(id int PRIMARY KEY,vendor_id int,product_id int REFERENCES catalog.products(id),
    product_variant_id int REFERENCES catalog.product_variants(id),is_active int,pack_size int,unit_cost_cents bigint,unit_cost_mills bigint,
    UNIQUE(vendor_id,product_id,product_variant_id));
  CREATE TABLE procurement.purchase_orders(id int PRIMARY KEY,vendor_id int);
  CREATE TABLE procurement.purchase_order_lines(id int PRIMARY KEY,purchase_order_id int REFERENCES procurement.purchase_orders(id),
    product_id int REFERENCES catalog.products(id),vendor_product_id int REFERENCES procurement.vendor_products(id),
    product_variant_id int REFERENCES catalog.product_variants(id),expected_receive_variant_id int,
    expected_receive_units_per_variant int,line_type text,status text,order_qty int,received_qty int,cancelled_qty int,line_total_cents bigint,
    damaged_qty int NOT NULL DEFAULT 0,returned_qty int NOT NULL DEFAULT 0);
  CREATE TABLE procurement.receiving_lines(id int PRIMARY KEY,purchase_order_line_id int REFERENCES procurement.purchase_order_lines(id));
  CREATE TABLE procurement.vendor_invoices(id int PRIMARY KEY,vendor_id int,status text,invoiced_amount_cents bigint,paid_amount_cents bigint,balance_cents bigint);
  CREATE TABLE procurement.vendor_invoice_lines(id int PRIMARY KEY,vendor_invoice_id int REFERENCES procurement.vendor_invoices(id),
    purchase_order_line_id int REFERENCES procurement.purchase_order_lines(id),product_variant_id int REFERENCES catalog.product_variants(id),
    sku text,qty_invoiced int,unit_cost_cents bigint,unit_cost_mills bigint,line_total_cents bigint,match_status text);
  CREATE TABLE procurement.po_events(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,po_id int REFERENCES procurement.purchase_orders(id),
    event_type varchar(40),actor_type varchar(20),actor_id varchar(100),payload_json jsonb,created_at timestamp NOT NULL);
  ALTER TABLE procurement.po_events ALTER COLUMN id RESTART WITH 9007199254740993;
  CREATE TABLE inventory.cycle_count_items(id int PRIMARY KEY,product_id int REFERENCES catalog.products(id),
    product_variant_id int REFERENCES catalog.product_variants(id),expected_qty int,counted_qty int,variance_qty int,status text,
    expected_sku text,counted_sku text,adjustment_transaction_id int,related_item_id int);
  CREATE TABLE inventory.inventory_levels(id int PRIMARY KEY,product_variant_id int REFERENCES catalog.product_variants(id),variant_qty int);
  CREATE TABLE inventory.inventory_lots(id int PRIMARY KEY,product_variant_id int REFERENCES catalog.product_variants(id),qty_on_hand int,unit_cost_cents bigint);
  CREATE TABLE inventory.inventory_transactions(id int PRIMARY KEY,product_variant_id int REFERENCES catalog.product_variants(id),quantity int);
  CREATE TABLE inventory.availability_runtime_authority(singleton_key boolean PRIMARY KEY,authority text,activation_run_id bigint);
  CREATE TABLE inventory.cutover_admission_fence(singleton_key boolean PRIMARY KEY,epoch bigint);
  CREATE TABLE inventory.availability_activation_freezes(activation_run_id bigint PRIMARY KEY,released_at timestamptz);
  CREATE TABLE inventory.quantity_ledger_opening(id int PRIMARY KEY);
  INSERT INTO inventory.availability_runtime_authority VALUES(true,'legacy',null);
  INSERT INTO inventory.cutover_admission_fence VALUES(true,1);
  CREATE TABLE wms.orders(id int PRIMARY KEY,order_placed_at timestamp,cancelled_at timestamp,warehouse_status text);
  CREATE TABLE wms.order_items(id int PRIMARY KEY,product_id int,sku text,quantity int,status text,order_id int,requires_shipping int DEFAULT 1);
  CREATE TABLE catalog.product_line_products(id int PRIMARY KEY,product_line_id int,product_id int REFERENCES catalog.products(id) ON DELETE CASCADE,
    UNIQUE(product_line_id,product_id));
  CREATE TABLE procurement.purchase_recommendation_runs(id int PRIMARY KEY,as_of timestamptz,status text);
  INSERT INTO catalog.products VALUES(5,'SHLZ-TOP-35PT-BLU',true,'active'),(50,'GLV-GRD-SGC-VNT',true,'active'),
    (102,'ZZ-DUPE-SHLZ-TOP-35PT-BLU',false,'archived');
  INSERT INTO catalog.product_variants VALUES(206,5,'SHLZ-TOP-35PT-BLU-C1000',1000,true),(102,50,'GLV-GRD-SGC-VNT-C10000',10000,true);
  INSERT INTO procurement.vendor_products VALUES(25,2,102,206,1,1000,7,null),(125,2,5,206,1,1,6,580);
  INSERT INTO procurement.purchase_orders VALUES(7,2),(113,2),(134,2);
  INSERT INTO procurement.purchase_order_lines VALUES
    (39,7,102,null,206,206,1,'product','cancelled',400000,0,400000,9007199254740993,0,0),
    (153,113,5,125,206,206,1,'product','received',200000,200000,0,1160000,0,0),
    (221,134,102,25,206,206,1,'product','open',352000,0,0,2293100,0,0);
  INSERT INTO procurement.receiving_lines VALUES(1,153);
  INSERT INTO procurement.vendor_invoices VALUES(9,2,'paid',7164050,7164050,0);
  INSERT INTO procurement.vendor_invoice_lines VALUES(43,9,39,206,'SHLZ-TOP-35PT-BLU-C1000',400000,7,null,2603167,'pending');
  INSERT INTO inventory.cycle_count_items SELECT n,102,206,80,80,0,'counted','SHLZ-TOP-35PT-BLU-C1000','SHLZ-TOP-35PT-BLU-C1000',null,null
    FROM unnest(ARRAY[${PRODUCT_102_COUNT_IDS.join(",")}]) n;
  INSERT INTO inventory.inventory_levels VALUES(1,206,80),(2,102,4);
  INSERT INTO inventory.inventory_lots VALUES(1,206,80,9007199254740993),(2,102,4,100);
  INSERT INTO inventory.inventory_transactions VALUES(1,206,80),(2,102,4);
  INSERT INTO wms.orders VALUES(1,'2026-08-01',null,'shipped');
  INSERT INTO wms.order_items VALUES(302040,102,'GLV-GRD-SGC-VNT-C10000',1,'completed',1,1),
    (302869,102,'GLV-GRD-SGC-VNT-C10000',2,'completed',1,1),(310633,102,'GLV-GRD-SGC-VNT-C10000',1,'completed',1,1),
    (320232,102,'GLV-GRD-SGC-VNT-C10000',1,'completed',1,1),(99999,206,'SHLZ-TOP-35PT-BLU-C1000',3,'completed',1,1);
  INSERT INTO catalog.product_line_products VALUES(71,1,102),(105,1,5);
  INSERT INTO procurement.purchase_recommendation_runs SELECT n,'2026-07-25'::timestamptz + n * interval '1 day','completed'
    FROM generate_series(1,39) n;
` +
  readCleanupMigration("146_po_vendor_product_identity_guard.sql") +
  rfqMigration.slice(guardStart, guardEnd) +
  [
    "162_purchase_forecast_observations.sql",
    "163_purchase_forecast_evaluations.sql",
    "168_purchase_forecast_overlay_contributions.sql",
    "169_purchase_forecast_overlay_capture_coverage.sql",
    "170_purchase_forecast_overlay_scoring.sql",
    "172_purchase_forecast_policy_cohorts.sql",
  ]
    .map(readCleanupMigration)
    .join("\n") +
  `
  INSERT INTO procurement.purchase_forecast_observations(run_id,observation_key,product_id,selected_receive_variant_id,
    product_sku,product_name,forecast_method,forecast_version,forecast_daily_pieces_micros,baseline_daily_pieces_micros,evidence_snapshot,created_at,
    forecast_policy_capture_version,forecast_policy_fingerprint,forecast_policy_snapshot)
    SELECT n,'source-'||n,102,null,'ZZ-DUPE-SHLZ-TOP-35PT-BLU','Original snapshot','recent_order_velocity_v1',1,0,0,'{}','2026-09-01',
      1,'${cleanupTestPolicy.fingerprint}','${JSON.stringify(cleanupTestPolicy.snapshot)}' FROM generate_series(1,38) n;
  INSERT INTO procurement.purchase_forecast_observations(run_id,observation_key,product_id,selected_receive_variant_id,
    product_sku,product_name,forecast_method,forecast_version,forecast_daily_pieces_micros,baseline_daily_pieces_micros,evidence_snapshot,created_at)
    SELECT n,'target-'||n,5,206,'SHLZ-TOP-35PT-BLU','Target snapshot','recent_order_velocity_v1',1,5000000,4000000,'{}','2026-09-01'
    FROM generate_series(1,38) n;
  INSERT INTO procurement.purchase_forecast_evaluations(observation_id,horizon_days,evaluation_version,demand_query_version,observed_from,observed_through_exclusive,
    actual_demand_pieces,actual_order_count,actual_active_days,forecast_demand_micros,baseline_demand_micros,
    forecast_absolute_error_micros,baseline_absolute_error_micros,forecast_bias_micros,baseline_bias_micros,evidence_snapshot,evaluated_at)
    SELECT o.id,h,1,'test-source-v1','2026-07-25','2026-07-25'::timestamptz+h*interval '1 day',0,0,0,0,0,0,0,0,0,'{}','2026-09-21'
    FROM procurement.purchase_forecast_observations o CROSS JOIN unnest(ARRAY[7,30]) h
    WHERE o.product_id=102 AND (h=7 OR o.run_id<=28);
`;

export const insertCleanupTestForecast = `INSERT INTO procurement.purchase_forecast_observations(run_id,observation_key,product_id,product_sku,
  product_name,forecast_method,forecast_version,forecast_daily_pieces_micros,baseline_daily_pieces_micros,evidence_snapshot)
  VALUES(39,'new',$1,'test','test','recent_order_velocity_v1',1,0,0,'{}')`;
