import { readFile } from "node:fs/promises";
import { createServer, type Server } from "node:http";
import type { AddressInfo } from "node:net";
import { resolve } from "node:path";
import { config } from "dotenv";
import { eq, getTableColumns, type Table } from "drizzle-orm";
import { getTableConfig } from "drizzle-orm/pg-core";
import { drizzle } from "drizzle-orm/node-postgres";
import express from "express";
import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import * as schema from "@shared/schema";

// Redirect only the connection boundary. HTTP permission middleware, identity
// queries, purchase application service, policy and audit writes remain real.
const connection = vi.hoisted(() => ({ database: null as any }));
vi.mock("../../../../db", () => ({ db: new Proxy({}, {
  get(_target, property) {
    if (!connection.database) throw new Error("Approval test database not initialized");
    const value = connection.database[property];
    return typeof value === "function" ? value.bind(connection.database) : value;
  },
}) }));
import { procurementMethods } from "../../procurement.storage";
import { isPurchaseOrderHistoryConstraintViolation } from "../../purchase-order-history.repository";
import { createPurchasingService } from "../../purchasing.service";
import { registerPurchaseOrderRoutes } from "../../purchase-order.routes";
import { readPurchaseApprovalActor } from "../../../identity/infrastructure/purchase-approval-access.repository";

config({ path: resolve(process.cwd(), ".env.test") });
const testUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const databaseTests = testUrl && disposable ? describe : describe.skip;

// Fixture column names/types come from production Drizzle definitions. These
// tables isolate the actual owner path, not the full migration/constraint suite.
function fixtureTable(table: Parameters<typeof getTableConfig>[0]): string {
  const definition = getTableConfig(table);
  const columns = Object.values(getTableColumns(table as Table)).map((column) => {
    const identity = column.primary && ["integer", "bigint"].includes(column.getSQLType()) ? " GENERATED BY DEFAULT AS IDENTITY" : "";
    const defaultNow = ["created_at", "changed_at"].includes(column.name) ? " DEFAULT now()" : "";
    return `"${column.name}" ${column.getSQLType()}${identity}${defaultNow}${column.primary ? " PRIMARY KEY" : ""}`;
  });
  return `CREATE TABLE "${definition.schema}"."${definition.name}" (${columns.join(", ")})`;
}

function deferred() {
  let resolvePromise!: () => void;
  return { promise: new Promise<void>((resolveValue) => { resolvePromise = resolveValue; }), resolve: () => resolvePromise() };
}

databaseTests.sequential("purchase approval authority PostgreSQL owner and HTTP guarantees", () => {
  let pool: pg.Pool;
  const ownedSchemas: string[] = [];
  let database: ReturnType<typeof drizzle<typeof schema>>;
  let service: ReturnType<typeof createPurchasingService>;
  let server: Server;
  let url: string;
  let requestActor: string | null = "admin-user";
  let retentionMigration: string;

  const storage = { ...procurementMethods, getPurchaseOrderById: async (id: number) => (await database.select().from(schema.purchaseOrders).where(eq(schema.purchaseOrders.id, id)))[0] };
  const makeService = (options: Parameters<typeof createPurchasingService>[2] = {}) => createPurchasingService(database, storage as any, {
    now: () => new Date("2026-09-07T12:00:00Z"), ...options,
  });
  const postApproval = async (body: unknown = {}) => {
    const response = await fetch(`${url}/api/purchase-orders/1/approve`, {
      method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body),
    });
    return { status: response.status, body: await response.json() as any };
  };
  const evidence = async () => {
    const header = (await pool.query("SELECT * FROM procurement.purchase_orders WHERE id=1")).rows;
    const lines = (await pool.query("SELECT * FROM procurement.purchase_order_lines ORDER BY id")).rows;
    const events = (await pool.query("SELECT * FROM procurement.po_events ORDER BY id")).rows;
    const history = (await pool.query("SELECT * FROM procurement.po_status_history ORDER BY id")).rows;
    const revisions = (await pool.query("SELECT * FROM procurement.po_revisions ORDER BY id")).rows;
    return { header, lines, events, history, revisions };
  };

  beforeAll(async () => {
    if ([process.env.DATABASE_URL, process.env.EXTERNAL_DATABASE_URL].filter(Boolean).includes(testUrl!)) {
      throw new Error("Approval tests require a separate explicitly disposable database");
    }
    pool = new pg.Pool({ connectionString: testUrl, ssl: /localhost|127\.0\.0\.1/.test(testUrl!) ? false : { rejectUnauthorized: false } });
    for (const name of ["identity", "procurement", "inventory"]) {
      await pool.query(`CREATE SCHEMA ${name}`);
      ownedSchemas.push(name);
    }
    for (const table of [schema.users, schema.authRoles, schema.authPermissions, schema.authUserRoles, schema.authRolePermissions,
      schema.purchaseOrders, schema.purchaseOrderLines, schema.poApprovalTiers, schema.poStatusHistory, schema.poEvents, schema.poRevisions, schema.purchasingRecommendationPoHandoffs, schema.warehouseSettings]) {
      await pool.query(fixtureTable(table));
    }
    await pool.query(`
      ALTER TABLE identity.auth_user_roles ADD FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE;
      ALTER TABLE identity.auth_user_roles ADD FOREIGN KEY (role_id) REFERENCES identity.auth_roles(id) ON DELETE CASCADE;
      ALTER TABLE identity.auth_role_permissions ADD FOREIGN KEY (role_id) REFERENCES identity.auth_roles(id) ON DELETE CASCADE;
      ALTER TABLE identity.auth_role_permissions ADD FOREIGN KEY (permission_id) REFERENCES identity.auth_permissions(id) ON DELETE CASCADE;
      CREATE UNIQUE INDEX role_assignment ON identity.auth_user_roles(user_id,role_id);
      CREATE UNIQUE INDEX role_permission ON identity.auth_role_permissions(role_id,permission_id);
      CREATE UNIQUE INDEX permission_key ON identity.auth_permissions(resource,action);
    `);
    await pool.query(`
      ALTER TABLE procurement.po_events ADD FOREIGN KEY(po_id) REFERENCES procurement.purchase_orders(id) ON DELETE CASCADE;
      ALTER TABLE procurement.po_status_history ADD FOREIGN KEY(purchase_order_id) REFERENCES procurement.purchase_orders(id) ON DELETE CASCADE;
      ALTER TABLE procurement.po_revisions ADD FOREIGN KEY(purchase_order_id) REFERENCES procurement.purchase_orders(id) ON DELETE CASCADE;
      ALTER TABLE procurement.purchase_order_lines ADD FOREIGN KEY(purchase_order_id) REFERENCES procurement.purchase_orders(id) ON DELETE CASCADE;
    `);
    retentionMigration = await readFile(resolve(process.cwd(), "migrations/227_purchase_order_history_retention.sql"), "utf8");
    database = drizzle(pool, { schema });
    connection.database = database;
    service = makeService();
    const app = express();
    app.use(express.json());
    app.use((req, _res, next) => {
      // Session establishment is the only authentication test double. The
      // intentionally false role string must not override database membership.
      (req as any).session = { user: requestActor ? { id: requestActor, role: "admin" } : undefined };
      next();
    });
    app.locals.services = { purchasing: service, shipmentTracking: {} };
    registerPurchaseOrderRoutes(app);
    server = createServer(app);
    await new Promise<void>((resolveValue) => server.listen(0, "127.0.0.1", resolveValue));
    url = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  });

  beforeEach(async () => {
    requestActor = "admin-user";
    // Reset only this suite's explicitly disposable schemas between cases.
    // Every owner action below runs with migration227 reinstalled after seed.
    await pool.query(`
      DROP TRIGGER IF EXISTS po_event_history_immutable_rows ON procurement.po_events;
      DROP TRIGGER IF EXISTS po_event_history_immutable_truncate ON procurement.po_events;
      DROP TRIGGER IF EXISTS purchase_order_history_retention_rows ON procurement.purchase_orders;
      DROP TRIGGER IF EXISTS purchase_order_history_retention_truncate ON procurement.purchase_orders;
      TRUNCATE identity.auth_user_roles, identity.auth_role_permissions, identity.auth_permissions, identity.auth_roles, identity.users RESTART IDENTITY CASCADE;
      TRUNCATE procurement.purchase_orders, procurement.purchase_order_lines, procurement.po_approval_tiers,
        procurement.po_events, procurement.po_status_history, procurement.po_revisions, procurement.purchasing_recommendation_po_handoffs, inventory.warehouse_settings RESTART IDENTITY CASCADE;
      INSERT INTO identity.users(id,username,password,role,active) VALUES
        ('admin-user','admin','unused','admin',1), ('lead-user','lead','unused','picker',1),
        ('wrong-user','wrong','unused','admin',1), ('inactive-user','inactive','unused','admin',0),
        ('scoped-user','scoped','unused','admin',1), ('no-grant-user','no-grant','unused','admin',1);
      INSERT INTO identity.auth_roles(id,name,is_system) VALUES
        (1,'Administrator',1),(2,'Team Lead',1),(3,'Other Buyer',0),(4,'Scoped Approver',0),(5,'No Grant',0);
      INSERT INTO identity.auth_permissions(id,resource,action,category) VALUES (1,'purchasing','approve','purchasing'),(2,'purchasing','edit','purchasing');
      INSERT INTO identity.auth_role_permissions(id,role_id,permission_id,constraints) VALUES
        (1,1,1,NULL),(2,2,1,NULL),(3,3,1,NULL),(4,4,1,'{"warehouseId":1}'),(5,1,2,NULL);
      INSERT INTO identity.auth_user_roles(id,user_id,role_id) VALUES
        (1,'admin-user',1),(2,'lead-user',2),(3,'wrong-user',3),(4,'inactive-user',1),(5,'scoped-user',4),(6,'no-grant-user',5);
      INSERT INTO procurement.purchase_orders(id,po_number,vendor_id,status,physical_status,financial_status,currency,
        approval_tier_id,subtotal_cents,total_cents,discount_cents,tax_cents,shipping_cost_cents,updated_at)
      VALUES (1,'APPROVAL-001',1,'pending_approval','draft','unbilled','USD',1,10000,10000,0,0,0,'2026-09-01T12:00:00');
      INSERT INTO procurement.purchase_order_lines(id,purchase_order_id,line_number,line_type,product_id,sku,product_name,status,
        order_qty,unit_cost_cents,unit_cost_mills,quoted_unit_cost_mills,total_product_cost_cents,packaging_cost_cents,
        discount_cents,tax_cents,line_total_cents,pricing_basis,pricing_source,pricing_remainder_mills,updated_at)
      VALUES (11,1,1,'product',1,'A','Product A','open',1,10000,1000000,1000000,10000,0,0,0,10000,'per_piece','manual',0,'2026-09-01T12:00:00');
      INSERT INTO procurement.po_approval_tiers(id,tier_name,threshold_cents,approver_role,active) VALUES (1,'Admin approval',1000,'admin',1);
      INSERT INTO inventory.warehouse_settings(id,warehouse_code,require_approval,auto_send_on_approve,require_acknowledge_before_receive,
        hide_incoterms_domestic,enable_shipment_tracking,auto_putaway_location,auto_close_on_reconcile,one_click_receive_start,use_new_po_editor,use_new_reorder_cockpit)
      VALUES (1,'DEFAULT',true,false,false,false,false,false,false,false,false,false);
    `);
    await pool.query(retentionMigration);
  });

  afterAll(async () => {
    if (server) await new Promise<void>((resolveValue, reject) => server.close((error) => error ? reject(error) : resolveValue()));
    if (pool) {
      for (const name of [...ownedSchemas].reverse()) await pool.query(`DROP SCHEMA ${name} CASCADE`);
      await pool.end();
    }
  });

  it("rejects a forged HTTP/session role and preserves every purchase, line, history and audit field", async () => {
    requestActor = "wrong-user";
    const before = await evidence();
    const response = await postApproval({ userId: "admin-user", role: "admin", approverRole: "admin", notes: "forged role" });
    expect(response).toMatchObject({ status: 403, body: { details: { code: "PO_APPROVAL_ROLE_REQUIRED", requiredRole: "admin", actorId: "wrong-user", assignedRoles: [{ id: 3, name: "Other Buyer" }] } } });
    expect(await evidence()).toEqual(before);
  });

  it.each([
    ["inactive-user", "PO_APPROVAL_ACTOR_INACTIVE"], ["scoped-user", "PO_APPROVAL_SCOPE_UNSUPPORTED"],
  ])("rejects %s in the real HTTP owner even when generic permission middleware passes", async (userId, code) => {
    requestActor = userId;
    const before = await evidence();
    expect(await postApproval()).toMatchObject({ status: 403, body: { details: { code } } });
    expect(await evidence()).toEqual(before);
  });

  it("requires authentication and actual permission at HTTP and direct service boundaries", async () => {
    const before = await evidence();
    requestActor = null;
    expect((await postApproval()).status).toBe(401);
    requestActor = "no-grant-user";
    expect((await postApproval()).status).toBe(403);
    await expect(service.approve(1, "no-grant-user")).rejects.toMatchObject({ statusCode: 403, details: { code: "PO_APPROVAL_PERMISSION_REQUIRED" } });
    await expect(service.approve(1)).rejects.toMatchObject({ statusCode: 403, details: { code: "PO_APPROVAL_ACTOR_REQUIRED" } });
    await expect(service.approve(1, "missing-user")).rejects.toMatchObject({ statusCode: 403, details: { code: "PO_APPROVAL_ACTOR_INACTIVE" } });
    expect(await evidence()).toEqual(before);
  });

  it("approves the configured current actor and freezes authority in the existing transactional audit", async () => {
    const response = await postApproval({ notes: "Reviewed total and vendor quote" });
    expect(response.status).toBe(200);
    const result = await evidence();
    expect(result.header[0]).toMatchObject({ status: "approved", approved_by: "admin-user", total_cents: "10000" });
    expect(result.events).toHaveLength(1);
    expect(result.events[0]).toMatchObject({ actor_id: "admin-user", event_type: "approved", payload_json: {
      approval_authority: { contractVersion: 1, requireApproval: true, tier: { id: 1, thresholdCents: 1000, approverRole: "admin" }, totalCents: 10000,
        actor: { userId: "admin-user", active: true, roles: [{ id: 1, name: "Administrator", isSystem: true }], approvalGrantIds: [1] }, matchedRoleId: 1 },
    } });
    expect(result.history).toHaveLength(1);
    expect(result.events[0].created_at).toBeInstanceOf(Date);
    await expect(service.approve(1, "admin-user")).rejects.toMatchObject({ statusCode: 400 });
    expect((await evidence()).events).toEqual(result.events);
    expect((await service.send(1, "admin-user")).status).toBe("sent");
  });

  it("requires Team Lead membership exactly and accepts its explicit grant despite a stale legacy picker role", async () => {
    await pool.query("UPDATE procurement.po_approval_tiers SET approver_role='lead' WHERE id=1");
    await expect(service.approve(1, "admin-user")).rejects.toMatchObject({ details: { code: "PO_APPROVAL_ROLE_REQUIRED" } });
    expect((await service.approve(1, "lead-user")).status).toBe("approved");
  });

  it.each(["role", "threshold", "total", "missing history"])("requires reapproval when %s changes before sending", async (change) => {
    if (change === "missing history") {
      await pool.query(`UPDATE procurement.purchase_orders SET status='approved',approved_by='admin-user',approved_at=now();
        INSERT INTO procurement.po_events(po_id,event_type,actor_type,actor_id,payload_json) VALUES (1,'approved','user','admin-user','{}')`);
    } else {
      await service.approve(1, "admin-user");
    }
    const approvedEvents = (await evidence()).events;
    if (change === "role") await pool.query("UPDATE procurement.po_approval_tiers SET approver_role='lead' WHERE id=1");
    if (change === "threshold") await pool.query("UPDATE procurement.po_approval_tiers SET threshold_cents=999 WHERE id=1");
    if (change === "total") await pool.query("UPDATE procurement.purchase_orders SET shipping_cost_cents=1 WHERE id=1");
    const beforeSend = await evidence();
    expect((await service.send(1, "admin-user")).status).toBe("pending_approval");
    const after = await evidence();
    expect(after.events.filter((row) => row.event_type === "sent_to_vendor")).toHaveLength(0);
    expect(after.events.filter((row) => row.event_type === "approved")).toEqual(beforeSend.events);
    if (change !== "missing history") expect(after.events.filter((row) => row.event_type === "approved")).toEqual(approvedEvents);
    expect(after.header[0].physical_status).toBe("draft");
  });

  it.each(["admin", "lead"])("rejects a duplicate highest active threshold requiring %s without committing anything", async (role) => {
    await pool.query("INSERT INTO procurement.po_approval_tiers(id,tier_name,threshold_cents,approver_role,active) VALUES (2,'Duplicate',1000,$1,1)", [role]);
    const before = await evidence();
    expect(await postApproval()).toMatchObject({ status: 409, body: { details: { code: "PO_APPROVAL_TIER_AMBIGUOUS", tierIds: [1, 2], thresholdCents: 1000 } } });
    expect(await evidence()).toEqual(before);
  });
  it("keeps solo sending available without a tier approval snapshot or approval-role capability", async () => {
    await pool.query("UPDATE inventory.warehouse_settings SET require_approval=false; UPDATE procurement.purchase_orders SET status='approved'");
    expect((await service.send(1, "wrong-user")).status).toBe("sent");
    expect((await evidence()).events.filter((row) => row.event_type === "approved")).toHaveLength(0);
  });

  it("ignores inactive tier controls during an optional solo approval while still checking the actor permission", async () => {
    await pool.query(`UPDATE inventory.warehouse_settings SET require_approval=false;
      INSERT INTO procurement.po_approval_tiers(id,tier_name,threshold_cents,approver_role,active) VALUES (2,'Duplicate dormant rule',1000,'lead',1)`);
    expect((await service.approve(1, "wrong-user")).status).toBe("approved");
    expect((await evidence()).events[0].payload_json.approval_authority).toMatchObject({ requireApproval: false, tier: null, matchedRoleId: null });
    expect((await service.send(1, "wrong-user")).status).toBe("sent");
  });
  it("rolls back provisional legacy cost repairs on role denial", async () => {
    await pool.query(`INSERT INTO procurement.purchase_order_lines(id,purchase_order_id,line_number,line_type,status,order_qty,unit_cost_cents,
      line_total_cents,pricing_basis,pricing_source,discount_cents,tax_cents,updated_at)
      VALUES (12,1,2,'fee','open',1,500,1,'legacy_unknown','manual',0,0,'2026-09-01T12:00:00')`);
    const before = await evidence();
    await expect(service.approve(1, "wrong-user")).rejects.toMatchObject({ details: { code: "PO_APPROVAL_ROLE_REQUIRED" } });
    expect(await evidence()).toEqual(before);
  });

  it("rolls back the approval and status history when its audit insert fails", async () => {
    const before = await evidence();
    await pool.query(`CREATE FUNCTION procurement.fail_approval_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected audit failure'; END $$;
      CREATE TRIGGER fail_approval_audit BEFORE INSERT ON procurement.po_events FOR EACH ROW EXECUTE FUNCTION procurement.fail_approval_audit()`);
    try {
      await expect(service.approve(1, "admin-user")).rejects.toThrow();
      expect(await evidence()).toEqual(before);
    } finally {
      await pool.query("DROP TRIGGER fail_approval_audit ON procurement.po_events; DROP FUNCTION procurement.fail_approval_audit()");
    }
  });

  it.each([
    "UPDATE procurement.po_events SET payload_json='{}' WHERE po_id=1",
    "DELETE FROM procurement.po_events WHERE po_id=1",
    "TRUNCATE procurement.po_events",
  ])("rejects direct event history mutation: %s", async (statement) => {
    await service.approve(1, "admin-user");
    const before = await evidence();
    await expect(pool.query(statement)).rejects.toMatchObject({ code: "23514", constraint: "po_event_history_immutable" });
    expect(await evidence()).toEqual(before);
  });

  it.each(["DELETE FROM procurement.purchase_orders WHERE id=1", "TRUNCATE procurement.purchase_orders CASCADE"])(
    "rejects parent removal including cascaded history: %s", async (statement) => {
      await service.approve(1, "admin-user");
      const before = await evidence();
      await expect(pool.query(statement)).rejects.toSatisfy(isPurchaseOrderHistoryConstraintViolation);
      expect(await evidence()).toEqual(before);
    });

  it.each(["status_history", "revisions"])("preserves legacy %s when no event exists", async (kind) => {
    await pool.query("UPDATE procurement.purchase_orders SET status='draft'");
    if (kind === "status_history") await pool.query("INSERT INTO procurement.po_status_history(purchase_order_id,to_status) VALUES (1,'draft')");
    else await pool.query("INSERT INTO procurement.po_revisions(purchase_order_id,change_type,old_value,new_value) VALUES (1,'price_changed','1','2')");
    const before = await evidence();
    await expect(pool.query("DELETE FROM procurement.purchase_orders WHERE id=1")).rejects.toMatchObject({ constraint: "purchase_order_history_retention" });
    await expect(service.deletePO(1)).rejects.toMatchObject({ statusCode: 409, details: { code: "PO_HISTORY_DELETE_BLOCKED", historyKinds: [kind] } });
    expect(await evidence()).toEqual(before);
  });

  it("returns an actionable HTTP error for the reachable stale-approval-to-draft delete path and allows cancellation", async () => {
    await service.approve(1, "admin-user");
    const originalApproval = (await evidence()).events[0];
    await pool.query("UPDATE procurement.po_approval_tiers SET approver_role='lead'");
    await service.send(1, "admin-user");
    await service.returnToDraft(1, "admin-user", "Review the changed policy");
    const before = await evidence();
    const response = await fetch(`${url}/api/purchase-orders/1`, { method: "DELETE" });
    expect(response.status).toBe(409);
    expect(await response.json()).toMatchObject({ error: expect.stringContaining("Cancel it instead"), details: { code: "PO_HISTORY_DELETE_BLOCKED" } });
    expect(await evidence()).toEqual(before);
    expect((await service.cancel(1, "Superseded purchase", "admin-user")).physicalStatus).toBe("cancelled");
    expect((await evidence()).events[0]).toEqual(originalApproval);
  });

  it("retains both approval decisions through reapproval and send", async () => {
    await service.approve(1, "admin-user");
    const originalApproval = (await evidence()).events[0];
    await pool.query("UPDATE procurement.po_approval_tiers SET approver_role='lead'");
    await service.send(1, "admin-user");
    await service.approve(1, "lead-user");
    expect((await service.send(1, "lead-user")).status).toBe("sent");
    const approvals = (await evidence()).events.filter((row) => row.event_type === "approved");
    expect(approvals).toHaveLength(2);
    expect(approvals[0]).toEqual(originalApproval);
    expect(approvals[1].payload_json.approval_authority.actor.userId).toBe("lead-user");
  });

  it("preserves existing rows when the additive retention migration runs again", async () => {
    await service.approve(1, "admin-user");
    const before = await evidence();
    await pool.query(retentionMigration);
    expect(await evidence()).toEqual(before);
    await expect(pool.query("DELETE FROM procurement.po_events")).rejects.toMatchObject({ constraint: "po_event_history_immutable" });
  });

  it("keeps deletion of a history-free manual draft transactional and guarded by its current status", async () => {
    await pool.query("UPDATE procurement.purchase_orders SET status='draft'");
    expect(await service.deletePO(1)).toBe(true);
    expect((await evidence()).header).toHaveLength(0);
    expect((await evidence()).lines).toHaveLength(0);
    await expect(service.deletePO(1)).rejects.toMatchObject({ statusCode: 404 });
  });

  it("retains the existing recommendation handoff denial inside the delete transaction", async () => {
    await pool.query("UPDATE procurement.purchase_orders SET status='draft'; INSERT INTO procurement.purchasing_recommendation_po_handoffs(id,purchase_order_id) VALUES (1,1)");
    const before = await evidence();
    await expect(service.deletePO(1)).rejects.toMatchObject({ statusCode: 409, details: { code: "RECOMMENDATION_PO_DELETE_BLOCKED", handoffId: 1 } });
    expect(await evidence()).toEqual(before);
  });

  it("observes an event committed while the delete owner waits for the parent row lock", async () => {
    await pool.query("UPDATE procurement.purchase_orders SET status='draft'");
    const writer = await pool.connect();
    let deletion: Promise<unknown> | undefined;
    try {
      await writer.query("BEGIN");
      const writerPid = (await writer.query("SELECT pg_backend_pid() AS pid")).rows[0].pid;
      await writer.query("INSERT INTO procurement.po_events(po_id,event_type,actor_type,payload_json) VALUES (1,'reviewed','user','{}')");
      deletion = service.deletePO(1).then((value) => ({ value }), (error) => ({ error }));
      let blocked = false;
      for (let attempt = 0; attempt < 100; attempt++) {
        const result = await pool.query("SELECT EXISTS (SELECT 1 FROM pg_stat_activity WHERE $1 = ANY(pg_blocking_pids(pid))) AS blocked", [writerPid]);
        if (result.rows[0].blocked) { blocked = true; break; }
        await new Promise((resolveValue) => setTimeout(resolveValue, 10));
      }
      expect(blocked).toBe(true);
      await writer.query("COMMIT");
      expect(await deletion).toMatchObject({ error: { statusCode: 409, details: { code: "PO_HISTORY_DELETE_BLOCKED" } } });
      const after = await evidence();
      expect(after.header).toHaveLength(1);
      expect(after.events).toHaveLength(1);
    } finally {
      await writer.query("ROLLBACK");
      await deletion;
      writer.release();
    }
  });
  it.each([
    ["grant", "DELETE FROM identity.auth_role_permissions WHERE id=1", "PO_APPROVAL_PERMISSION_REQUIRED"],
    ["membership", "DELETE FROM identity.auth_user_roles WHERE id=1", "PO_APPROVAL_PERMISSION_REQUIRED"],
    ["active account", "UPDATE identity.users SET active=0 WHERE id='admin-user'", "PO_APPROVAL_ACTOR_INACTIVE"],
    ["role name", "UPDATE identity.auth_roles SET name='Retired Administrator' WHERE id=1", "PO_APPROVAL_ROLE_REQUIRED"],
    ["permission", "UPDATE identity.auth_permissions SET action='view' WHERE id=1", "PO_APPROVAL_PERMISSION_REQUIRED"],
  ])("holds current %s authority until approval commits, then denies after revocation", async (_label, revokeSql, denialCode) => {
    const captured = deferred();
    const continueApproval = deferred();
    const controlled = makeService({ readApprovalActor: async (tx, userId) => {
      const actor = await readPurchaseApprovalActor(tx, userId);
      captured.resolve();
      await continueApproval.promise;
      return actor;
    } });
    const approval = controlled.approve(1, "admin-user");
    await captured.promise;
    const revoker = await pool.connect();
    let deletion: Promise<pg.QueryResult> | undefined;
    try {
      await revoker.query("BEGIN");
      const pid = (await revoker.query("SELECT pg_backend_pid() AS pid")).rows[0].pid;
      deletion = revoker.query(revokeSql);
      let blocked = false;
      for (let attempt = 0; attempt < 100; attempt++) {
        const result = await pool.query("SELECT wait_event_type FROM pg_stat_activity WHERE pid=$1", [pid]);
        if (result.rows[0]?.wait_event_type === "Lock") { blocked = true; break; }
        await new Promise((resolveValue) => setTimeout(resolveValue, 10));
      }
      expect(blocked).toBe(true);
      continueApproval.resolve();
      expect((await approval).status).toBe("approved");
      await deletion;
      await revoker.query("COMMIT");
      const event = (await evidence()).events[0];
      expect(event.payload_json.approval_authority.actor.approvalGrantIds).toEqual([1]);
      await pool.query("UPDATE procurement.purchase_orders SET status='pending_approval'");
      const before = await evidence();
      await expect(service.approve(1, "admin-user")).rejects.toMatchObject({ details: { code: denialCode } });
      expect(await evidence()).toEqual(before);
    } finally {
      continueApproval.resolve();
      await approval.catch(() => undefined);
      await deletion?.catch(() => undefined);
      await revoker.query("ROLLBACK");
      revoker.release();
    }
  });
});