import { getTableColumns, SQL, type Table } from "drizzle-orm";
import { getTableConfig, PgDialect } from "drizzle-orm/pg-core";

type PgTable = Parameters<typeof getTableConfig>[0];

export function identifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`;
}

function defaultExpression(value: unknown): string {
  if (value instanceof SQL) {
    const query = new PgDialect().sqlToQuery(value);
    if (query.params.length !== 0) throw new Error("Fixture default must not contain parameters");
    return query.sql;
  }
  if (value === null) return "NULL";
  if (typeof value === "string") return `'${value.replaceAll("'", "''")}'`;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  throw new Error("Unsupported schema default in shipment-line fixture");
}

export function qualifiedTable(table: PgTable): string {
  const definition = getTableConfig(table);
  return `${identifier(definition.schema ?? "public")}.${identifier(definition.name)}`;
}

/** Use actual column types/defaults. Identity mode permits explicit deterministic seed IDs. */
export function fixtureTable(table: PgTable): string {
  const columns = Object.values(getTableColumns(table as Table)).map((column) => {
    if (column.primary && column.name === "id") {
      const type = column.getSQLType().includes("big") ? "bigint" : "integer";
      return `${identifier(column.name)} ${type} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    }
    const defaultSql = column.default === undefined ? "" : ` DEFAULT ${defaultExpression(column.default)}`;
    return `${identifier(column.name)} ${column.getSQLType()}${defaultSql}${column.notNull ? " NOT NULL" : ""}`;
  });
  return `CREATE TABLE ${qualifiedTable(table)} (${columns.join(", ")})`;
}

/** Install actual FK actions between fixture tables, excluding unrelated user/WMS dependencies. */
export function fixtureForeignKeys(tables: readonly PgTable[]): string[] {
  const included = new Set(tables.map(qualifiedTable));
  return tables.flatMap((table) => getTableConfig(table).foreignKeys.flatMap((foreignKey) => {
    const reference = foreignKey.reference();
    if (!included.has(qualifiedTable(reference.foreignTable))) return [];
    const localColumns = reference.columns.map((column) => identifier(column.name)).join(", ");
    const foreignColumns = reference.foreignColumns.map((column) => identifier(column.name)).join(", ");
    return [`ALTER TABLE ${qualifiedTable(table)} ADD FOREIGN KEY (${localColumns}) REFERENCES ${qualifiedTable(reference.foreignTable)} (${foreignColumns}) ON DELETE ${foreignKey.onDelete ?? "no action"} ON UPDATE ${foreignKey.onUpdate ?? "no action"}`];
  }));
}
