import { createHash, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { config } from "dotenv";
import { getTableColumns, SQL, sql, type Table } from "drizzle-orm";
import { getTableConfig, PgDialect } from "drizzle-orm/pg-core";
import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import * as schema from "@shared/schema";
import { shipmentCostVersion } from "../../shipment-cost-version";
import type { ShipmentCostCommand } from "../../shipment-cost-commands";
import type { ShipmentTrackingService } from "../../shipment-tracking.service";
import type { FinancialCommandDescriptor } from "../../../../platform/commands/transactional-command.service";

config({ path: resolve(process.cwd(), ".env.test") });
const TEST_DB_URL = process.env.ECHELON_TEST_DATABASE_URL;
const DISPOSABLE = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const databaseTests = TEST_DB_URL && DISPOSABLE ? describe : describe.skip;
const NOW = new Date("2026-09-06T12:00:00.000Z");

function identifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`;
}

function defaultExpression(value: unknown): string {
  if (value instanceof SQL) {
    const query = new PgDialect().sqlToQuery(value);
    if (query.params.length !== 0) throw new Error("Fixture default must not contain parameters");
    return query.sql;
  }
  if (typeof value === "string") return `'${value.replaceAll("'", "''")}'`;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  throw new Error("Unsupported schema default in shipment-cost fixture");
}

/** Full real column definitions/defaults; only the relevant cross-table FKs are installed below. */
function fixtureTable(table: Parameters<typeof getTableConfig>[0]): string {
  const definition = getTableConfig(table);
  const columns = Object.values(getTableColumns(table as Table)).map((column) => {
    if (column.primary && column.name === "id") {
      const type = column.getSQLType().includes("big") ? "bigint" : "integer";
      return `${identifier(column.name)} ${type} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    }
    const defaultSql = column.default === undefined ? "" : ` DEFAULT ${defaultExpression(column.default)}`;
    return `${identifier(column.name)} ${column.getSQLType()}${defaultSql}${column.notNull ? " NOT NULL" : ""}`;
  });
  return `CREATE TABLE ${identifier(definition.schema ?? "public")}.${identifier(definition.name)} (${columns.join(", ")})`;
}

databaseTests.sequential("shipment cost command PostgreSQL guarantees", () => {
  const runId = randomUUID().replaceAll("-", "");
  const actorId = `shipment-cost-test-${runId}`;
  const delegateId = `${actorId}-delegate`;
  let pool: pg.Pool;
  let database: ReturnType<typeof drizzle<typeof schema>>;
  let service: ShipmentTrackingService;
  let createService: typeof import("../../shipment-tracking.service").createShipmentTrackingService;
  let storage: typeof import("../../procurement.storage").procurementMethods;
  let commandFactory: typeof import("../../shipment-cost-commands").createShipmentCostCommands;
  let repositoryFactory: typeof import("../../../../platform/commands/command-results.repository").createDrizzleFinancialCommandRepository;
  let defaultModulePool: pg.Pool | undefined;
  let ownsProcurement = false;
  let ownsAudit = false;
  let auditReady = false;
  let commandTablesReady = false;

  async function readCost(id = 31) {
    const cost = await storage.getInboundFreightCostById(id, database);
    if (!cost) throw new Error(`Fixture cost ${id} is missing`);
    return cost;
  }

  async function patch(fields: Record<string, unknown>, id = 31): Promise<ShipmentCostCommand> {
    return { operation: "update", resourceId: id, body: { expectedVersion: shipmentCostVersion(await readCost(id)), ...fields } };
  }

  async function remove(id = 31): Promise<ShipmentCostCommand> {
    return { operation: "delete", resourceId: id, body: { expectedVersion: shipmentCostVersion(await readCost(id)), reason: "Fixture correction" } };
  }

  function execute(command: ShipmentCostCommand, target: ShipmentTrackingService = service) {
    return database.transaction((tx) => target.executeCostCommandInTransaction(tx, command, actorId, NOW));
  }

  async function state() {
    const results = await Promise.all([
      pool.query("SELECT * FROM procurement.inbound_freight_costs ORDER BY id"),
      pool.query("SELECT * FROM procurement.inbound_shipments ORDER BY id"),
      pool.query("SELECT * FROM procurement.inbound_shipment_lines ORDER BY id"),
      pool.query("SELECT * FROM procurement.inbound_freight_allocations ORDER BY id"),
      pool.query("SELECT * FROM public.audit_events WHERE actor = ANY($1::text[]) ORDER BY id", [[actorId, delegateId]]),
      pool.query("SELECT * FROM procurement.vendor_invoice_lines ORDER BY id"),
      pool.query("SELECT * FROM procurement.landed_cost_snapshots ORDER BY id"),
      pool.query("SELECT * FROM procurement.inbound_shipment_status_history ORDER BY id"),
    ]);
    return results.map((result) => result.rows);
  }

  function descriptor(name: string, command: ShipmentCostCommand): FinancialCommandDescriptor {
    return {
      actorType: "service", actorId: "procurement.shipment-cost",
      method: command.operation === "create" ? "POST" : command.operation === "update" ? "PATCH" : "DELETE",
      routeTemplate: command.operation === "create" ? "/api/inbound-shipments/:id/costs" : "/api/inbound-shipments/costs/:costId",
      resourceKey: `${command.operation === "create" ? "shipment" : "shipment_cost"}:${command.resourceId}`,
      idempotencyKey: `${runId}-${name}`,
      requestHash: createHash("sha256").update(JSON.stringify(command)).digest("hex"),
      commandName: `procurement.shipment_cost.${command.operation}`, contractVersion: 1,
    };
  }

  /** Observe a real PostgreSQL blocker rather than assuming an arbitrary delay proves serialization. */
  async function waitUntilBlocked(pid: number) {
    const deadline = Date.now() + 5_000;
    while (Date.now() < deadline) {
      const result = await pool.query<{ blocked: boolean }>("SELECT cardinality(pg_blocking_pids($1)) > 0 AS blocked", [pid]);
      if (result.rows[0]?.blocked) return;
      await new Promise((resolveWait) => setTimeout(resolveWait, 20));
    }
    throw new Error("Shipment command did not block on the concurrently held PostgreSQL lock");
  }

  async function contend(command: ShipmentCostCommand, hold: (client: pg.PoolClient) => Promise<unknown>) {
    const holder = await pool.connect();
    let transactionOpen = false;
    let outcome: Promise<{ ok: true; value: unknown } | { ok: false; error: unknown }> | undefined;
    try {
      await holder.query("BEGIN");
      transactionOpen = true;
      await hold(holder);
      let reportPid!: (pid: number) => void;
      const ready = new Promise<number>((resolveReady) => { reportPid = resolveReady; });
      outcome = database.transaction(async (tx) => {
        await tx.execute(sql`SET LOCAL statement_timeout = '8s'`);
        const result = await tx.execute(sql`SELECT pg_backend_pid() AS pid`);
        reportPid(Number(result.rows[0].pid));
        return service.executeCostCommandInTransaction(tx, command, actorId, NOW);
      }).then((value) => ({ ok: true as const, value }), (error: unknown) => ({ ok: false as const, error }));
      await waitUntilBlocked(await ready);
      await holder.query("COMMIT");
      transactionOpen = false;
      return await outcome;
    } finally {
      if (transactionOpen) await holder.query("ROLLBACK");
      holder.release();
      await outcome;
    }
  }

  beforeAll(async () => {
    if ([process.env.DATABASE_URL, process.env.EXTERNAL_DATABASE_URL].filter(Boolean).includes(TEST_DB_URL!)) {
      throw new Error("Shipment command integration requires a separate explicitly disposable database");
    }
    pool = new pg.Pool({ connectionString: TEST_DB_URL, max: 8, ssl: /localhost|127\.0\.0\.1/.test(TEST_DB_URL!) ? false : { rejectUnauthorized: false } });
    await pool.query("CREATE SCHEMA procurement");
    ownsProcurement = true;
    for (const table of [schema.vendors, schema.inboundShipments, schema.inboundShipmentLines, schema.vendorInvoices, schema.inboundFreightCosts, schema.inboundFreightAllocations, schema.vendorInvoiceLines, schema.landedCostSnapshots, schema.inboundShipmentStatusHistory]) {
      await pool.query(fixtureTable(table));
    }
    const auditExists = await pool.query("SELECT to_regclass('public.audit_events') AS relation");
    if (!auditExists.rows[0].relation) {
      await pool.query(fixtureTable(schema.auditEvents));
      ownsAudit = true;
    }
    auditReady = true;
    await pool.query(`
      ALTER TABLE procurement.inbound_freight_costs
        ADD FOREIGN KEY (inbound_shipment_id) REFERENCES procurement.inbound_shipments(id) ON DELETE CASCADE,
        ADD FOREIGN KEY (vendor_id) REFERENCES procurement.vendors(id) ON DELETE SET NULL,
        ADD FOREIGN KEY (vendor_invoice_id) REFERENCES procurement.vendor_invoices(id) ON DELETE SET NULL;
      ALTER TABLE procurement.inbound_shipment_lines
        ADD FOREIGN KEY (inbound_shipment_id) REFERENCES procurement.inbound_shipments(id) ON DELETE CASCADE;
      ALTER TABLE procurement.vendor_invoice_lines
        ADD FOREIGN KEY (vendor_invoice_id) REFERENCES procurement.vendor_invoices(id) ON DELETE CASCADE,
        ADD FOREIGN KEY (freight_cost_id) REFERENCES procurement.inbound_freight_costs(id) ON DELETE SET NULL;
      ALTER TABLE procurement.inbound_freight_allocations
        ADD FOREIGN KEY (shipment_cost_id) REFERENCES procurement.inbound_freight_costs(id) ON DELETE CASCADE,
        ADD FOREIGN KEY (inbound_shipment_line_id) REFERENCES procurement.inbound_shipment_lines(id) ON DELETE CASCADE,
        ADD UNIQUE (shipment_cost_id, inbound_shipment_line_id);
      ALTER TABLE procurement.landed_cost_snapshots
        ADD FOREIGN KEY (inbound_shipment_line_id) REFERENCES procurement.inbound_shipment_lines(id) ON DELETE CASCADE,
        ADD UNIQUE (inbound_shipment_line_id);
      ALTER TABLE procurement.inbound_shipment_status_history
        ADD FOREIGN KEY (inbound_shipment_id) REFERENCES procurement.inbound_shipments(id) ON DELETE CASCADE;
    `);
    for (const migration of ["136_financial_command_results.sql", "140_financial_command_operations.sql"]) {
      await pool.query(readFileSync(resolve(process.cwd(), "migrations", migration), "utf8"));
    }
    commandTablesReady = true;
    database = drizzle(pool, { schema });

    // Application modules export a default pool. Prevent it from ever receiving
    // a production URL; every test operation injects the disposable database.
    const previousDatabaseUrl = process.env.DATABASE_URL;
    const previousExternalUrl = process.env.EXTERNAL_DATABASE_URL;
    delete process.env.DATABASE_URL;
    delete process.env.EXTERNAL_DATABASE_URL;
    try {
      const [serviceModule, storageModule, commandModule, repositoryModule, databaseModule] = await Promise.all([
        import("../../shipment-tracking.service"), import("../../procurement.storage"),
        import("../../shipment-cost-commands"), import("../../../../platform/commands/command-results.repository"),
        import("../../../../db"),
      ]);
      createService = serviceModule.createShipmentTrackingService;
      storage = storageModule.procurementMethods;
      commandFactory = commandModule.createShipmentCostCommands;
      repositoryFactory = repositoryModule.createDrizzleFinancialCommandRepository;
      defaultModulePool = databaseModule.pool;
      service = createService(database, storage as Parameters<typeof createService>[1]);
    } finally {
      if (previousDatabaseUrl === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = previousDatabaseUrl;
      if (previousExternalUrl === undefined) delete process.env.EXTERNAL_DATABASE_URL;
      else process.env.EXTERNAL_DATABASE_URL = previousExternalUrl;
    }
  });

  beforeEach(async () => {
    if (!ownsProcurement) throw new Error("Fixture schema ownership was not established");
    await pool.query(`TRUNCATE procurement.landed_cost_snapshots, procurement.inbound_shipment_status_history,
      procurement.vendor_invoice_lines, procurement.inbound_freight_allocations,
      procurement.inbound_freight_costs, procurement.inbound_shipment_lines, procurement.vendor_invoices,
      procurement.inbound_shipments, procurement.vendors RESTART IDENTITY CASCADE`);
    await pool.query("DELETE FROM public.audit_events WHERE actor = ANY($1::text[])", [[actorId, delegateId]]);
    await pool.query(`
      INSERT INTO procurement.vendors(id,code,name) VALUES (5,'TEST-A','Supplier A'),(6,'TEST-B','Supplier B');
      INSERT INTO procurement.inbound_shipments(id,shipment_number,status,allocation_method_default,estimated_total_cost_cents,actual_total_cost_cents)
        VALUES (1,'TEST-SHIP-1','costing','by_line_count',500,500),(9,'TEST-SHIP-9','closed','by_line_count',0,0);
      INSERT INTO procurement.inbound_shipment_lines(id,inbound_shipment_id,sku,qty_shipped,allocated_cost_cents,landed_unit_cost_cents)
        VALUES (11,1,'TEST-SKU',5,500,100);
      INSERT INTO procurement.vendor_invoices(id,invoice_number,vendor_id,inbound_shipment_id,invoiced_amount_cents,balance_cents)
        VALUES (71,'TEST-INV',5,1,500,500);
      INSERT INTO procurement.inbound_freight_costs(id,inbound_shipment_id,cost_type,estimated_cents,actual_cents,vendor_id,allocation_method,cost_status)
        VALUES (31,1,'freight',500,500,5,'by_line_count','finalized');
      INSERT INTO procurement.inbound_freight_allocations(id,shipment_cost_id,inbound_shipment_line_id,allocated_cents)
        VALUES (41,31,11,500);
    `);
  });

  afterAll(async () => {
    try {
      if (pool) {
        const cleanup: Promise<unknown>[] = [];
        if (commandTablesReady) cleanup.push(pool.query("DELETE FROM public.financial_command_results WHERE actor_id = $1 AND idempotency_key LIKE $2", ["procurement.shipment-cost", `${runId}-%`]));
        if (ownsAudit) cleanup.push(pool.query("DROP TABLE public.audit_events"));
        else if (auditReady) cleanup.push(pool.query("DELETE FROM public.audit_events WHERE actor = ANY($1::text[])", [[actorId, delegateId]]));
        if (ownsProcurement) cleanup.push(pool.query("DROP SCHEMA procurement CASCADE"));
        const failures = (await Promise.allSettled(cleanup)).filter((result): result is PromiseRejectedResult => result.status === "rejected");
        if (failures.length > 0) throw new AggregateError(failures.map((failure) => failure.reason), "Shipment command fixture cleanup failed");
      }
    } finally {
      await pool?.end();
      await defaultModulePool?.end();
    }
  });

  it("creates, allocates and audits one charge with a versioned result", async () => {
    const result = await execute({ operation: "create", resourceId: 1, body: { costType: "insurance", actualCents: 125, vendorId: 5, reason: "Insurance quote" } });
    expect(result).toMatchObject({ inboundShipmentId: 1, actualCents: 125, estimatedCents: null, currency: "USD", costStatus: "finalized", createdAt: NOW, updatedAt: NOW, version: expect.stringMatching(/^[0-9a-f]{64}$/) });
    expect((await pool.query("SELECT actual_total_cost_cents FROM procurement.inbound_shipments WHERE id=1")).rows[0]).toEqual({ actual_total_cost_cents: "625" });
    expect((await pool.query("SELECT SUM(allocated_cents)::text AS total FROM procurement.inbound_freight_allocations")).rows[0].total).toBe("625");
    const audit = (await pool.query("SELECT * FROM public.audit_events WHERE actor=$1", [actorId])).rows[0];
    expect(audit).toMatchObject({ action: "procurement.shipment_cost.created", actor: actorId, timestamp: NOW, changes: { before: null, after: expect.objectContaining({ actualCents: 125, createdAt: NOW.toISOString(), updatedAt: NOW.toISOString() }) }, context: { shipmentId: 1, reason: "Insurance quote" } });
  });

  it("rejects overflow in mixed actual/estimate effective totals even when each separate total is safe", async () => {
    await pool.query("UPDATE procurement.inbound_freight_costs SET actual_cents=NULL,estimated_cents=1 WHERE id=31");
    const before = await state();
    await expect(execute({
      operation: "create", resourceId: 1,
      body: { costType: "insurance", actualCents: Number.MAX_SAFE_INTEGER },
    })).rejects.toMatchObject({ details: { code: "SHIPMENT_COST_TOTAL_OVERFLOW" } });
    expect(await state()).toEqual(before);
  });

  it("keeps actual zero distinct from null and reallocates the fallback estimate", async () => {
    const zero = await execute(await patch({ actualCents: 0 }));
    expect(zero).toMatchObject({ actualCents: 0, estimatedCents: 500, costStatus: "finalized" });
    expect((await pool.query("SELECT allocated_cost_cents FROM procurement.inbound_shipment_lines WHERE id=11")).rows[0].allocated_cost_cents).toBe("0");
    expect(await execute(await patch({ actualCents: null }))).toMatchObject({ actualCents: null, costStatus: "estimated" });
    expect((await pool.query("SELECT allocated_cost_cents FROM procurement.inbound_shipment_lines WHERE id=11")).rows[0].allocated_cost_cents).toBe("500");
  });

  it("rejects protected identity and AP fields without any domain or audit write", async () => {
    const before = await state();
    for (const fields of [{ inboundShipmentId: 9 }, { vendorInvoiceId: 71 }, { paidDate: NOW.toISOString() }, { costStatus: "paid" }, { id: 99 }, { createdAt: NOW.toISOString() }]) {
      await expect(execute(await patch(fields))).rejects.toMatchObject({ name: "ZodError" });
    }
    await expect(execute({ operation: "create", resourceId: 1, body: { costType: "freight", actualCents: 10, inboundShipmentId: 9 } })).rejects.toMatchObject({ name: "ZodError" });
    expect(await state()).toEqual(before);
  });

  it.each(["closed", "cancelled"])("rejects create, update and delete under a %s parent", async (status) => {
    await pool.query("UPDATE procurement.inbound_shipments SET status=$1 WHERE id=1", [status]);
    const before = await state();
    for (const command of [{ operation: "create" as const, resourceId: 1, body: { costType: "freight", actualCents: 25 } }, await patch({ notes: "Cannot change" }), await remove()]) {
      await expect(execute(command)).rejects.toMatchObject({ statusCode: 409, details: { code: "SHIPMENT_COST_TERMINAL" } });
    }
    expect(await state()).toEqual(before);
  });

  it("preserves signed legacy amounts and unknown currency when correcting metadata", async () => {
    await pool.query("UPDATE procurement.inbound_freight_costs SET actual_cents=-55,currency=NULL,exchange_rate=NULL WHERE id=31");
    const before = await state();
    expect(await execute(await patch({ notes: "Credit evidence retained" }))).toMatchObject({ actualCents: -55, currency: null, exchangeRate: null, notes: "Credit evidence retained", updatedAt: NOW });
    const after = await state();
    expect((await readCost()).updatedAt).toEqual(NOW);
    expect(after[4][0].timestamp).toEqual(NOW);
    expect(after.slice(1, 4)).toEqual(before.slice(1, 4));
    await expect(execute(await patch({ actualCents: 0 }))).rejects.toMatchObject({ statusCode: 409, details: { code: "SHIPMENT_COST_CURRENCY_UNSUPPORTED" } });
  });

  it("blocks economics when another charge has an unsupported currency basis", async () => {
    await pool.query("INSERT INTO procurement.inbound_freight_costs(id,inbound_shipment_id,cost_type,actual_cents,currency) VALUES(32,1,'other',100,'EUR')");
    const before = await state();
    await expect(execute(await patch({ actualCents: 501 }))).rejects.toMatchObject({ details: { code: "SHIPMENT_COST_CURRENCY_UNSUPPORTED" } });
    expect(await state()).toEqual(before);
  });

  it("protects invoice-owned fields and permits separate descriptive evidence", async () => {
    await pool.query("UPDATE procurement.inbound_freight_costs SET vendor_invoice_id=71,cost_status='invoiced' WHERE id=31");
    for (const fields of [{ vendorId: 6 }, { actualCents: 600 }, { allocationMethod: "by_weight" }, { invoiceDate: "2026-09-07" }]) {
      await expect(execute(await patch(fields))).rejects.toMatchObject({ details: { code: "SHIPMENT_COST_AP_OWNED" } });
    }
    expect(await execute(await patch({ description: "Carrier evidence" }))).toMatchObject({ vendorInvoiceId: 71, vendorId: 5, actualCents: 500, description: "Carrier evidence" });
    await expect(execute(await remove())).rejects.toMatchObject({ details: { code: "SHIPMENT_COST_AP_OWNED" } });
  });

  it("preserves invoice-line source history after the cost header has been unlinked", async () => {
    await pool.query("INSERT INTO procurement.vendor_invoice_lines(id,vendor_invoice_id,freight_cost_id,line_number,qty_invoiced,unit_cost_cents,line_total_cents) VALUES(91,71,31,1,1,500,500)");
    const before = await state();
    await expect(execute(await remove())).rejects.toMatchObject({ details: { code: "SHIPMENT_COST_AP_OWNED" } });
    await expect(execute(await patch({ actualCents: 600 }))).rejects.toMatchObject({ details: { code: "SHIPMENT_COST_AP_OWNED" } });
    expect(await state()).toEqual(before);
  });

  it("deletes only an unreferenced charge and updates totals, allocations and audit together", async () => {
    expect(await execute(await remove())).toEqual({ success: true });
    expect((await pool.query("SELECT * FROM procurement.inbound_freight_costs")).rows).toEqual([]);
    expect((await pool.query("SELECT * FROM procurement.inbound_freight_allocations")).rows).toEqual([]);
    expect((await pool.query("SELECT allocated_cost_cents FROM procurement.inbound_shipment_lines WHERE id=11")).rows[0].allocated_cost_cents).toBe("0");
    expect((await pool.query("SELECT changes FROM public.audit_events WHERE actor=$1", [actorId])).rows[0].changes).toMatchObject({ before: { id: 31 }, after: null });
  });

  it("rolls back the cost and totals when the allocation write fails", async () => {
    const failingStorage = { ...storage, async bulkCreateInboundFreightCostAllocations(...args: Parameters<typeof storage.bulkCreateInboundFreightCostAllocations>) {
      await storage.bulkCreateInboundFreightCostAllocations(...args);
      throw new Error("Injected failure after real allocation insert");
    } };
    const failingService = createService(database, failingStorage as Parameters<typeof createService>[1]);
    const before = await state();
    await expect(execute(await patch({ actualCents: 777 }), failingService)).rejects.toThrow("Injected failure after real allocation insert");
    expect(await state()).toEqual(before);
  });

  it("rolls back completed cost and allocation writes when audit persistence fails", async () => {
    const before = await state();
    await pool.query("ALTER TABLE public.audit_events ADD CONSTRAINT shipment_cost_test_reject_audit CHECK(action <> 'procurement.shipment_cost.amended')");
    try {
      await expect(execute(await patch({ actualCents: 777 }))).rejects.toThrow();
      expect(await state()).toEqual(before);
    } finally {
      await pool.query("ALTER TABLE public.audit_events DROP CONSTRAINT shipment_cost_test_reject_audit");
    }
  });

  it("allows exactly one concurrent edit with the same observed version", async () => {
    const first = await patch({ notes: "Editor A" });
    const second = { ...first, body: { ...(first.body as object), notes: "Editor B" } };
    const results = await Promise.allSettled([execute(first), execute(second)]);
    expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1);
    expect(results.find((result) => result.status === "rejected")).toMatchObject({ reason: { statusCode: 409, details: { code: "SHIPMENT_COST_VERSION_CONFLICT" } } });
    expect((await pool.query("SELECT * FROM public.audit_events WHERE actor=$1", [actorId])).rows).toHaveLength(1);
  });

  it("rechecks the version after waiting for a concurrent AP invoice link", async () => {
    const result = await contend(await patch({ vendorId: 6 }), (client) => client.query("UPDATE procurement.inbound_freight_costs SET vendor_invoice_id=71,cost_status='invoiced' WHERE id=31"));
    expect(result).toMatchObject({ ok: false, error: { statusCode: 409, details: { code: "SHIPMENT_COST_VERSION_CONFLICT" } } });
    expect(await readCost()).toMatchObject({ vendorId: 5, vendorInvoiceId: 71 });
  });

  it("rechecks invoice-line ownership after a lock wait even when the cost version is unchanged", async () => {
    const observed = shipmentCostVersion(await readCost());
    const result = await contend(await patch({ actualCents: 900 }), async (client) => {
      await client.query("SELECT id FROM procurement.inbound_freight_costs WHERE id=31 FOR UPDATE");
      await client.query("INSERT INTO procurement.vendor_invoice_lines(id,vendor_invoice_id,freight_cost_id,line_number,qty_invoiced,unit_cost_cents,line_total_cents) VALUES(91,71,31,1,1,500,500)");
    });
    expect(result).toMatchObject({ ok: false, error: { details: { code: "SHIPMENT_COST_AP_OWNED" } } });
    expect(shipmentCostVersion(await readCost())).toBe(observed);
    expect((await pool.query("SELECT freight_cost_id FROM procurement.vendor_invoice_lines WHERE id=91")).rows[0].freight_cost_id).toBe(31);
  });

  it("rechecks terminal parent status after waiting for a concurrent close", async () => {
    const result = await contend(await patch({ actualCents: 900 }), (client) => client.query("UPDATE procurement.inbound_shipments SET status='closed' WHERE id=1"));
    expect(result).toMatchObject({ ok: false, error: { details: { code: "SHIPMENT_COST_TERMINAL" } } });
    expect((await readCost()).actualCents).toBe(500);
  });


  it("prevents draft parent deletion from bypassing individual charge history", async () => {
    await pool.query("UPDATE procurement.inbound_shipments SET status='draft' WHERE id=1");
    const before = await state();
    await expect(service.deleteShipment(1)).rejects.toMatchObject({ statusCode: 409, details: { code: "SHIPMENT_HAS_COST_HISTORY" } });
    expect(await state()).toEqual(before);
  });

  it("uses the parent-delete transaction executor so a later failure restores the draft", async () => {
    await pool.query("UPDATE procurement.inbound_shipments SET status='draft' WHERE id=9");
    const abortingDatabase = {
      transaction: (work: (tx: unknown) => Promise<unknown>) => database.transaction(async (tx) => {
        expect(await work(tx)).toBe(true);
        expect((await tx.execute(sql`SELECT id FROM procurement.inbound_shipments WHERE id=9`)).rows).toEqual([]);
        throw new Error("Injected failure after parent deletion");
      }),
    };
    const abortingService = createService(abortingDatabase, storage as Parameters<typeof createService>[1]);
    await expect(abortingService.deleteShipment(9)).rejects.toThrow("Injected failure after parent deletion");
    expect((await pool.query("SELECT status FROM procurement.inbound_shipments WHERE id=9")).rows).toEqual([{ status: "draft" }]);
    expect(await service.deleteShipment(9)).toBe(true);
  });

  it("preserves historical cost status when unchanged actual cents accompany metadata", async () => {
    await pool.query("UPDATE procurement.inbound_freight_costs SET cost_status='paid' WHERE id=31");
    const before = await state();
    expect(await execute(await patch({ actualCents: 500, description: "Historical evidence" }))).toMatchObject({ actualCents: 500, costStatus: "paid" });
    expect((await state()).slice(1, 4)).toEqual(before.slice(1, 4));
  });

  it("treats unit-rate numeric formatting as unchanged and does not reallocate", async () => {
    expect((await readCost()).exchangeRate).toBe("1.0000");
    const before = await state();
    expect(await execute(await patch({ exchangeRate: "1", notes: "Equivalent unit rate" }))).toMatchObject({ exchangeRate: "1.0000" });
    expect((await state()).slice(1, 4)).toEqual(before.slice(1, 4));
  });


  it("commits close finalization and history before waiting cost edits or cancellations can proceed", async () => {
    const command = await patch({ actualCents: 900 });
    let reportLocked!: () => void;
    let releaseClose!: () => void;
    const locked = new Promise<void>((resolveLocked) => { reportLocked = resolveLocked; });
    const release = new Promise<void>((resolveRelease) => { releaseClose = resolveRelease; });
    let pauseFirstLineRead = true;
    const closingStorage = {
      ...storage,
      async getInboundShipmentLines(...args: Parameters<typeof storage.getInboundShipmentLines>) {
        const lines = await storage.getInboundShipmentLines(...args);
        if (pauseFirstLineRead) {
          pauseFirstLineRead = false;
          reportLocked();
          await release;
        }
        return lines;
      },
      // This fixture proves procurement finalization. Inventory lot posting is
      // a separate existing post-commit operation and has no fixture candidates.
      async getProvisionalLotsByShipment() { return []; },
    };
    const closingService = createService(database, closingStorage as Parameters<typeof createService>[1], undefined, () => NOW);
    const closing = closingService.close(1, actorId, "Finalize fixture shipment")
      .then((value) => ({ ok: true as const, value }), (error: unknown) => ({ ok: false as const, error }));
    let editing: Promise<{ ok: true; value: unknown } | { ok: false; error: unknown }> | undefined;
    let cancelling: Promise<{ ok: true; value: unknown } | { ok: false; error: unknown }> | undefined;
    try {
      await Promise.race([locked, closing.then((result) => {
        if (!result.ok) throw result.error;
        throw new Error("Close completed without reaching the locked finalization boundary");
      })]);
      let reportPid!: (pid: number) => void;
      const ready = new Promise<number>((resolveReady) => { reportPid = resolveReady; });
      editing = database.transaction(async (tx) => {
        await tx.execute(sql`SET LOCAL statement_timeout = '8s'`);
        const result = await tx.execute(sql`SELECT pg_backend_pid() AS pid`);
        reportPid(Number(result.rows[0].pid));
        return service.executeCostCommandInTransaction(tx, command, actorId, NOW);
      }).then((value) => ({ ok: true as const, value }), (error: unknown) => ({ ok: false as const, error }));
      let reportCancelPid!: (pid: number) => void;
      const cancelReady = new Promise<number>((resolveReady) => { reportCancelPid = resolveReady; });
      const cancellationDatabase = {
        transaction: (work: (tx: unknown) => Promise<unknown>) => database.transaction(async (tx) => {
          await tx.execute(sql`SET LOCAL statement_timeout = '8s'`);
          const result = await tx.execute(sql`SELECT pg_backend_pid() AS pid`);
          reportCancelPid(Number(result.rows[0].pid));
          return work(tx);
        }),
      };
      const cancellingService = createService(cancellationDatabase, storage as Parameters<typeof createService>[1], undefined, () => NOW);
      cancelling = cancellingService.cancel(1, actorId, "Concurrent cancellation")
        .then((value) => ({ ok: true as const, value }), (error: unknown) => ({ ok: false as const, error }));
      const [editingPid, cancellationPid] = await Promise.all([ready, cancelReady]);
      await Promise.all([waitUntilBlocked(editingPid), waitUntilBlocked(cancellationPid)]);
      releaseClose();
      expect(await closing).toMatchObject({ ok: true, value: { status: "closed", closedBy: actorId, closedAt: NOW } });
      expect(await editing).toMatchObject({ ok: false, error: { details: { code: "SHIPMENT_COST_TERMINAL" } } });
      expect(await cancelling).toMatchObject({ ok: false, error: { statusCode: 400, message: "Cannot transition from 'closed' to 'cancelled'" } });
      expect((await readCost()).actualCents).toBe(500);
      expect(await database.select().from(schema.landedCostSnapshots)).toMatchObject([
        { inboundShipmentLineId: 11, totalLandedCostCents: 500, finalizedAt: NOW },
      ]);
      expect(await database.select().from(schema.inboundShipmentStatusHistory)).toMatchObject([
        { inboundShipmentId: 1, fromStatus: "costing", toStatus: "closed", changedBy: actorId, changedAt: NOW },
      ]);
    } finally {
      releaseClose();
      await Promise.allSettled([closing, ...(editing ? [editing] : []), ...(cancelling ? [cancelling] : [])]);
    }
  });

  it("rolls back close snapshots, allocation and header when status history fails", async () => {
    let provisionalLookups = 0;
    const closingStorage = {
      ...storage,
      async getProvisionalLotsByShipment() { provisionalLookups++; return []; },
    };
    const closingService = createService(database, closingStorage as Parameters<typeof createService>[1], undefined, () => NOW);
    const before = await state();
    await pool.query("ALTER TABLE procurement.inbound_shipment_status_history ADD CONSTRAINT shipment_cost_test_reject_close CHECK(to_status <> 'closed')");
    try {
      await expect(closingService.close(1, actorId, "Fixture history failure")).rejects.toThrow();
      expect(await state()).toEqual(before);
      expect(provisionalLookups).toBe(0);
    } finally {
      await pool.query("ALTER TABLE procurement.inbound_shipment_status_history DROP CONSTRAINT shipment_cost_test_reject_close");
    }
  });


  it("rolls back a signed economic change rejected by the existing allocation owner", async () => {
    const before = await state();
    await expect(execute(await patch({ actualCents: -55 }))).rejects.toMatchObject({
      statusCode: 409, details: { code: "INVALID_LANDED_COST_AMOUNT" },
    });
    expect(await state()).toEqual(before);
  });

  it("rolls back a safe individual amount whose shipment aggregate exceeds the safe range", async () => {
    const before = await state();
    await expect(execute({
      operation: "create", resourceId: 1,
      body: { costType: "insurance", actualCents: Number.MAX_SAFE_INTEGER },
    })).rejects.toMatchObject({ statusCode: 409, details: { code: "SHIPMENT_COST_TOTAL_OVERFLOW" } });
    expect(await state()).toEqual(before);
  });

  it("records and replays a vendor FK rejection without committing a cost or audit", async () => {
    const before = await state();
    const command: ShipmentCostCommand = {
      operation: "create", resourceId: 1,
      body: { costType: "insurance", actualCents: 125, vendorId: 999 },
    };
    const request = descriptor("missing-vendor", command);
    const commands = commandFactory(service, repositoryFactory(database), () => NOW);
    const rejected = await commands.execute(command, actorId, request);
    expect(rejected).toMatchObject({
      httpStatus: 422, terminalState: "rejected", replayed: false,
      body: { code: "SHIPMENT_COST_REFERENCE_INVALID" },
    });
    expect(await state()).toEqual(before);
    expect(await commands.execute(command, delegateId, request)).toMatchObject({
      commandId: rejected.commandId, httpStatus: 422, terminalState: "rejected", replayed: true,
      body: rejected.body,
    });
    const result = await pool.query("SELECT status,last_error_code,response_body FROM public.financial_command_results WHERE id=$1", [rejected.commandId]);
    expect(result.rows).toEqual([{
      status: "rejected", last_error_code: "SHIPMENT_COST_REFERENCE_INVALID", response_body: rejected.body,
    }]);
    expect(await state()).toEqual(before);
  });

  it("replays the committed create across delegated actors without a second cost or audit", async () => {
    const command: ShipmentCostCommand = { operation: "create", resourceId: 1, body: { costType: "insurance", actualCents: 125 } };
    const request = descriptor("delegated-replay", command);
    const commands = commandFactory(service, repositoryFactory(database), () => NOW);
    const first = await commands.execute(command, actorId, request);
    const replay = await commands.execute(command, delegateId, request);
    expect(first).toMatchObject({ httpStatus: 201, terminalState: "succeeded", replayed: false });
    expect(replay).toMatchObject({ httpStatus: 201, replayed: true, body: JSON.parse(JSON.stringify(first.body)) });
    expect((await pool.query("SELECT * FROM procurement.inbound_freight_costs")).rows).toHaveLength(2);
    expect((await pool.query("SELECT actor FROM public.audit_events WHERE actor = ANY($1::text[])", [[actorId, delegateId]])).rows).toEqual([{ actor: actorId }]);
    const changed = { ...command, body: { costType: "insurance", actualCents: 126 } };
    await expect(commands.execute(changed, delegateId, { ...request, requestHash: descriptor("delegated-replay", changed).requestHash })).rejects.toMatchObject({ code: "FINANCIAL_COMMAND_IDEMPOTENCY_KEY_REUSED" });
  });
});
