-- NOOP. The original intent of this migration was to copy an
-- enable_order_combining row from warehouse.app_settings to
-- warehouse.echelon_settings. In practice, warehouse.app_settings is a
-- different shape entirely (config flags table, not key/value), so there
-- is no source row to migrate. The value has always lived directly in
-- warehouse.echelon_settings (or was a code default).
--
-- Migration 0082_order_combining_per_warehouse.sql then consolidates the
-- value from warehouse.echelon_settings into the DEFAULT row of
-- inventory.warehouse_settings.
--
-- Kept as a placeholder so subsequent migration numbers don't reshuffle.
SELECT 1;
