import { SQL } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { getTableConfig, PgDialect, type PgTable } from "drizzle-orm/pg-core";
import { beforeAll, beforeEach, afterAll, describe, expect, it, vi } from "vitest";
import * as schema from "@shared/schema";
import { createInventoryCutoverTestDatabase, type InventoryCutoverTestDatabase } from "../../../inventory/__tests__/fixtures/inventory-cutover-database";
import { resolveOrderLineCatalogIdentity } from "../../order-line-catalog-identity.service";
import { createOmsService } from "../../oms.service";
import { normalizeShopifyLineItems } from "../../shopify-line-item-normalizer";
import { buildWmsLineItemFromOmsLine } from "../../wms-sync.service";
import { createHistoricalOrderLineIdentityRepairService } from "../../application/historical-order-line-identity-repair.service";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const describeDatabase = databaseUrl && disposable ? describe : describe.skip;
const tables = [schema.productVariants, schema.channelListings, schema.omsOrders, schema.omsOrderLines,
  schema.omsOrderEvents, schema.omsOrderLineAuthorityEvents, schema.webhookInbox,
  schema.wmsOrders, schema.wmsOrderItems, schema.omsHistoricalLineIdentityRepairCommands,
  schema.productLocations, schema.warehouseLocations];
const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;

// Query/transaction fixture derived from current columns, not a production migration or trigger test.
function fixtureTable(table: PgTable): string {
  const config = getTableConfig(table);
  const columns = config.columns.map(column => {
    let definition = `${quote(column.name)} ${column.getSQLType()}`;
    if (column.primary) return `${definition} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    if (column.default !== undefined) {
      let literal: string;
      if (column.default instanceof SQL) {
        const compiled = new PgDialect().sqlToQuery(column.default);
        if (compiled.params.length) throw new Error("Fixture SQL default must have no parameters");
        literal = compiled.sql;
      } else if (typeof column.default === "string") literal = `'${column.default.replaceAll("'", "''")}'`;
      else if (["number", "boolean"].includes(typeof column.default)) literal = String(column.default);
      else throw new Error("Unsupported fixture default");
      definition += ` DEFAULT ${literal}`;
    }
    return definition + (column.notNull ? " NOT NULL" : "");
  });
  return `CREATE TABLE ${quote(config.schema!)}.${quote(config.name)} (${columns.join(",")});`;
}
const namespaces = [...new Set(tables.map(table => getTableConfig(table).schema!))];
const fixtureSql = namespaces.map(name => `CREATE SCHEMA ${quote(name)};`).join("\n")
  + tables.map(fixtureTable).join("\n") + `
    CREATE UNIQUE INDEX oms_channel_order_unique ON oms.oms_orders(channel_id,external_order_id);
    CREATE UNIQUE INDEX oms_authority_event_unique ON oms.oms_order_line_authority_events(event_key);
    CREATE UNIQUE INDEX oms_hist_identity_command_unique
      ON oms.historical_order_line_identity_repair_commands(idempotency_key);
  `;

describeDatabase.sequential("order line identity PostgreSQL and WMS handoff", () => {
  let database: InventoryCutoverTestDatabase;
  let orm: ReturnType<typeof drizzle<typeof schema>>;
  beforeAll(async () => {
    database = await createInventoryCutoverTestDatabase(databaseUrl, disposable, fixtureSql);
    orm = drizzle(database.pool, { schema });
  });
  beforeEach(async () => {
    await database.pool.query(`TRUNCATE catalog.product_variants, channels.channel_listings,
      oms.oms_orders, oms.oms_order_lines, oms.oms_order_events, oms.oms_order_line_authority_events,
      oms.webhook_inbox, wms.orders, wms.order_items,
      oms.historical_order_line_identity_repair_commands RESTART IDENTITY`);
    await database.pool.query(`INSERT INTO catalog.product_variants(id,product_id,name,sku,compare_at_price_cents)
      VALUES (11,1,'Example pack','EXAMPLE-P5',2500), (12,1,'Example case','EXAMPLE-C25',10000);
      INSERT INTO channels.channel_listings(channel_id,product_variant_id,external_product_id,external_variant_id)
      VALUES (2,11,'1000','1001'),(3,12,'1000','1001');`);
  });
  afterAll(async () => { await database?.close(); });
  const identityInput = { channelId: 2, externalVariantId: "1001", externalProductId: "1000", sku: null };
  const source = { id: 21, product_id: 1000, variant_id: 1001, sku: null,
    title: "Example item", quantity: 2, price: "10.00", requires_shipping: true };
  const orderData = () => ({ orderedAt: new Date("2026-09-01T12:00:00Z"), sourceTopic: "orders/paid",
    sourceEventId: "fixture-paid-1", financialStatus: "paid", lineItems: normalizeShopifyLineItems([source], []) });

  it("scopes the same external ID to its channel; an unmapped channel remains unresolved", async () => {
    await database.pool.query("UPDATE catalog.product_variants SET shopify_variant_id='1001' WHERE id=11");
    expect((await resolveOrderLineCatalogIdentity(orm, identityInput))?.id).toBe(11);
    expect((await resolveOrderLineCatalogIdentity(orm, { ...identityInput, channelId: 3 }))?.id).toBe(12);
    expect(await resolveOrderLineCatalogIdentity(orm, { ...identityInput, channelId: 4 })).toBeNull();
  });
  it("retains SKU-only behavior and rejects SKU/variant conflicts", async () => {
    expect((await resolveOrderLineCatalogIdentity(orm, { channelId: 2, sku: "example-p5" }))?.id).toBe(11);
    await expect(resolveOrderLineCatalogIdentity(orm, { ...identityInput, sku: "EXAMPLE-C25" }))
      .rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_CONFLICT" });
  });
  it("does not treat an inactive predecessor as an ambiguous active SKU match", async () => {
    await database.pool.query(`INSERT INTO catalog.product_variants(id,product_id,name,sku,is_active)
      VALUES (13,1,'Archived pack','EXAMPLE-P5',false)`);
    expect((await resolveOrderLineCatalogIdentity(orm, { channelId: 2, sku: "EXAMPLE-P5" }))?.id).toBe(11);
    await expect(resolveOrderLineCatalogIdentity(orm, { channelId: 2, sku: "EXAMPLE-P5", previousVariantId: 13 }))
      .rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_CHANGE_REQUIRES_REVIEW" });
  });
  it("detects duplicate channel mappings instead of taking the first row", async () => {
    await database.pool.query(`INSERT INTO channels.channel_listings(channel_id,product_variant_id,external_product_id,external_variant_id)
      VALUES (2,12,'1000','1001')`);
    await expect(resolveOrderLineCatalogIdentity(orm, identityInput)).rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_AMBIGUOUS" });
  });
  it("holds the selected channel mapping against concurrent replacement until the OMS transaction ends", async () => {
    const competitor = await database.pool.connect();
    try {
      await competitor.query("SET lock_timeout='100ms'");
      await orm.transaction(async tx => {
        expect((await resolveOrderLineCatalogIdentity(tx, identityInput))?.id).toBe(11);
        await expect(competitor.query("UPDATE channels.channel_listings SET product_variant_id=12 WHERE channel_id=2"))
          .rejects.toMatchObject({ code: "55P03" });
      });
      await competitor.query("UPDATE channels.channel_listings SET product_variant_id=12 WHERE channel_id=2");
    } finally {
      await competitor.query("RESET lock_timeout");
      competitor.release();
    }
  });
  it("normalizes, ingests, audits, replays and materializes a missing-SKU line without changing source SKU or quantities", async () => {
    const service = createOmsService(orm);
    const order = await service.ingestOrder(2, "fixture-order", orderData());
    await service.ingestOrder(2, "fixture-order", orderData());
    const [line] = await orm.select().from(schema.omsOrderLines);
    expect(line).toMatchObject({ productVariantId: 11, sku: null, quantity: 2, authorityFulfillableQuantity: 2 });
    const wms = await buildWmsLineItemFromOmsLine(orm, line, 2, 90);
    expect(wms).toMatchObject({ productId: 11, sku: "EXAMPLE-P5", quantity: 2, pickedQuantity: 0,
      fulfilledQuantity: 0, requiresShipping: 1, status: "pending", omsOrderLineId: line.id });
    const events = (await database.pool.query(`SELECT details FROM oms.oms_order_events
      WHERE event_type='line_catalog_identity_resolved'`)).rows;
    expect(events).toHaveLength(1);
    expect(events[0].details).toMatchObject({ orderLineId: line.id, previousVariantId: null,
      productVariantId: 11, sourceSku: null, catalogSku: "EXAMPLE-P5", matchedBy: "channel_variant_id" });
    expect(order.id).toBe(line.orderId);
    expect(source.sku).toBeNull();
  });
  it("rolls back the order and its lines when identity evidence conflicts", async () => {
    const data = orderData();
    data.lineItems[0].sku = "EXAMPLE-C25";
    await expect(createOmsService(orm).ingestOrder(2, "fixture-conflict", data))
      .rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_CONFLICT" });
    expect((await orm.select().from(schema.omsOrders))).toHaveLength(0);
    expect((await orm.select().from(schema.omsOrderLines))).toHaveLength(0);
    expect((await orm.select().from(schema.omsOrderEvents))).toHaveLength(0);
  });
  it("resolves a previously unidentified line when a later replay supplies its channel variant", async () => {
    const service = createOmsService(orm);
    const unidentified = orderData();
    unidentified.lineItems[0].externalVariantId = null;
    await service.ingestOrder(2, "fixture-later-identity", unidentified);
    expect((await orm.select().from(schema.omsOrderLines))[0].productVariantId).toBeNull();

    await service.ingestOrder(2, "fixture-later-identity", orderData());
    await service.ingestOrder(2, "fixture-later-identity", orderData());
    const lines = await orm.select().from(schema.omsOrderLines);
    expect(lines).toHaveLength(1);
    expect(lines[0]).toMatchObject({ productVariantId: 11, sku: null, quantity: 2 });
    expect((await buildWmsLineItemFromOmsLine(orm, lines[0], 2, 90)).sku).toBe("EXAMPLE-P5");
    expect((await database.pool.query(`SELECT id FROM oms.oms_order_events WHERE event_type='line_catalog_identity_resolved'`)).rows).toHaveLength(1);
  });
  it("resolves a newly added missing-SKU line during duplicate ingestion", async () => {
    const service = createOmsService(orm);
    await service.ingestOrder(2, "fixture-added-line", orderData());
    const updated = orderData();
    updated.lineItems.push({ ...updated.lineItems[0], externalLineItemId: "22" });
    await service.ingestOrder(2, "fixture-added-line", updated);
    await service.ingestOrder(2, "fixture-added-line", updated);
    const lines = await orm.select().from(schema.omsOrderLines);
    expect(lines).toHaveLength(2);
    expect(lines.find(line => line.externalLineItemId === "22"))
      .toMatchObject({ productVariantId: 11, sku: null, quantity: 2 });
    expect((await database.pool.query(`SELECT id FROM oms.oms_order_events WHERE event_type='line_catalog_identity_resolved'`)).rows).toHaveLength(2);
  });
  it("serializes concurrent replays without duplicate lines or identity audit events", async () => {
    const service = createOmsService(orm);
    await Promise.all([service.ingestOrder(2, "fixture-concurrent", orderData()), service.ingestOrder(2, "fixture-concurrent", orderData())]);
    expect(await orm.select().from(schema.omsOrders)).toHaveLength(1);
    expect(await orm.select().from(schema.omsOrderLines)).toHaveLength(1);
    expect((await database.pool.query(`SELECT id FROM oms.oms_order_events WHERE event_type='line_catalog_identity_resolved'`)).rows).toHaveLength(1);
  });
  it("uses the catalog SKU for channel aliases without rewriting the OMS source SKU", async () => {
    const data = orderData();
    data.lineItems[0].sku = "CHANNEL-ALIAS";
    await createOmsService(orm).ingestOrder(2, "fixture-alias", data);
    const [line] = await orm.select().from(schema.omsOrderLines);
    expect(line.sku).toBe("CHANNEL-ALIAS");
    expect((await buildWmsLineItemFromOmsLine(orm, line, 2, 90)).sku).toBe("EXAMPLE-P5");
  });
  it("keeps nonshipping items nonshipping when their channel variant resolves", async () => {
    const data = orderData();
    data.lineItems[0].requiresShipping = false;
    await createOmsService(orm).ingestOrder(2, "fixture-nonshipping", data);
    const [line] = await orm.select().from(schema.omsOrderLines);
    expect(await buildWmsLineItemFromOmsLine(orm, line, 2, 90))
      .toMatchObject({ requiresShipping: 0, status: "completed", sku: "EXAMPLE-P5" });
  });
  it("does not silently substitute a source SKU when a stored catalog identity is missing", async () => {
    await createOmsService(orm).ingestOrder(2, "fixture-missing-variant", orderData());
    const [line] = await orm.select().from(schema.omsOrderLines);
    await expect(buildWmsLineItemFromOmsLine(orm, { ...line, productVariantId: 999 }, 2, 90))
      .rejects.toMatchObject({ code: "WMS_CATALOG_VARIANT_MISSING", context: { variantId: 999 } });
  });
  it("does not rebind an existing line if channel mappings change before a later replay", async () => {
    const service = createOmsService(orm);
    await service.ingestOrder(2, "fixture-rebind", orderData());
    await database.pool.query("UPDATE channels.channel_listings SET product_variant_id=12 WHERE channel_id=2");
    await expect(service.ingestOrder(2, "fixture-rebind", orderData()))
      .rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_CHANGE_REQUIRES_REVIEW" });
    expect((await orm.select().from(schema.omsOrderLines))[0]).toMatchObject({ productVariantId: 11, sku: null, quantity: 2 });
    expect((await database.pool.query(`SELECT id FROM oms.oms_order_events WHERE event_type='line_catalog_identity_resolved'`)).rows).toHaveLength(1);
  });
  it("rolls back identity assignment and order creation if the audit write fails", async () => {
    await database.pool.query(`ALTER TABLE oms.oms_order_events ADD CONSTRAINT fixture_audit_failure
      CHECK (event_type <> 'line_catalog_identity_resolved')`);
    try {
      await expect(createOmsService(orm).ingestOrder(2, "fixture-audit-failure", orderData())).rejects.toThrow();
      expect(await orm.select().from(schema.omsOrders)).toHaveLength(0);
      expect(await orm.select().from(schema.omsOrderLines)).toHaveLength(0);
    } finally {
      await database.pool.query("ALTER TABLE oms.oms_order_events DROP CONSTRAINT fixture_audit_failure");
    }
  });

  it("repairs historical OMS and WMS identity atomically, preserves source SKU, and claims once", async () => {
    await database.pool.query(`
      INSERT INTO oms.oms_orders(id,channel_id,external_order_id,status,financial_status,fulfillment_status,ordered_at)
      VALUES (71,2,'historical-order-71','confirmed','paid','unfulfilled','2026-09-01T12:00:00Z');
      INSERT INTO oms.webhook_inbox(id,provider,topic,event_id,idempotency_key,status,payload)
      VALUES (81,'shopify','orders/updated','event-81','shopify:orders/updated:event-81','succeeded',
        '{"line_items":[{"id":9001,"product_id":1000,"variant_id":1001,"sku":null,"requires_shipping":true,"gift_card":false,"product_exists":true}]}'::jsonb);
      INSERT INTO oms.oms_order_lines(id,order_id,external_line_item_id,external_product_id,sku,quantity,
        requires_shipping,gift_card,product_exists,authority_source_inbox_id)
      VALUES (91,71,'9001','1000',NULL,2,true,false,true,81);
      INSERT INTO wms.orders(id,oms_fulfillment_order_id,source,order_number,customer_name,warehouse_status)
      VALUES (101,'71','oms','#71','Historical Customer','ready');
      INSERT INTO wms.order_items(id,order_id,oms_order_line_id,product_id,sku,name,quantity,status,picked_quantity,fulfilled_quantity)
      VALUES (111,101,91,NULL,'UNKNOWN','Example pack',2,'pending',0,0);
    `);
    const reconcileOrderDemand = vi.fn(async () => ({
      reconciled: true,
      release: { released: 0, failed: [] },
      reservation: { orderId: 101, reserved: 1, promised: 0, failed: [], totalBaseUnits: 10, totalPromisedBaseUnits: 0 },
    }));
    const service = createHistoricalOrderLineIdentityRepairService(orm, { reconcileOrderDemand },
      () => new Date("2026-09-11T15:00:00Z"));
    const preview = await service.preview(71);
    expect(preview).toMatchObject({ omsOrderId: 71, safeCount: 1, reviewCount: 0,
      lines: [{ omsOrderLineId: 91, externalVariantId: "1001", resolvedVariantId: 11,
        resolvedCatalogSku: "EXAMPLE-P5", wmsOrderItemId: 111 }] });

    const request = { expectedPreviewHash: preview.previewHash,
      idempotencyKey: "ba01e537-6af2-46f1-bc92-9de0105aff19", reason: "Reviewed fixture repair" };
    const result = await service.apply(71, request, { operator: "user:7", userId: "7" });
    expect(result).toMatchObject({ status: "succeeded", idempotentReplay: false,
      repair: { omsOrderId: 71, wmsOrderId: 101, repairedLines: [{ productVariantId: 11, catalogSku: "EXAMPLE-P5" }] } });
    expect((await database.pool.query("SELECT product_variant_id, sku FROM oms.oms_order_lines WHERE id=91")).rows[0])
      .toEqual({ product_variant_id: 11, sku: null });
    expect((await database.pool.query("SELECT product_id, sku FROM wms.order_items WHERE id=111")).rows[0])
      .toEqual({ product_id: 11, sku: "EXAMPLE-P5" });
    expect((await database.pool.query("SELECT status, operator FROM oms.historical_order_line_identity_repair_commands")).rows)
      .toEqual([{ status: "succeeded", operator: "user:7" }]);
    expect((await database.pool.query(`SELECT event_type FROM oms.oms_order_events
      WHERE order_id=71 ORDER BY id`)).rows.map((row) => row.event_type)).toEqual([
      "line_catalog_identity_resolved",
      "historical_line_identity_repair_prepared",
      "historical_line_identity_claim_reconciled",
    ]);
    expect(reconcileOrderDemand).toHaveBeenCalledTimes(1);

    const replay = await service.apply(71, request, { operator: "user:7", userId: "7" });
    expect(replay.idempotentReplay).toBe(true);
    expect(reconcileOrderDemand).toHaveBeenCalledTimes(1);
  });

  it("refuses a historical repair after WMS physical progress and writes nothing", async () => {
    await database.pool.query(`
      INSERT INTO oms.oms_orders(id,channel_id,external_order_id,status,financial_status,fulfillment_status,ordered_at)
      VALUES (72,2,'historical-order-72','confirmed','paid','unfulfilled','2026-09-01T12:00:00Z');
      INSERT INTO oms.webhook_inbox(id,provider,topic,event_id,idempotency_key,status,payload)
      VALUES (82,'shopify','orders/updated','event-82','shopify:orders/updated:event-82','succeeded',
        '{"line_items":[{"id":9002,"product_id":1000,"variant_id":1001,"sku":null,"requires_shipping":true}]}'::jsonb);
      INSERT INTO oms.oms_order_lines(id,order_id,external_line_item_id,external_product_id,sku,quantity,
        requires_shipping,gift_card,product_exists,authority_source_inbox_id)
      VALUES (92,72,'9002','1000',NULL,2,true,false,true,82);
      INSERT INTO wms.orders(id,oms_fulfillment_order_id,source,order_number,customer_name,warehouse_status)
      VALUES (102,'72','oms','#72','Historical Customer','ready');
      INSERT INTO wms.order_items(id,order_id,oms_order_line_id,product_id,sku,name,quantity,status,picked_quantity,fulfilled_quantity)
      VALUES (112,102,92,NULL,'UNKNOWN','Example pack',2,'pending',1,0);
    `);
    const reconcileOrderDemand = vi.fn();
    const service = createHistoricalOrderLineIdentityRepairService(orm, { reconcileOrderDemand });
    const preview = await service.preview(72);
    expect(preview).toMatchObject({ safeCount: 0, reviewCount: 1,
      lines: [{ code: "WMS_PHYSICAL_PROGRESS_PRESENT", pickedQuantity: 1 }] });
    await expect(service.apply(72, {
      expectedPreviewHash: preview.previewHash,
      idempotencyKey: "f1fb83fb-8334-4545-ae62-461a2d931a5a",
      reason: "Must not rewrite picked work",
    }, { operator: "user:7" })).rejects.toMatchObject({ code: "REPAIR_REVIEW_REQUIRED" });
    expect((await database.pool.query("SELECT product_variant_id FROM oms.oms_order_lines WHERE id=92")).rows[0].product_variant_id)
      .toBeNull();
    expect((await database.pool.query("SELECT count(*)::int AS count FROM oms.historical_order_line_identity_repair_commands")).rows[0].count)
      .toBe(0);
    expect(reconcileOrderDemand).not.toHaveBeenCalled();
  });
});
