import { SQL } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { getTableConfig, PgDialect, type PgTable } from "drizzle-orm/pg-core";
import { beforeAll, beforeEach, afterAll, describe, expect, it } from "vitest";
import * as schema from "@shared/schema";
import { createInventoryCutoverTestDatabase, type InventoryCutoverTestDatabase } from "../../../inventory/__tests__/fixtures/inventory-cutover-database";
import { resolveOrderLineCatalogIdentity } from "../../order-line-catalog-identity.service";
import { createOmsService } from "../../oms.service";
import { normalizeShopifyLineItems } from "../../shopify-line-item-normalizer";
import { buildWmsLineItemFromOmsLine } from "../../wms-sync.service";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const describeDatabase = databaseUrl && disposable ? describe : describe.skip;
const tables = [schema.productVariants, schema.channelListings, schema.omsOrders, schema.omsOrderLines,
  schema.omsOrderEvents, schema.omsOrderLineAuthorityEvents, schema.productLocations, schema.warehouseLocations];
const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;

// Query/transaction fixture derived from current columns, not a production migration or trigger test.
function fixtureTable(table: PgTable): string {
  const config = getTableConfig(table);
  const columns = config.columns.map(column => {
    let definition = `${quote(column.name)} ${column.getSQLType()}`;
    if (column.primary) return `${definition} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    if (column.default !== undefined) {
      let literal: string;
      if (column.default instanceof SQL) {
        const compiled = new PgDialect().sqlToQuery(column.default);
        if (compiled.params.length) throw new Error("Fixture SQL default must have no parameters");
        literal = compiled.sql;
      } else if (typeof column.default === "string") literal = `'${column.default.replaceAll("'", "''")}'`;
      else if (["number", "boolean"].includes(typeof column.default)) literal = String(column.default);
      else throw new Error("Unsupported fixture default");
      definition += ` DEFAULT ${literal}`;
    }
    return definition + (column.notNull ? " NOT NULL" : "");
  });
  return `CREATE TABLE ${quote(config.schema!)}.${quote(config.name)} (${columns.join(",")});`;
}
const namespaces = [...new Set(tables.map(table => getTableConfig(table).schema!))];
const fixtureSql = namespaces.map(name => `CREATE SCHEMA ${quote(name)};`).join("\n")
  + tables.map(fixtureTable).join("\n") + `
    CREATE UNIQUE INDEX oms_channel_order_unique ON oms.oms_orders(channel_id,external_order_id);
    CREATE UNIQUE INDEX oms_authority_event_unique ON oms.oms_order_line_authority_events(event_key);
  `;

describeDatabase.sequential("order line identity PostgreSQL and WMS handoff", () => {
  let database: InventoryCutoverTestDatabase;
  let orm: ReturnType<typeof drizzle<typeof schema>>;
  beforeAll(async () => {
    database = await createInventoryCutoverTestDatabase(databaseUrl, disposable, fixtureSql);
    orm = drizzle(database.pool, { schema });
  });
  beforeEach(async () => {
    await database.pool.query(`TRUNCATE catalog.product_variants, channels.channel_listings,
      oms.oms_orders, oms.oms_order_lines, oms.oms_order_events, oms.oms_order_line_authority_events RESTART IDENTITY`);
    await database.pool.query(`INSERT INTO catalog.product_variants(id,product_id,name,sku,compare_at_price_cents)
      VALUES (11,1,'Example pack','EXAMPLE-P5',2500), (12,1,'Example case','EXAMPLE-C25',10000);
      INSERT INTO channels.channel_listings(channel_id,product_variant_id,external_product_id,external_variant_id)
      VALUES (2,11,'1000','1001'),(3,12,'1000','1001');`);
  });
  afterAll(async () => { await database?.close(); });
  const identityInput = { channelId: 2, externalVariantId: "1001", externalProductId: "1000", sku: null };
  const source = { id: 21, product_id: 1000, variant_id: 1001, sku: null,
    title: "Example item", quantity: 2, price: "10.00", requires_shipping: true };
  const orderData = () => ({ orderedAt: new Date("2026-09-01T12:00:00Z"), sourceTopic: "orders/paid",
    sourceEventId: "fixture-paid-1", financialStatus: "paid", lineItems: normalizeShopifyLineItems([source], []) });

  it("scopes the same external ID to its channel; an unmapped channel remains unresolved", async () => {
    await database.pool.query("UPDATE catalog.product_variants SET shopify_variant_id='1001' WHERE id=11");
    expect((await resolveOrderLineCatalogIdentity(orm, identityInput))?.id).toBe(11);
    expect((await resolveOrderLineCatalogIdentity(orm, { ...identityInput, channelId: 3 }))?.id).toBe(12);
    expect(await resolveOrderLineCatalogIdentity(orm, { ...identityInput, channelId: 4 })).toBeNull();
  });
  it("retains SKU-only behavior and rejects SKU/variant conflicts", async () => {
    expect((await resolveOrderLineCatalogIdentity(orm, { channelId: 2, sku: "example-p5" }))?.id).toBe(11);
    await expect(resolveOrderLineCatalogIdentity(orm, { ...identityInput, sku: "EXAMPLE-C25" }))
      .rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_CONFLICT" });
  });
  it("does not treat an inactive predecessor as an ambiguous active SKU match", async () => {
    await database.pool.query(`INSERT INTO catalog.product_variants(id,product_id,name,sku,is_active)
      VALUES (13,1,'Archived pack','EXAMPLE-P5',false)`);
    expect((await resolveOrderLineCatalogIdentity(orm, { channelId: 2, sku: "EXAMPLE-P5" }))?.id).toBe(11);
    await expect(resolveOrderLineCatalogIdentity(orm, { channelId: 2, sku: "EXAMPLE-P5", previousVariantId: 13 }))
      .rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_CHANGE_REQUIRES_REVIEW" });
  });
  it("detects duplicate channel mappings instead of taking the first row", async () => {
    await database.pool.query(`INSERT INTO channels.channel_listings(channel_id,product_variant_id,external_product_id,external_variant_id)
      VALUES (2,12,'1000','1001')`);
    await expect(resolveOrderLineCatalogIdentity(orm, identityInput)).rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_AMBIGUOUS" });
  });
  it("holds the selected channel mapping against concurrent replacement until the OMS transaction ends", async () => {
    const competitor = await database.pool.connect();
    try {
      await competitor.query("SET lock_timeout='100ms'");
      await orm.transaction(async tx => {
        expect((await resolveOrderLineCatalogIdentity(tx, identityInput))?.id).toBe(11);
        await expect(competitor.query("UPDATE channels.channel_listings SET product_variant_id=12 WHERE channel_id=2"))
          .rejects.toMatchObject({ code: "55P03" });
      });
      await competitor.query("UPDATE channels.channel_listings SET product_variant_id=12 WHERE channel_id=2");
    } finally {
      await competitor.query("RESET lock_timeout");
      competitor.release();
    }
  });
  it("normalizes, ingests, audits, replays and materializes a missing-SKU line without changing source SKU or quantities", async () => {
    const service = createOmsService(orm);
    const order = await service.ingestOrder(2, "fixture-order", orderData());
    await service.ingestOrder(2, "fixture-order", orderData());
    const [line] = await orm.select().from(schema.omsOrderLines);
    expect(line).toMatchObject({ productVariantId: 11, sku: null, quantity: 2, authorityFulfillableQuantity: 2 });
    const wms = await buildWmsLineItemFromOmsLine(orm, line, 2, 90);
    expect(wms).toMatchObject({ productId: 11, sku: "EXAMPLE-P5", quantity: 2, pickedQuantity: 0,
      fulfilledQuantity: 0, requiresShipping: 1, status: "pending", omsOrderLineId: line.id });
    const events = (await database.pool.query(`SELECT details FROM oms.oms_order_events
      WHERE event_type='line_catalog_identity_resolved'`)).rows;
    expect(events).toHaveLength(1);
    expect(events[0].details).toMatchObject({ orderLineId: line.id, previousVariantId: null,
      productVariantId: 11, sourceSku: null, catalogSku: "EXAMPLE-P5", matchedBy: "channel_variant_id" });
    expect(order.id).toBe(line.orderId);
    expect(source.sku).toBeNull();
  });
  it("rolls back the order and its lines when identity evidence conflicts", async () => {
    const data = orderData();
    data.lineItems[0].sku = "EXAMPLE-C25";
    await expect(createOmsService(orm).ingestOrder(2, "fixture-conflict", data))
      .rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_CONFLICT" });
    expect((await orm.select().from(schema.omsOrders))).toHaveLength(0);
    expect((await orm.select().from(schema.omsOrderLines))).toHaveLength(0);
    expect((await orm.select().from(schema.omsOrderEvents))).toHaveLength(0);
  });
  it("resolves a previously unidentified line when a later replay supplies its channel variant", async () => {
    const service = createOmsService(orm);
    const unidentified = orderData();
    unidentified.lineItems[0].externalVariantId = null;
    await service.ingestOrder(2, "fixture-later-identity", unidentified);
    expect((await orm.select().from(schema.omsOrderLines))[0].productVariantId).toBeNull();

    await service.ingestOrder(2, "fixture-later-identity", orderData());
    await service.ingestOrder(2, "fixture-later-identity", orderData());
    const lines = await orm.select().from(schema.omsOrderLines);
    expect(lines).toHaveLength(1);
    expect(lines[0]).toMatchObject({ productVariantId: 11, sku: null, quantity: 2 });
    expect((await buildWmsLineItemFromOmsLine(orm, lines[0], 2, 90)).sku).toBe("EXAMPLE-P5");
    expect((await database.pool.query(`SELECT id FROM oms.oms_order_events WHERE event_type='line_catalog_identity_resolved'`)).rows).toHaveLength(1);
  });
  it("resolves a newly added missing-SKU line during duplicate ingestion", async () => {
    const service = createOmsService(orm);
    await service.ingestOrder(2, "fixture-added-line", orderData());
    const updated = orderData();
    updated.lineItems.push({ ...updated.lineItems[0], externalLineItemId: "22" });
    await service.ingestOrder(2, "fixture-added-line", updated);
    await service.ingestOrder(2, "fixture-added-line", updated);
    const lines = await orm.select().from(schema.omsOrderLines);
    expect(lines).toHaveLength(2);
    expect(lines.find(line => line.externalLineItemId === "22"))
      .toMatchObject({ productVariantId: 11, sku: null, quantity: 2 });
    expect((await database.pool.query(`SELECT id FROM oms.oms_order_events WHERE event_type='line_catalog_identity_resolved'`)).rows).toHaveLength(2);
  });
  it("serializes concurrent replays without duplicate lines or identity audit events", async () => {
    const service = createOmsService(orm);
    await Promise.all([service.ingestOrder(2, "fixture-concurrent", orderData()), service.ingestOrder(2, "fixture-concurrent", orderData())]);
    expect(await orm.select().from(schema.omsOrders)).toHaveLength(1);
    expect(await orm.select().from(schema.omsOrderLines)).toHaveLength(1);
    expect((await database.pool.query(`SELECT id FROM oms.oms_order_events WHERE event_type='line_catalog_identity_resolved'`)).rows).toHaveLength(1);
  });
  it("uses the catalog SKU for channel aliases without rewriting the OMS source SKU", async () => {
    const data = orderData();
    data.lineItems[0].sku = "CHANNEL-ALIAS";
    await createOmsService(orm).ingestOrder(2, "fixture-alias", data);
    const [line] = await orm.select().from(schema.omsOrderLines);
    expect(line.sku).toBe("CHANNEL-ALIAS");
    expect((await buildWmsLineItemFromOmsLine(orm, line, 2, 90)).sku).toBe("EXAMPLE-P5");
  });
  it("keeps nonshipping items nonshipping when their channel variant resolves", async () => {
    const data = orderData();
    data.lineItems[0].requiresShipping = false;
    await createOmsService(orm).ingestOrder(2, "fixture-nonshipping", data);
    const [line] = await orm.select().from(schema.omsOrderLines);
    expect(await buildWmsLineItemFromOmsLine(orm, line, 2, 90))
      .toMatchObject({ requiresShipping: 0, status: "completed", sku: "EXAMPLE-P5" });
  });
  it("does not silently substitute a source SKU when a stored catalog identity is missing", async () => {
    await createOmsService(orm).ingestOrder(2, "fixture-missing-variant", orderData());
    const [line] = await orm.select().from(schema.omsOrderLines);
    await expect(buildWmsLineItemFromOmsLine(orm, { ...line, productVariantId: 999 }, 2, 90))
      .rejects.toMatchObject({ code: "WMS_CATALOG_VARIANT_MISSING", context: { variantId: 999 } });
  });
  it("does not rebind an existing line if channel mappings change before a later replay", async () => {
    const service = createOmsService(orm);
    await service.ingestOrder(2, "fixture-rebind", orderData());
    await database.pool.query("UPDATE channels.channel_listings SET product_variant_id=12 WHERE channel_id=2");
    await expect(service.ingestOrder(2, "fixture-rebind", orderData()))
      .rejects.toMatchObject({ code: "ORDER_LINE_IDENTITY_CHANGE_REQUIRES_REVIEW" });
    expect((await orm.select().from(schema.omsOrderLines))[0]).toMatchObject({ productVariantId: 11, sku: null, quantity: 2 });
    expect((await database.pool.query(`SELECT id FROM oms.oms_order_events WHERE event_type='line_catalog_identity_resolved'`)).rows).toHaveLength(1);
  });
  it("rolls back identity assignment and order creation if the audit write fails", async () => {
    await database.pool.query(`ALTER TABLE oms.oms_order_events ADD CONSTRAINT fixture_audit_failure
      CHECK (event_type <> 'line_catalog_identity_resolved')`);
    try {
      await expect(createOmsService(orm).ingestOrder(2, "fixture-audit-failure", orderData())).rejects.toThrow();
      expect(await orm.select().from(schema.omsOrders)).toHaveLength(0);
      expect(await orm.select().from(schema.omsOrderLines)).toHaveLength(0);
    } finally {
      await database.pool.query("ALTER TABLE oms.oms_order_events DROP CONSTRAINT fixture_audit_failure");
    }
  });
});
