import { pgSchema, text, varchar, integer, timestamp, boolean, numeric, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Explicit PostgreSQL Namespace for the Membership/Rewards Pillar
export const membershipSchema = pgSchema("membership");

// ============================================
// MEMBERS
// ============================================

export const members = membershipSchema.table("members", {
  id: varchar("id").primaryKey(),
  email: text("email"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  status: text("status"),
  shopifyCustomerId: varchar("shopify_customer_id"),
  tier: varchar("tier"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertMemberSchema = createInsertSchema(members);
export type Member = typeof members.$inferSelect;
export type InsertMember = z.infer<typeof insertMemberSchema>;

// ============================================
// PLANS
// ============================================

export const plans = membershipSchema.table("plans", {
  id: varchar("id").primaryKey(),
  name: text("name"),
  tierLevel: integer("tier_level"),
  
  // DYNAMIC CONFIG: The priority modifier subtracted/added to the base shipping score
  priorityModifier: integer("priority_modifier").notNull().default(5),
  
  priceCents: integer("price_cents"),
  billingInterval: text("billing_interval"),
  billingIntervalCount: integer("billing_interval_count"),
  shopifySellingPlanId: varchar("shopify_selling_plan_id"),
  shopifySellingPlanGid: varchar("shopify_selling_plan_gid"),
  includesDropship: boolean("includes_dropship"),
  isActive: boolean("is_active"),
});

export const insertPlanSchema = createInsertSchema(plans);
export type Plan = typeof plans.$inferSelect;
export type InsertPlan = z.infer<typeof insertPlanSchema>;

// ============================================
// MEMBER SUBSCRIPTIONS
// ============================================

export const memberSubscriptions = membershipSchema.table("member_subscriptions", {
  id: varchar("id").primaryKey(),
  memberId: varchar("member_id").references(() => members.id),
  planId: varchar("plan_id").references(() => plans.id),
  status: text("status"),
  billingInterval: text("billing_interval"),
  cycleStartedAt: timestamp("cycle_started_at"),
  shopifySubscriptionContractId: varchar("shopify_subscription_contract_id"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertMemberSubscriptionSchema = createInsertSchema(memberSubscriptions);
export type MemberSubscription = typeof memberSubscriptions.$inferSelect;
export type InsertMemberSubscription = z.infer<typeof insertMemberSubscriptionSchema>;


// ============================================
// INTROSPECTED AUTOGENERATED MEMBERSHIP TABLES
// ============================================

export const accessRules = membershipSchema.table("access_rules", {
  id: text("id").primaryKey(),
  resourceType: text("resource_type"),
  resourceId: text("resource_id"),
  resourceName: text("resource_name"),
  requiredPlanIds: text("required_plan_ids"),
  gatingBehavior: text("gating_behavior"),
  redirectUrl: text("redirect_url"),
  isActive: boolean("is_active"),
});

export const portalConfig = membershipSchema.table("portal_config", {
  id: text("id").primaryKey(),
  showLifetimeSavings: boolean("show_lifetime_savings"),
  showRewardsBalance: boolean("show_rewards_balance"),
  showOrderHistory: boolean("show_order_history"),
  showUpcomingBilling: boolean("show_upcoming_billing"),
  allowPlanChanges: boolean("allow_plan_changes"),
  allowCancellation: boolean("allow_cancellation"),
  customMessage: text("custom_message"),
  heroHeadline: text("hero_headline"),
  heroSubheadline: text("hero_subheadline"),
  benefitCards: jsonb("benefit_cards"),
  featuredProductIds: jsonb("featured_product_ids"),
  featuredCollectionId: text("featured_collection_id"),
  ctaLoginText: text("cta_login_text"),
  ctaJoinText: text("cta_join_text"),
  showPlansSection: boolean("show_plans_section"),
  showProductsSection: boolean("show_products_section"),
  featuredPlanIds: jsonb("featured_plan_ids"),
  showMemberPricingSection: boolean("show_member_pricing_section"),
  memberPricingCollectionId: text("member_pricing_collection_id"),
  memberPricingProductIds: jsonb("member_pricing_product_ids"),
  memberPricingTitle: text("member_pricing_title"),
  memberPricingSubtitle: text("member_pricing_subtitle"),
  showMembershipUpsell: boolean("show_membership_upsell"),
  membershipUpsellPlanId: text("membership_upsell_plan_id"),
  membershipUpsellMessage: text("membership_upsell_message"),
  showCollectionUpsell: boolean("show_collection_upsell"),
  showProductDetailUpsell: boolean("show_product_detail_upsell"),
  upsellSavingsDisplayMode: text("upsell_savings_display_mode"),
  upsellSavingsThreshold: text("upsell_savings_threshold"),
  upsellBgColor: text("upsell_bg_color"),
  upsellTextColor: text("upsell_text_color"),
  upsellBorderColor: text("upsell_border_color"),
  priceBadgeBgColor: text("price_badge_bg_color"),
  priceBadgeTextColor: text("price_badge_text_color"),
  priceBadgeBorderColor: text("price_badge_border_color"),
  savingsBadgeBgColor: text("savings_badge_bg_color"),
  savingsBadgeTextColor: text("savings_badge_text_color"),
  upsellWidgetHeadline: text("upsell_widget_headline"),
  upsellWidgetSubtext: text("upsell_widget_subtext"),
  upsellWidgetBgColor: text("upsell_widget_bg_color"),
  upsellWidgetBorderColor: text("upsell_widget_border_color"),
  upsellWidgetTextColor: text("upsell_widget_text_color"),
  upsellWidgetSavingsColor: text("upsell_widget_savings_color"),
  flyinHeadline: text("flyin_headline"),
  flyinBenefits: jsonb("flyin_benefits"),
  flyinBenefitsLinkText: text("flyin_benefits_link_text"),
  flyinBenefitsLinkUrl: text("flyin_benefits_link_url"),
  flyinOption1Text: text("flyin_option1_text"),
  flyinOption2Text: text("flyin_option2_text"),
  flyinCartSavingsText: text("flyin_cart_savings_text"),
  flyinButtonText: text("flyin_button_text"),
  flyinButtonBgColor: text("flyin_button_bg_color"),
  flyinButtonTextColor: text("flyin_button_text_color"),
  socialFacebookUrl: text("social_facebook_url"),
  socialInstagramUrl: text("social_instagram_url"),
  socialTwitterUrl: text("social_twitter_url"),
  socialYoutubeUrl: text("social_youtube_url"),
  socialTiktokUrl: text("social_tiktok_url"),
});

export const productCollections = membershipSchema.table("product_collections", {
  id: text("id").primaryKey(),
  productId: text("product_id"),
  collectionId: text("collection_id"),
});

export const notificationTemplates = membershipSchema.table("notification_templates", {
  id: text("id").primaryKey(),
  name: text("name"),
  type: text("type"),
  subject: text("subject"),
  bodyHtml: text("body_html"),
  isActive: boolean("is_active"),
  category: text("category"),
  description: text("description"),
  klaviyoListId: text("klaviyo_list_id"),
});

export const backInStockSends = membershipSchema.table("back_in_stock_sends", {
  id: text("id").primaryKey(),
  subscriptionId: text("subscription_id"),
  provider: text("provider"),
  eventName: text("event_name"),
  createdAt: timestamp("created_at"),
  success: integer("success"),
  error: text("error"),
});

export const backInStockSubscriptions = membershipSchema.table("back_in_stock_subscriptions", {
  id: text("id").primaryKey(),
  shopDomain: text("shop_domain"),
  email: text("email"),
  productId: text("product_id"),
  variantId: text("variant_id"),
  inventoryItemId: text("inventory_item_id"),
  productTitle: text("product_title"),
  variantTitle: text("variant_title"),
  productHandle: text("product_handle"),
  productUrl: text("product_url"),
  source: text("source"),
  status: text("status"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
  notifiedAt: timestamp("notified_at"),
  cancelledAt: timestamp("cancelled_at"),
  notifyCount: integer("notify_count"),
  lastError: text("last_error"),
  phone: text("phone"),
  channel: text("channel"),
});

export const collectionAlertNotificationQueue = membershipSchema.table("collection_alert_notification_queue", {
  id: text("id").primaryKey(),
  collectionId: text("collection_id"),
  collectionTitle: text("collection_title"),
  productId: text("product_id"),
  productTitle: text("product_title"),
  productUrl: text("product_url"),
  productImage: text("product_image"),
  notificationType: text("notification_type"),
  createdAt: timestamp("created_at"),
  processedAt: timestamp("processed_at"),
  batchId: text("batch_id"),
});

export const collectionAlertSettings = membershipSchema.table("collection_alert_settings", {
  id: text("id").primaryKey(),
  collectionId: text("collection_id"),
  collectionHandle: text("collection_handle"),
  collectionTitle: text("collection_title"),
  enabled: boolean("enabled"),
  bannerTitle: text("banner_title"),
  bannerCtaText: text("banner_cta_text"),
  notifyOnNewProduct: boolean("notify_on_new_product"),
  notifyOnRestock: boolean("notify_on_restock"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
  digestWaitMinutes: integer("digest_wait_minutes"),
});

export const collectionAlertSubscriptions = membershipSchema.table("collection_alert_subscriptions", {
  id: text("id").primaryKey(),
  collectionId: text("collection_id"),
  collectionHandle: text("collection_handle"),
  collectionTitle: text("collection_title"),
  email: text("email"),
  phone: text("phone"),
  channel: text("channel"),
  smsConsent: boolean("sms_consent"),
  smsConsentAt: timestamp("sms_consent_at"),
  status: text("status"),
  notifyCount: integer("notify_count"),
  lastNotifiedAt: timestamp("last_notified_at"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
  unsubscribedAt: timestamp("unsubscribed_at"),
});

export const memberCurrentMembership = membershipSchema.table("member_current_membership", {
  memberId: text("member_id"),
  subscriptionId: text("subscription_id"),
  planId: text("plan_id"),
  status: text("status"),
  billingInterval: text("billing_interval"),
  cycleEndsAt: timestamp("cycle_ends_at"),
  scheduledPlanId: text("scheduled_plan_id"),
  updatedAt: timestamp("updated_at"),
});

export const memberShopifyCustomerIds = membershipSchema.table("member_shopify_customer_ids", {
  shopifyCustomerId: text("shopify_customer_id"),
  memberId: text("member_id"),
  createdAt: timestamp("created_at"),
  lastSeenAt: timestamp("last_seen_at"),
});

export const memberStats = membershipSchema.table("member_stats", {
  memberId: text("member_id"),
  lifetimeSavingsCents: integer("lifetime_savings_cents"),
  rewardsBalanceCents: integer("rewards_balance_cents"),
  totalOrders: integer("total_orders"),
  totalSpentCents: integer("total_spent_cents"),
  planSavingsCents: integer("plan_savings_cents"),
  couponSavingsCents: integer("coupon_savings_cents"),
  updatedAt: timestamp("updated_at"),
  qtySavingsCents: integer("qty_savings_cents"),
});

export const subscriptionBillingAttempts = membershipSchema.table("subscription_billing_attempts", {
  id: text("id").primaryKey(),
  contractId: text("contract_id"),
  shopifyBillingAttemptId: text("shopify_billing_attempt_id"),
  status: text("status"),
  amountCents: integer("amount_cents"),
  currency: text("currency"),
  billingCycleIndex: integer("billing_cycle_index"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  shopifyOrderId: text("shopify_order_id"),
  processedAt: timestamp("processed_at"),
  createdAt: timestamp("created_at"),
});

export const subscriptionContracts = membershipSchema.table("subscription_contracts", {
  id: text("id").primaryKey(),
  shopifyContractId: text("shopify_contract_id"),
  memberId: text("member_id"),
  shopifyCustomerId: text("shopify_customer_id"),
  planId: text("plan_id"),
  status: text("status"),
  billingInterval: text("billing_interval"),
  billingIntervalCount: integer("billing_interval_count"),
  nextBillingDate: timestamp("next_billing_date"),
  currentCycleStartDate: timestamp("current_cycle_start_date"),
  currentCycleEndDate: timestamp("current_cycle_end_date"),
  cancelledAt: timestamp("cancelled_at"),
  pausedAt: timestamp("paused_at"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
});

export const subscriptionEvents = membershipSchema.table("subscription_events", {
  id: text("id").primaryKey(),
  memberSubscriptionId: text("member_subscription_id"),
  shopifyContractId: text("shopify_contract_id"),
  eventType: text("event_type"),
  eventSource: text("event_source"),
  payload: jsonb("payload"),
  notes: text("notes"),
  createdAt: timestamp("created_at"),
});

export const subscriptionLedger = membershipSchema.table("subscription_ledger", {
  id: text("id").primaryKey(),
  subscriptionId: text("subscription_id"),
  memberId: text("member_id"),
  eventType: text("event_type"),
  fromPlanId: text("from_plan_id"),
  toPlanId: text("to_plan_id"),
  chargeCents: integer("charge_cents"),
  creditCents: integer("credit_cents"),
  netAmountCents: integer("net_amount_cents"),
  description: text("description"),
  refundPolicySnapshot: text("refund_policy_snapshot"),
  shopifyOrderId: text("shopify_order_id"),
  shopifyRefundId: text("shopify_refund_id"),
  createdAt: timestamp("created_at"),
});

export const sellingPlanGroups = membershipSchema.table("selling_plan_groups", {
  id: text("id").primaryKey(),
  shopifySellingPlanGroupId: text("shopify_selling_plan_group_id"),
  shopifySellingPlanId: text("shopify_selling_plan_id"),
  planId: text("plan_id"),
  name: text("name"),
  merchantCode: text("merchant_code"),
  billingInterval: text("billing_interval"),
  billingIntervalCount: integer("billing_interval_count"),
  isActive: boolean("is_active"),
  createdAt: timestamp("created_at"),
});

export const planCollectionExclusions = membershipSchema.table("plan_collection_exclusions", {
  id: text("id").primaryKey(),
  planId: text("plan_id"),
  collectionId: text("collection_id"),
  collectionTitle: text("collection_title"),
});

export const planEarningRules = membershipSchema.table("plan_earning_rules", {
  id: text("id").primaryKey(),
  planId: text("plan_id"),
  activityId: text("activity_id"),
  isEnabled: boolean("is_enabled"),
  rewardType: text("reward_type"),
  pointsValue: numeric("points_value"),
  multiplierValue: numeric("multiplier_value"),
  frequencyCap: text("frequency_cap"),
  maxEarningsPerPeriod: numeric("max_earnings_per_period"),
  requiresApproval: boolean("requires_approval"),
  targetProductIds: text("target_product_ids"),
  targetCollectionIds: text("target_collection_ids"),
  bonusCondition: text("bonus_condition"),
  bonusConditionValue: numeric("bonus_condition_value"),
});

export const planFeatureGrants = membershipSchema.table("plan_feature_grants", {
  id: text("id").primaryKey(),
  planId: text("plan_id"),
  featureKey: text("feature_key"),
  isEnabled: boolean("is_enabled"),
  grantedAt: timestamp("granted_at"),
});

export const planFeatures = membershipSchema.table("plan_features", {
  id: text("id").primaryKey(),
  featureKey: text("feature_key"),
  displayName: text("display_name"),
  description: text("description"),
  category: text("category"),
  requiresEnforcement: boolean("requires_enforcement"),
  sortOrder: integer("sort_order"),
  createdAt: timestamp("created_at"),
});

export const planMedalBenefits = membershipSchema.table("plan_medal_benefits", {
  id: text("id").primaryKey(),
  planId: text("plan_id"),
  medalId: text("medal_id"),
  benefits: jsonb("benefits"),
  isActive: boolean("is_active"),
  createdAt: timestamp("created_at"),
});

export const planRedemptionRules = membershipSchema.table("plan_redemption_rules", {
  id: text("id").primaryKey(),
  planId: text("plan_id"),
  redemptionOptionId: text("redemption_option_id"),
  isEnabled: boolean("is_enabled"),
  customPointsCost: integer("custom_points_cost"),
  customValueAmount: numeric("custom_value_amount"),
  maxRedemptionsPerMonth: integer("max_redemptions_per_month"),
  createdAt: timestamp("created_at"),
  customExpiryDays: integer("custom_expiry_days"),
});

export const planVariantOverrides = membershipSchema.table("plan_variant_overrides", {
  id: text("id").primaryKey(),
  planId: text("plan_id"),
  variantId: text("variant_id"),
  productId: text("product_id"),
  sku: text("sku"),
  productTitle: text("product_title"),
  variantTitle: text("variant_title"),
  overrideType: text("override_type"),
  discountPercent: numeric("discount_percent"),
  fixedPrice: numeric("fixed_price"),
  isActive: boolean("is_active"),
});

export const earningActivities = membershipSchema.table("earning_activities", {
  id: text("id").primaryKey(),
  activityType: text("activity_type"),
  displayName: text("display_name"),
  description: text("description"),
  requiresVerification: boolean("requires_verification"),
  verificationUrl: text("verification_url"),
  externalServiceId: text("external_service_id"),
  sortOrder: integer("sort_order"),
  category: text("category"),
  icon: text("icon"),
  isRepeatable: boolean("is_repeatable"),
  automationSource: text("automation_source"),
  defaultPoints: numeric("default_points"),
  defaultMultiplier: numeric("default_multiplier"),
  isSystemActivity: boolean("is_system_activity"),
});

export const memberEarningEvents = membershipSchema.table("member_earning_events", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  activityId: text("activity_id"),
  status: text("status"),
  pointsAwarded: numeric("points_awarded"),
  verifiedAt: timestamp("verified_at"),
  verifiedBy: text("verified_by"),
  rejectionReason: text("rejection_reason"),
  createdAt: timestamp("created_at"),
  planEarningRuleId: text("plan_earning_rule_id"),
  orderId: text("order_id"),
  productId: text("product_id"),
  referredMemberId: text("referred_member_id"),
  externalReference: text("external_reference"),
  metadata: jsonb("metadata"),
  expiresAt: timestamp("expires_at"),
});

export const memberMedalAchievements = membershipSchema.table("member_medal_achievements", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  medalId: text("medal_id"),
  achievedAt: timestamp("achieved_at"),
  pointsAtAchievement: integer("points_at_achievement"),
  notificationSent: boolean("notification_sent"),
});

export const memberReferrals = membershipSchema.table("member_referrals", {
  id: text("id").primaryKey(),
  referrerMemberId: text("referrer_member_id"),
  referredMemberId: text("referred_member_id"),
  referredEmail: text("referred_email"),
  referralCode: text("referral_code"),
  status: text("status"),
  signupPointsAwarded: boolean("signup_points_awarded"),
  purchasePointsAwarded: boolean("purchase_points_awarded"),
  signupAt: timestamp("signup_at"),
  firstPurchaseAt: timestamp("first_purchase_at"),
  expiresAt: timestamp("expires_at"),
  createdAt: timestamp("created_at"),
});

export const medalBenefitGrants = membershipSchema.table("medal_benefit_grants", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  medalId: text("medal_id"),
  achievementId: text("achievement_id"),
  benefitType: text("benefit_type"),
  benefitValue: text("benefit_value"),
  benefitDescription: text("benefit_description"),
  shopifyDiscountId: text("shopify_discount_id"),
  shopifyPriceRuleId: text("shopify_price_rule_id"),
  discountCode: text("discount_code"),
  shopifyProductId: text("shopify_product_id"),
  shopifyVariantId: text("shopify_variant_id"),
  status: text("status"),
  claimedAt: timestamp("claimed_at"),
  claimedOrderId: text("claimed_order_id"),
  expiresAt: timestamp("expires_at"),
  emailSent: boolean("email_sent"),
  emailSentAt: timestamp("email_sent_at"),
  metadata: jsonb("metadata"),
  grantedAt: timestamp("granted_at"),
  createdAt: timestamp("created_at"),
});

export const redemptionOptions = membershipSchema.table("redemption_options", {
  id: text("id").primaryKey(),
  name: text("name"),
  slug: text("slug"),
  description: text("description"),
  redemptionType: text("redemption_type"),
  pointsCost: integer("points_cost"),
  valueAmount: numeric("value_amount"),
  valueType: text("value_type"),
  shopifyDiscountType: text("shopify_discount_type"),
  usageLimit: integer("usage_limit"),
  expiryDays: integer("expiry_days"),
  minimumOrderAmount: numeric("minimum_order_amount"),
  icon: text("icon"),
  badgeColor: text("badge_color"),
  sortOrder: integer("sort_order"),
  isActive: boolean("is_active"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
});

export const rewardLedger = membershipSchema.table("reward_ledger", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  entryType: text("entry_type"),
  sourceType: text("source_type"),
  points: numeric("points"),
  orderId: text("order_id"),
  orderItemId: text("order_item_id"),
  referenceId: text("reference_id"),
  activityId: text("activity_id"),
  redemptionType: text("redemption_type"),
  discountCode: text("discount_code"),
  shopifyDiscountId: text("shopify_discount_id"),
  description: text("description"),
  adminNote: text("admin_note"),
  metadata: jsonb("metadata"),
  expiresAt: timestamp("expires_at"),
  status: text("status"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at"),
  omsOrderLineId: integer("oms_order_line_id"),
});

export const rewardMedals = membershipSchema.table("reward_medals", {
  id: text("id").primaryKey(),
  name: text("name"),
  slug: text("slug"),
  description: text("description"),
  thresholdPoints: integer("threshold_points"),
  lifetimePointsThreshold: integer("lifetime_points_threshold"),
  orderCountThreshold: integer("order_count_threshold"),
  icon: text("icon"),
  color: text("color"),
  badgeImageUrl: text("badge_image_url"),
  benefits: jsonb("benefits"),
  sortOrder: integer("sort_order"),
  isActive: boolean("is_active"),
  createdAt: timestamp("created_at"),
});

export const rewardOverrides = membershipSchema.table("reward_overrides", {
  id: text("id").primaryKey(),
  sku: text("sku"),
  shopifyVariantId: text("shopify_variant_id"),
  productTitle: text("product_title"),
  rewardsMultiplier: numeric("rewards_multiplier"),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  isActive: boolean("is_active"),
});

export const rewardRedemptions = membershipSchema.table("reward_redemptions", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  pointsUsed: numeric("points_used"),
  discountValue: numeric("discount_value"),
  discountCode: text("discount_code"),
  shopifyPriceRuleId: text("shopify_price_rule_id"),
  shopifyDiscountId: text("shopify_discount_id"),
  status: text("status"),
  usedAt: timestamp("used_at"),
  expiresAt: timestamp("expires_at"),
  createdAt: timestamp("created_at"),
  redemptionType: text("redemption_type"),
  cryptoCurrency: text("crypto_currency"),
  cryptoAmount: numeric("crypto_amount"),
  destinationWallet: text("destination_wallet"),
  txHash: text("tx_hash"),
  ledgerEntryId: text("ledger_entry_id"),
  promoCode: text("promo_code"),
  promoDiscountValue: numeric("promo_discount_value"),
  shippingCreditValue: numeric("shipping_credit_value"),
  totalCombinedValue: numeric("total_combined_value"),
  checkoutUrl: text("checkout_url"),
  cartSubtotal: numeric("cart_subtotal"),
  shopifyOrderId: text("shopify_order_id"),
});

export const socialAccounts = membershipSchema.table("social_accounts", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  platform: text("platform"),
  externalUserId: text("external_user_id"),
  externalUsername: text("external_username"),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  tokenExpiresAt: timestamp("token_expires_at"),
  scopes: text("scopes"),
  status: text("status"),
  connectedAt: timestamp("connected_at"),
  lastVerifiedAt: timestamp("last_verified_at"),
});

export const socialActionVerifications = membershipSchema.table("social_action_verifications", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  socialAccountId: text("social_account_id"),
  platform: text("platform"),
  actionType: text("action_type"),
  targetId: text("target_id"),
  targetName: text("target_name"),
  verificationStatus: text("verification_status"),
  verificationMethod: text("verification_method"),
  lastCheckedAt: timestamp("last_checked_at"),
  verifiedAt: timestamp("verified_at"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at"),
});

export const socialVerifications = membershipSchema.table("social_verifications", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  platform: text("platform"),
  activityType: text("activity_type"),
  verified: boolean("verified"),
  verifiedAt: timestamp("verified_at"),
  pointsAwarded: integer("points_awarded"),
  createdAt: timestamp("created_at"),
});

export const tokenTransactions = membershipSchema.table("token_transactions", {
  id: text("id").primaryKey(),
  memberId: text("member_id"),
  rewardLedgerId: text("reward_ledger_id"),
  transactionType: text("transaction_type"),
  tokenAmount: numeric("token_amount"),
  pointsAmount: numeric("points_amount"),
  network: text("network"),
  blockchainTxHash: text("blockchain_tx_hash"),
  blockNumber: integer("block_number"),
  fromAddress: text("from_address"),
  toAddress: text("to_address"),
  status: text("status"),
  errorMessage: text("error_message"),
  confirmedAt: timestamp("confirmed_at"),
  gasFee: numeric("gas_fee"),
  gasFeeCurrency: text("gas_fee_currency"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at"),
});

export const marketplaceExclusions = membershipSchema.table("marketplace_exclusions", {
  id: text("id").primaryKey(),
  type: text("type"),
  value: text("value"),
  description: text("description"),
  isActive: boolean("is_active"),
  createdAt: timestamp("created_at"),
});

