/** Explicit PostgreSQL hardening coverage, carried forward from CI at bf044f8ec.
 * Add new suites here (not to workflow commands), then update the coverage guard
 * and document the intentional inventory change in the PR. Deterministic shards
 * partition this entire list. Each file gets a fresh disposable database/process;
 * no schema-mutating files run concurrently in a job.
 */
export const POSTGRES_SHARD_COUNT = 8;

export const POSTGRES_TEST_FILES: readonly string[] = Object.freeze([
  "server/platform/__tests__/integration/financial-command-results.integration.test.ts",
  "server/modules/procurement/__tests__/integration/procurement-cost-evidence.integration.test.ts",
  "server/modules/inventory/__tests__/integration/cost-report-reads.integration.test.ts",
  "server/modules/procurement/__tests__/integration/shipment-purchase-orders.integration.test.ts",
  "server/modules/procurement/__tests__/integration/receiving-cost-application.integration.test.ts",
  "server/modules/inventory/__tests__/integration/cost-lineage-owners.integration.test.ts",
  "server/modules/inventory/__tests__/integration/canonical-claim-picker-observation.integration.test.ts",
  "server/modules/procurement/__tests__/integration/invoice-cost-review.integration.test.ts",
  "server/modules/inventory/__tests__/integration/quantity-ledger.integration.test.ts",
  "server/modules/inventory/__tests__/integration/quantity-ledger-hardening.integration.test.ts",
  "server/modules/inventory/__tests__/integration/replenishment-claim-safety.integration.test.ts",
  "server/modules/procurement/__tests__/integration/rfq-workflow.integration.test.ts",
  "server/modules/procurement/__tests__/integration/supplier-sourcing.integration.test.ts",
  "server/modules/procurement/__tests__/integration/inbound-tracking.integration.test.ts",
  "server/modules/procurement/__tests__/integration/cost-reporting.integration.test.ts",
  "server/modules/procurement/__tests__/integration/procurement-settings-authority.integration.test.ts",
  "server/modules/procurement/__tests__/integration/purchase-planning-policy.integration.test.ts",
  "server/modules/procurement/__tests__/integration/purchase-approval-authority.integration.test.ts",
  "server/modules/procurement/__tests__/integration/purchase-pipeline.integration.test.ts",
  "server/modules/procurement/__tests__/integration/purchase-planning-receipt-supply.integration.test.ts",
  "server/modules/procurement/__tests__/integration/po-email-outbox.integration.test.ts",
  "server/modules/procurement/__tests__/integration/purchase-workspace.integration.test.ts",
  "server/modules/procurement/__tests__/integration/shipment-cost-commands.integration.test.ts",
  "server/modules/procurement/__tests__/integration/shipment-line-commands.integration.test.ts",
  "server/modules/procurement/__tests__/integration/receiving-unit-integrity.integration.test.ts",
  "server/modules/procurement/__tests__/integration/po-lifecycle-timestamp.integration.test.ts",
  "server/modules/procurement/__tests__/integration/historical-po-supplier-evidence-backfill.integration.test.ts",
  "server/modules/procurement/__tests__/integration/legacy-po-receive-config-remediation.integration.test.ts",
  "server/modules/inventory/__tests__/integration/invoice-variance-cogs.integration.test.ts",
  "server/modules/procurement/__tests__/integration/ap-invoice-line-metadata.integration.test.ts",
  "server/modules/inventory/__tests__/integration/lot-cost-column-types.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-availability-foundation.integration.test.ts",
  "server/modules/inventory/__tests__/integration/inventory-cutover-encumbrance.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-cutover-preflight.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-cutover-reconstruction.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-cutover-capture-stage.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-cutover-opening.integration.test.ts",
  "server/modules/oms/__tests__/integration/inventory-cutover-receipt-evidence.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-cutover-admission-fence.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-cutover-composition.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/quantity-publication-admission.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/quantity-publication-catchup-canonical.integration.test.ts",
  "server/modules/channels/__tests__/integration/channel-quantity-publication-catchup.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-availability-dispatch-migration.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-availability-dispatch-runtime.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-availability-dispatch-source-command.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-availability-runtime-shipment.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/shipment-publication-transaction.integration.test.ts",
  "server/modules/inventory/__tests__/integration/canonical-claim-dispatch-inventory.integration.test.ts",
  "server/modules/inventory/__tests__/integration/legacy-shipment-authority-fence.integration.test.ts",
  "server/modules/inventory/__tests__/integration/shipment-lot-parity.integration.test.ts",
  "server/modules/oms/__tests__/integration/channel-shipment-runtime-preparation.integration.test.ts",
  "server/modules/oms/__tests__/integration/shipment-canonical-echo-preparation.integration.test.ts",
  "server/modules/wms/__tests__/integration/canonical-claim-dispatch-source.integration.test.ts",
  "server/modules/inventory-planning/__tests__/integration/inventory-demand-dispatch.integration.test.ts",
  "server/modules/inventory/__tests__/integration/shipment-quantity-evidence.integration.test.ts",
  "server/modules/inventory/__tests__/integration/shipment-operational-dispatch.integration.test.ts",
  "server/modules/oms/__tests__/integration/shipment-omission-compatibility.integration.test.ts",
  "server/modules/wms/__tests__/integration/shipment-unpick-source-bin.integration.test.ts",
  "server/modules/shipping/__tests__/integration/historical-shipstation-contents-correction.repository.integration.test.ts",
  "server/modules/warehouse/__tests__/integration/work-configuration.integration.test.ts",
  "server/modules/warehouse/__tests__/integration/assembly-work.integration.test.ts",
  "server/modules/channels/__tests__/integration/allocation-engine.integration.test.ts",
  "server/modules/channels/__tests__/integration/source-lock.integration.test.ts",
  "server/modules/inventory/__tests__/integration/allocation-concurrency.integration.test.ts",
  "server/modules/shipping/__tests__/integration/package-allocation-ledger.repository.integration.test.ts",
  "server/modules/shipping-engine/__tests__/integration/fulfillment-provider-connections.integration.test.ts",
  "server/modules/dropship/__tests__/integration/dropship-ebay-listing-policy-bulk.integration.test.ts",
  "server/modules/dropship/__tests__/integration/dropship-listing-price.integration.test.ts",
  "server/modules/dropship/__tests__/integration/dropship-listing-content.integration.test.ts",
  "server/modules/dropship/__tests__/integration/dropship-product-cost.integration.test.ts",
  "server/modules/dropship/__tests__/integration/dropship-marketplace-credentials.integration.test.ts",
  "server/modules/oms/__tests__/integration/order-line-catalog-identity.integration.test.ts",
]);
