import { resolve } from "node:path";

import { config } from "dotenv";
import pg from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { PostgresCanonicalClaimInventoryRepository } from "../../infrastructure/canonical-claim-inventory.repository";
import { PostgresCanonicalClaimPickerObservationReviewRepository } from "../../../orders/canonical-claim-picker-observation-review.repository";

config({ path: resolve(process.cwd(), ".env.test") });

const TEST_DB_URL = process.env.ECHELON_TEST_DATABASE_URL;
const DISPOSABLE_DB = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const describeWithDisposableDb = TEST_DB_URL && DISPOSABLE_DB ? describe : describe.skip;
const OCCURRED_AT = new Date("2026-09-03T11:00:00.000Z");

function sslConfig(connectionString: string) {
  return /localhost|127\.0\.0\.1/.test(connectionString)
    ? false
    : { rejectUnauthorized: false };
}

describeWithDisposableDb.sequential("canonical claim picker-observation PostgreSQL transaction", () => {
  let pool: pg.Pool;
  const suffix = `${process.pid}`;
  const schemas = {
    inventory: `claim_observation_inventory_${suffix}`,
    warehouse: `claim_observation_warehouse_${suffix}`,
    wms: `claim_observation_wms_${suffix}`,
  } as const;

  const qualify = (statement: string) => statement
    .replaceAll("inventory.", `"${schemas.inventory}".`)
    .replaceAll("warehouse.", `"${schemas.warehouse}".`)
    .replaceAll("wms.", `"${schemas.wms}".`);

  const observationInput = (client: { query: (text: string, values?: unknown[]) => Promise<any> }) => ({
    client,
    claimId: BigInt(9),
    releases: [{
      claimResourceId: BigInt(12),
      inventoryLevelId: 11,
      warehouseLocationId: 2,
      sourceVariantId: 105,
      releaseQty: BigInt(3),
      lotAllocations: [{ inventoryLotId: 51, releaseQty: BigInt(3) }],
      orderItemId: 71,
    }],
    sourceCostLayers: [{
      inventoryLotId: 51,
      quantity: BigInt(3),
      unitCostMills: BigInt(125),
      poUnitCostMills: BigInt(100),
      packagingUnitCostMills: BigInt(20),
      landedUnitCostMills: BigInt(5),
    }],
    target: {
      claimResourceId: BigInt(13),
      inventoryLevelId: 15,
      warehouseLocationId: 3,
      sourceVariantId: 105,
      claimedQty: 3,
      orderItemId: 71,
    },
    observationReference: "a".repeat(64),
    orderId: 70,
    actor: "integration-test",
    reason: "picker observed three units in P-3",
    occurredAt: OCCURRED_AT,
  });

  beforeAll(async () => {
    const protectedUrls = [
      process.env.DATABASE_URL,
      process.env.EXTERNAL_DATABASE_URL,
    ].filter((value): value is string => Boolean(value));
    if (!TEST_DB_URL || !DISPOSABLE_DB || protectedUrls.includes(TEST_DB_URL)) {
      throw new Error("Picker-observation integration tests require a distinct disposable database");
    }
    pool = new pg.Pool({
      connectionString: TEST_DB_URL,
      max: 2,
      ssl: sslConfig(TEST_DB_URL),
    });
    await pool.query(`
      CREATE SCHEMA "${schemas.warehouse}";
      CREATE SCHEMA "${schemas.inventory}";
      CREATE SCHEMA "${schemas.wms}";

      CREATE TABLE "${schemas.warehouse}".warehouse_locations (
        id integer PRIMARY KEY,
        warehouse_id integer NOT NULL,
        code varchar(50) NOT NULL
      );

      CREATE TABLE "${schemas.inventory}".inventory_levels (
        id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
        product_variant_id integer NOT NULL,
        warehouse_location_id integer NOT NULL,
        variant_qty integer NOT NULL DEFAULT 0 CHECK (variant_qty >= 0),
        reserved_qty integer NOT NULL DEFAULT 0 CHECK (reserved_qty >= 0 AND reserved_qty <= variant_qty),
        picked_qty integer NOT NULL DEFAULT 0,
        packed_qty integer NOT NULL DEFAULT 0,
        backorder_qty integer NOT NULL DEFAULT 0,
        updated_at timestamptz NOT NULL,
        UNIQUE (product_variant_id, warehouse_location_id)
      );

      CREATE TABLE "${schemas.inventory}".inventory_lots (
        id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
        lot_number varchar(50) NOT NULL UNIQUE,
        product_variant_id integer NOT NULL,
        warehouse_location_id integer NOT NULL,
        receiving_order_id integer,
        purchase_order_id integer,
        inbound_shipment_id integer,
        build_order_id integer,
        build_run_id integer,
        po_line_id integer,
        unit_cost_cents numeric(10,4) NOT NULL DEFAULT 0,
        po_unit_cost_cents numeric(10,4) NOT NULL DEFAULT 0,
        packaging_cost_cents numeric(10,4) NOT NULL DEFAULT 0,
        landed_cost_cents numeric(10,4) NOT NULL DEFAULT 0,
        total_unit_cost_cents numeric(10,4) NOT NULL DEFAULT 0,
        unit_cost_mills bigint NOT NULL DEFAULT 0,
        po_unit_cost_mills bigint NOT NULL DEFAULT 0,
        packaging_cost_mills bigint NOT NULL DEFAULT 0,
        landed_cost_mills bigint NOT NULL DEFAULT 0,
        total_unit_cost_mills bigint NOT NULL DEFAULT 0,
        qty_received integer NOT NULL DEFAULT 0,
        qty_on_hand integer NOT NULL DEFAULT 0 CHECK (qty_on_hand >= 0),
        qty_reserved integer NOT NULL DEFAULT 0 CHECK (qty_reserved >= 0 AND qty_reserved <= qty_on_hand),
        qty_picked integer NOT NULL DEFAULT 0,
        qty_consumed integer NOT NULL DEFAULT 0,
        received_at timestamptz NOT NULL,
        status varchar(20) NOT NULL DEFAULT 'active',
        cost_provisional integer NOT NULL DEFAULT 0 CHECK (cost_provisional IN (0, 1)),
        cost_source varchar(20),
        notes text,
        created_at timestamptz NOT NULL
      );

      CREATE TABLE "${schemas.inventory}".inventory_transactions (
        id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        product_variant_id integer,
        from_location_id integer,
        to_location_id integer,
        transaction_type varchar(30) NOT NULL,
        variant_qty_delta integer NOT NULL,
        variant_qty_before integer,
        variant_qty_after integer,
        reserved_qty_delta integer,
        source_state varchar(30),
        target_state varchar(30),
        unit_cost_cents numeric(10,4),
        unit_cost_mills bigint,
        total_cost_mills bigint,
        inventory_lot_id integer,
        order_id integer,
        order_item_id integer,
        cycle_count_id integer,
        reference_type varchar(50),
        reference_id varchar(300),
        user_id varchar(100),
        notes text,
        created_at timestamptz NOT NULL
      );

      CREATE TABLE "${schemas.wms}".orders (
        id integer PRIMARY KEY,
        order_number varchar(100) NOT NULL
      );
      CREATE TABLE "${schemas.wms}".order_items (
        id integer PRIMARY KEY,
        order_id integer NOT NULL,
        sku varchar(100) NOT NULL
      );
      CREATE TABLE "${schemas.wms}".allocation_exceptions (
        id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        order_id integer NOT NULL,
        order_item_id integer NOT NULL,
        order_number varchar(100),
        sku varchar(100),
        product_variant_id integer NOT NULL,
        exception_type varchar(50) NOT NULL,
        status varchar(30) NOT NULL,
        requested_qty integer NOT NULL,
        selected_location_id integer NOT NULL,
        selected_location_code varchar(50),
        resolution varchar(100),
        auto_fixed_setup boolean NOT NULL,
        review_reason text NOT NULL,
        metadata jsonb NOT NULL,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL
      );

      INSERT INTO "${schemas.warehouse}".warehouse_locations (id, warehouse_id, code)
      VALUES (2, 1, 'R-2'), (3, 1, 'P-3'), (4, 1, 'P-4');
      INSERT INTO "${schemas.inventory}".inventory_levels (
        id, product_variant_id, warehouse_location_id, variant_qty, reserved_qty, updated_at
      ) VALUES
        (11, 105, 2, 3, 3, '${OCCURRED_AT.toISOString()}'),
        (15, 105, 3, 1, 0, '${OCCURRED_AT.toISOString()}');
      INSERT INTO "${schemas.inventory}".inventory_lots (
        id, lot_number, product_variant_id, warehouse_location_id,
        receiving_order_id, purchase_order_id, inbound_shipment_id, po_line_id,
        unit_cost_cents, po_unit_cost_cents, packaging_cost_cents, landed_cost_cents,
        total_unit_cost_cents, unit_cost_mills, po_unit_cost_mills,
        packaging_cost_mills, landed_cost_mills, total_unit_cost_mills,
        qty_received, qty_on_hand, qty_reserved, received_at, status,
        cost_provisional, cost_source, created_at
      ) VALUES
        (51, 'SOURCE-51', 105, 2, 401, 402, 403, 404,
         1.25, 1.00, 0.20, 0.05, 1.25, 125, 100, 20, 5, 125,
         3, 3, 3, '${OCCURRED_AT.toISOString()}', 'active', 0, 'purchase_order', '${OCCURRED_AT.toISOString()}'),
        (52, 'TARGET-52', 105, 3, 405, 406, 407, 408,
         1.25, 1.00, 0.20, 0.05, 1.25, 125, 100, 20, 5, 125,
         1, 1, 0, '${OCCURRED_AT.toISOString()}', 'active', 0, 'purchase_order', '${OCCURRED_AT.toISOString()}');
      INSERT INTO "${schemas.wms}".orders (id, order_number) VALUES (70, 'ORDER-70');
      INSERT INTO "${schemas.wms}".order_items (id, order_id, sku) VALUES (71, 70, 'P5');
    `);
  }, 300_000);

  afterAll(async () => {
    if (!pool) return;
    await pool.query(`
      DROP SCHEMA IF EXISTS "${schemas.inventory}" CASCADE;
      DROP SCHEMA IF EXISTS "${schemas.warehouse}" CASCADE;
      DROP SCHEMA IF EXISTS "${schemas.wms}" CASCADE;
    `);
    await pool.end();
  });

  it("creates a zero target level with the production SQL contract", async () => {
    const client = await pool.connect();
    const rewritingClient = {
      query: (text: string, values?: unknown[]) => client.query(qualify(text), values),
    };
    const repository = new PostgresCanonicalClaimInventoryRepository();
    try {
      await client.query("BEGIN");
      const inventoryLevelId = await repository.ensureInventoryLevel({
        client: rewritingClient,
        productVariantId: 105,
        warehouseLocationId: 4,
        occurredAt: OCCURRED_AT,
      });
      const replayedInventoryLevelId = await repository.ensureInventoryLevel({
        client: rewritingClient,
        productVariantId: 105,
        warehouseLocationId: 4,
        occurredAt: OCCURRED_AT,
      });
      await client.query("COMMIT");
      expect(inventoryLevelId).toBeGreaterThan(0);
      expect(replayedInventoryLevelId).toBe(inventoryLevelId);
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }

    const level = await pool.query<{ variant_qty: number; reserved_qty: number }>(
      `SELECT variant_qty, reserved_qty
       FROM "${schemas.inventory}".inventory_levels
       WHERE product_variant_id = 105 AND warehouse_location_id = 4`,
    );
    expect(level.rows).toEqual([{ variant_qty: 0, reserved_qty: 0 }]);
    await pool.query(
      `DELETE FROM "${schemas.inventory}".inventory_levels
       WHERE product_variant_id = 105 AND warehouse_location_id = 4`,
    );
  });

  it("rejects a picker observation that would relocate claim stock across warehouses", async () => {
    const client = await pool.connect();
    const rewritingClient = {
      query: (text: string, values?: unknown[]) => client.query(qualify(text), values),
    };
    try {
      await client.query("BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE");
      await client.query(
        `UPDATE "${schemas.warehouse}".warehouse_locations SET warehouse_id = 2 WHERE id = 2`,
      );
      const repository = new PostgresCanonicalClaimInventoryRepository();
      await expect(repository.reconcileObservedPickResource(observationInput(rewritingClient)))
        .rejects.toMatchObject({ code: "CLAIM_OBSERVATION_SOURCE_CHANGED" });
    } finally {
      await client.query("ROLLBACK");
      client.release();
    }
  });

  it("relocates exact reserved lineage without changing warehouse on-hand", async () => {
    const client = await pool.connect();
    const rewritingClient = {
      query: (text: string, values?: unknown[]) => client.query(qualify(text), values),
    };
    const repository = new PostgresCanonicalClaimInventoryRepository();
    try {
      await client.query("BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE");
      const result = await repository.reconcileObservedPickResource(observationInput(rewritingClient));
      await client.query("COMMIT");

      expect(result).toMatchObject({
        recordedReconciledQuantity: BigInt(1),
        observedRelocatedQuantity: BigInt(2),
      });
      expect(result.relocatedInventoryLotIds).toHaveLength(1);
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }

    const levels = await pool.query<{ id: number; variant_qty: number; reserved_qty: number }>(
      `SELECT id, variant_qty, reserved_qty
       FROM "${schemas.inventory}".inventory_levels
       ORDER BY id`,
    );
    expect(levels.rows).toEqual([
      { id: 11, variant_qty: 1, reserved_qty: 0 },
      { id: 15, variant_qty: 3, reserved_qty: 3 },
    ]);
    expect(levels.rows.reduce((total, level) => total + level.variant_qty, 0)).toBe(4);

    const relocatedLot = await pool.query<{
      warehouse_location_id: number;
      receiving_order_id: number;
      purchase_order_id: number;
      inbound_shipment_id: number;
      po_line_id: number;
      qty_on_hand: number;
      qty_reserved: number;
      received_at: Date;
      total_unit_cost_mills: string;
      cost_provisional: number;
      cost_source: string;
    }>(
      `SELECT warehouse_location_id, receiving_order_id, purchase_order_id,
              inbound_shipment_id, po_line_id, qty_on_hand, qty_reserved,
              received_at, total_unit_cost_mills, cost_provisional, cost_source
       FROM "${schemas.inventory}".inventory_lots
       WHERE lot_number LIKE 'OBS-9-%'`,
    );
    expect(relocatedLot.rows).toEqual([expect.objectContaining({
      warehouse_location_id: 3,
      receiving_order_id: 401,
      purchase_order_id: 402,
      inbound_shipment_id: 403,
      po_line_id: 404,
      qty_on_hand: 2,
      qty_reserved: 2,
      received_at: OCCURRED_AT,
      total_unit_cost_mills: "125",
      cost_provisional: 0,
      cost_source: "purchase_order",
    })]);

    const ledger = await pool.query<{ transaction_type: string; variant_qty_delta: number }>(
      `SELECT transaction_type, variant_qty_delta
       FROM "${schemas.inventory}".inventory_transactions
       ORDER BY id`,
    );
    expect(ledger.rows.map((row) => row.transaction_type)).toEqual([
      "unreserve",
      "reserve",
      "transfer",
      "reserve_move",
    ]);
    expect(ledger.rows.filter((row) => row.transaction_type === "transfer"))
      .toEqual([{ transaction_type: "transfer", variant_qty_delta: 2 }]);
  });

  it("records review evidence through the same supplied transaction client", async () => {
    const client = await pool.connect();
    const rewritingClient = {
      query: (text: string, values?: unknown[]) => client.query(qualify(text), values),
    };
    try {
      await client.query("BEGIN");
      const repository = new PostgresCanonicalClaimPickerObservationReviewRepository();
      const reviewId = await repository.recordReview({
        client: rewritingClient,
        orderId: 70,
        orderItemId: 71,
        targetVariantId: 105,
        requestedQty: 3,
        selectedLocationId: 3,
        resolution: "picker_scan_count_correction",
        reviewReason: "picker observed three units in P-3",
        metadata: {
          schemaVersion: "inventory_availability_claim_picker_observation_v1",
          pickerNonBlocking: true,
          shipmentBlocking: false,
          claimId: "9",
          claimLineId: "20",
          observationKind: "validated_item_scan",
          observedPhysicalQty: "3",
          systemLevelQtyBefore: "1",
          systemLotQtyBefore: "1",
          recordedUnreservedQtyBefore: "1",
          recordedReconciledQty: "1",
          observedRelocatedQty: "2",
          relocatedInventoryLotIds: [100],
          releasedClaimResourceIds: ["12"],
          deviceType: "scanner",
          sessionId: "session-1",
          actor: "integration-test",
        },
        occurredAt: OCCURRED_AT,
      });
      await client.query("COMMIT");
      expect(reviewId).toBeGreaterThan(0);
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }

    const review = await pool.query<{ status: string; metadata: Record<string, unknown> }>(
      `SELECT status, metadata FROM "${schemas.wms}".allocation_exceptions`,
    );
    expect(review.rows).toEqual([expect.objectContaining({
      status: "needs_review",
      metadata: expect.objectContaining({
        observedRelocatedQty: "2",
        pickerNonBlocking: true,
        shipmentBlocking: false,
      }),
    })]);
  });

  it("commits a counted shortage from unreserved FIFO layers with exact item lineage", async () => {
    await pool.query(`
      INSERT INTO "${schemas.inventory}".inventory_levels (
        id, product_variant_id, warehouse_location_id, variant_qty, reserved_qty, updated_at
      ) VALUES (21, 205, 4, 10, 4, '${OCCURRED_AT.toISOString()}');
      INSERT INTO "${schemas.inventory}".inventory_lots (
        id, lot_number, product_variant_id, warehouse_location_id,
        unit_cost_cents, po_unit_cost_cents, total_unit_cost_cents,
        unit_cost_mills, po_unit_cost_mills, total_unit_cost_mills,
        qty_received, qty_on_hand, qty_reserved, received_at, status,
        cost_provisional, cost_source, created_at
      ) VALUES
        (61, 'COUNT-61', 205, 4, 1.25, 1.25, 1.25, 125, 125, 125,
         6, 6, 4, '${OCCURRED_AT.toISOString()}', 'active', 0, 'purchase_order', '${OCCURRED_AT.toISOString()}'),
        (62, 'COUNT-62', 205, 4, 2.00, 2.00, 2.00, 200, 200, 200,
         4, 4, 0, '${OCCURRED_AT.toISOString()}', 'active', 0, 'purchase_order', '${OCCURRED_AT.toISOString()}');
    `);
    const client = await pool.connect();
    const rewritingClient = {
      query: (text: string, values?: unknown[]) => client.query(qualify(text), values),
    };
    const repository = new PostgresCanonicalClaimInventoryRepository();
    let adjustmentTransactionId: number;
    try {
      await client.query("BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE");
      const result = await repository.applyCycleCountAdjustment({
        client: rewritingClient,
        inventoryLevelId: 21,
        productVariantId: 205,
        warehouseLocationId: 4,
        quantityBefore: 10,
        countedQty: 6,
        cycleCountId: 8,
        cycleCountItemId: 81,
        actor: "integration-test",
        reason: "verified physical count",
        occurredAt: OCCURRED_AT,
      });
      adjustmentTransactionId = result.adjustmentTransactionId;
      expect(result).toMatchObject({ consumedQty: BigInt(4), consumedCostMills: BigInt(650) });
      await client.query("COMMIT");
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }

    const level = await pool.query<{ variant_qty: number; reserved_qty: number }>(
      `SELECT variant_qty, reserved_qty
       FROM "${schemas.inventory}".inventory_levels WHERE id = 21`,
    );
    expect(level.rows).toEqual([{ variant_qty: 6, reserved_qty: 4 }]);
    const lots = await pool.query<{ id: number; qty_on_hand: number; qty_reserved: number }>(
      `SELECT id, qty_on_hand, qty_reserved
       FROM "${schemas.inventory}".inventory_lots WHERE id IN (61, 62) ORDER BY id`,
    );
    expect(lots.rows).toEqual([
      { id: 61, qty_on_hand: 4, qty_reserved: 4 },
      { id: 62, qty_on_hand: 2, qty_reserved: 0 },
    ]);
    const ledger = await pool.query<{
      id: string;
      from_location_id: number;
      variant_qty_delta: number;
      variant_qty_before: number;
      variant_qty_after: number;
      inventory_lot_id: number;
      unit_cost_mills: string;
      total_cost_mills: string;
      cycle_count_id: number;
      reference_type: string;
      reference_id: string;
    }>(
      `SELECT id, from_location_id, variant_qty_delta, variant_qty_before,
              variant_qty_after, inventory_lot_id, unit_cost_mills,
              total_cost_mills, cycle_count_id, reference_type, reference_id
       FROM "${schemas.inventory}".inventory_transactions
       WHERE cycle_count_id = 8 AND reference_type = 'cycle_count_item'
         AND reference_id = '81'
       ORDER BY id`,
    );
    expect(Number(ledger.rows[0]?.id)).toBe(adjustmentTransactionId!);
    expect(ledger.rows).toEqual([
      expect.objectContaining({
        from_location_id: 4,
        variant_qty_delta: -2,
        variant_qty_before: 10,
        variant_qty_after: 8,
        inventory_lot_id: 61,
        unit_cost_mills: "125",
        total_cost_mills: "250",
        cycle_count_id: 8,
        reference_type: "cycle_count_item",
        reference_id: "81",
      }),
      expect.objectContaining({
        from_location_id: 4,
        variant_qty_delta: -2,
        variant_qty_before: 8,
        variant_qty_after: 6,
        inventory_lot_id: 62,
        unit_cost_mills: "200",
        total_cost_mills: "400",
        cycle_count_id: 8,
        reference_type: "cycle_count_item",
        reference_id: "81",
      }),
    ]);
  });
});
