import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { getTableColumns, SQL, sql, type Table } from "drizzle-orm";
import { getTableConfig, PgDialect } from "drizzle-orm/pg-core";
import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import * as schema from "@shared/schema";
import { InventoryLotService } from "../../lots.service";
import { BuildExecutionRepository } from "../../infrastructure/build-execution.repository";
import { PostgresCanonicalClaimInventoryRepository } from "../../infrastructure/canonical-claim-inventory.repository";
import { buildMillsToRoundedCents, normalizeBuildLotCosts } from "../../infrastructure/build.repository";
import { lockInventoryCostGraph } from "../../infrastructure/cost-evidence.repository";
import { costEvidenceTransactionFromPg } from "../../infrastructure/cost-evidence-pg";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const enabled = databaseUrl && process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const databaseTests = enabled ? describe : describe.skip;
const occurredAt = new Date("2026-09-07T12:00:00.000Z");

function tableDdl(table: Parameters<typeof getTableConfig>[0]): string {
  const definition = getTableConfig(table);
  const fields = Object.values(getTableColumns(table as Table)).map((column) => {
    if (column.primary && column.name === "id") return `"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    const value = column.default;
    const defaultSql = value === undefined ? "" : value instanceof SQL
      ? new PgDialect().sqlToQuery(value).sql
      : typeof value === "string" ? `'${value.replaceAll("'", "''")}'`
      : typeof value === "bigint" || typeof value === "number" || typeof value === "boolean" ? String(value)
      : (() => { throw new Error(`Unsupported fixture default: ${definition.name}.${column.name}`); })();
    return `"${column.name}" ${column.getSQLType()}${defaultSql ? ` DEFAULT ${defaultSql}` : ""}${column.notNull ? " NOT NULL" : ""}`;
  });
  return `CREATE TABLE "${definition.schema}"."${definition.name}" (${fields.join(",")})`;
}

databaseTests.sequential("cost contribution physical owners on PostgreSQL", () => {
  let pool: pg.Pool;
  let database: ReturnType<typeof drizzle<typeof schema>>;
  const ownedSchemas: string[] = [];

  beforeAll(async () => {
    const address = new URL(databaseUrl!);
    if (!["127.0.0.1", "localhost", "[::1]"].includes(address.hostname)
      || [process.env.DATABASE_URL, process.env.EXTERNAL_DATABASE_URL].filter(Boolean).includes(databaseUrl)) {
      throw new Error("Cost lineage tests require a separate explicitly disposable local PostgreSQL database.");
    }
    pool = new pg.Pool({ connectionString: databaseUrl, application_name: "echelon-cost-lineage-test", max: 4 });
    for (const name of ["procurement", "inventory"]) {
      await pool.query(`CREATE SCHEMA ${name}`);
      ownedSchemas.push(name);
    }
    for (const table of ["purchase_order_lines", "inbound_shipment_lines", "receiving_orders", "receiving_lines", "vendor_invoice_lines"]) {
      await pool.query(`CREATE TABLE procurement.${table} (id integer PRIMARY KEY)`);
    }
    for (const table of [schema.inventoryLots, schema.inventoryTransactions, schema.inventoryLevels,
      schema.buildOrders, schema.buildOrderComponents, schema.buildRuns, schema.buildRunConsumptions, schema.buildComponentReservations]) {
      await pool.query(tableDdl(table));
    }
    await pool.query(`
      CREATE TABLE inventory.availability_claim_build_handoffs (build_order_id integer, claim_id bigint, claim_operation_id bigint, status text);
      CREATE UNIQUE INDEX level_identity ON inventory.inventory_levels(product_variant_id,warehouse_location_id);
      CREATE UNIQUE INDEX reservation_identity ON inventory.build_component_reservations(build_order_component_id,inventory_lot_id);
      CREATE UNIQUE INDEX build_run_replay_identity ON inventory.build_runs(idempotency_key);
    `);
    await pool.query(await readFile(resolve(process.cwd(), "migrations/222_procurement_cost_evidence.sql"), "utf8"));
    database = drizzle(pool, { schema });
  });

  beforeEach(async () => {
    await pool.query(`TRUNCATE inventory.lot_cost_contributions, inventory.inventory_transactions,
      inventory.inventory_lots, inventory.inventory_levels, inventory.build_run_consumptions,
      inventory.build_component_reservations, inventory.build_runs, inventory.build_order_components,
      inventory.build_orders RESTART IDENTITY CASCADE`);
  });

  afterAll(async () => {
    if (!pool) return;
    for (const name of [...ownedSchemas].reverse()) await pool.query(`DROP SCHEMA ${name} CASCADE`);
    await pool.end();
  });

  async function seedLot(id: number, qty: number, reserved = 0, variant = 101, location = 20) {
    await pool.query(`INSERT INTO inventory.inventory_lots
      (id,lot_number,product_variant_id,warehouse_location_id,qty_received,qty_on_hand,qty_reserved,
       received_at,unit_cost_mills,po_unit_cost_mills,packaging_cost_mills,landed_cost_mills,total_unit_cost_mills)
      VALUES ($1,$2,$3,$4,$5,$5,$6,$7,125,100,20,5,125)`, [id, `SOURCE-${id}`, variant, location, qty, reserved, occurredAt]);
  }

  async function transfer(qty: number) {
    return database.transaction(async (tx) => new InventoryLotService(tx).transferLots({
      productVariantId: 101, fromLocationId: 20, toLocationId: 30, qty,
      actorId: "integration-test", occurredAt, operationKey: `synthetic-transfer-${qty}`,
    }));
  }

  it("records each transfer layer without treating a destination as a new purchase quantity", async () => {
    await seedLot(101, 5); await seedLot(102, 10);
    await transfer(8);
    const edges = await pool.query("SELECT source_lot_id,output_lot_id,source_qty,output_qty,operation_kind,recorded_by FROM inventory.lot_cost_contributions ORDER BY source_lot_id");
    expect(edges.rows).toEqual([
      { source_lot_id: 101, output_lot_id: 1, source_qty: 5, output_qty: 5, operation_kind: "transfer", recorded_by: "integration-test" },
      { source_lot_id: 102, output_lot_id: 2, source_qty: 3, output_qty: 3, operation_kind: "transfer", recorded_by: "integration-test" },
    ]);
    const outputs = await pool.query("SELECT qty_on_hand,po_unit_cost_mills,packaging_cost_mills,landed_cost_mills,total_unit_cost_mills FROM inventory.inventory_lots WHERE warehouse_location_id=30 ORDER BY id");
    expect(outputs.rows).toEqual([5, 3].map((qty) => ({ qty_on_hand: qty, po_unit_cost_mills: "100", packaging_cost_mills: "20", landed_cost_mills: "5", total_unit_cost_mills: "125" })));
    expect((await pool.query("SELECT count(*)::integer AS count FROM inventory.lot_cost_origins")).rows[0].count).toBe(0);
    await expect(pool.query("UPDATE inventory.lot_cost_contributions SET source_qty=1")).rejects.toMatchObject({ code: "55000" });
  });

  it("rolls back source quantities and destination lots when contribution evidence fails", async () => {
    await seedLot(101, 5);
    await pool.query(`CREATE FUNCTION inventory.fail_test_contribution() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected contribution failure'; END $$;
      CREATE TRIGGER fail_test_contribution BEFORE INSERT ON inventory.lot_cost_contributions FOR EACH ROW EXECUTE FUNCTION inventory.fail_test_contribution()`);
    try {
      await expect(transfer(3)).rejects.toThrow("injected contribution failure");
      expect((await pool.query("SELECT id,qty_on_hand FROM inventory.inventory_lots ORDER BY id")).rows).toEqual([{ id: 101, qty_on_hand: 5 }]);
      expect((await pool.query("SELECT count(*)::integer AS count FROM inventory.lot_cost_contributions")).rows[0].count).toBe(0);
    } finally {
      await pool.query("DROP TRIGGER fail_test_contribution ON inventory.lot_cost_contributions");
      await pool.query("DROP FUNCTION inventory.fail_test_contribution()");
    }
  });

  it("waits before reading source costs and copies the cost committed by the preceding graph owner", async () => {
    await seedLot(101, 5);
    const writer = await pool.connect();
    let pending: Promise<void> | undefined;
    let transferBackendId = 0;
    try {
      await writer.query("BEGIN");
      await lockInventoryCostGraph(costEvidenceTransactionFromPg(writer));
      await writer.query("UPDATE inventory.inventory_lots SET po_unit_cost_mills=200,total_unit_cost_mills=225,unit_cost_mills=225 WHERE id=101");
      pending = database.transaction(async (tx) => {
        transferBackendId = Number((await tx.execute(sql`SELECT pg_backend_pid() AS id`)).rows[0].id);
        await new InventoryLotService(tx).transferLots({ productVariantId: 101, fromLocationId: 20, toLocationId: 30,
          qty: 3, actorId: "integration-test", occurredAt });
      });
      let observedWait = false;
      for (let attempt = 0; attempt < 100; attempt += 1) {
        if (transferBackendId) {
          observedWait = (await writer.query("SELECT EXISTS(SELECT 1 FROM pg_locks WHERE pid=$1 AND locktype='advisory' AND NOT granted) AS waiting", [transferBackendId])).rows[0].waiting;
          if (observedWait) break;
        }
        await new Promise((done) => setTimeout(done, 10));
      }
      expect(observedWait).toBe(true);
      await writer.query("COMMIT");
      await pending;
      expect((await pool.query("SELECT po_unit_cost_mills,total_unit_cost_mills FROM inventory.inventory_lots WHERE warehouse_location_id=30")).rows)
        .toEqual([{ po_unit_cost_mills: "200", total_unit_cost_mills: "225" }]);
    } finally {
      await writer.query("ROLLBACK");
      writer.release();
      await pending;
    }
  });

  it("records all standard build inputs for every remainder output layer and replays without duplicate edges", async () => {
    await seedLot(101, 2, 2); await seedLot(102, 3, 3);
    await pool.query(`
      INSERT INTO inventory.inventory_levels(product_variant_id,warehouse_location_id,variant_qty,reserved_qty) VALUES (101,20,5,5);
      INSERT INTO inventory.build_orders(id,system_number,recipe_id,recipe_code,recipe_version,recipe_type,
        output_product_id,output_units_per_variant,output_variant_id,output_qty_per_build,planned_builds,
        warehouse_id,output_location_id,status,idempotency_key,total_component_cost_mills)
        VALUES (10,'BUILD-SYNTHETIC',1,'RECIPE-SYNTHETIC',1,'assembly',95,1,105,4,1,1,30,'released','build-order-synthetic',0);
      INSERT INTO inventory.build_order_components(id,build_order_id,recipe_component_id,component_variant_id,
        component_product_id,component_units_per_variant,qty_per_build,planned_qty,source_location_id)
        VALUES (11,10,1,101,90,1,5,5,20);
      INSERT INTO inventory.build_component_reservations(build_order_component_id,inventory_lot_id,reserved_qty)
        VALUES (11,101,2),(11,102,3);
    `);
    const repository = new BuildExecutionRepository(database, {
      loadActiveBuildVariantFacts: async () => new Map([
        [101, { variantId: 101, productId: 90, unitsPerVariant: 1 }],
        [105, { variantId: 105, productId: 95, unitsPerVariant: 1 }],
      ]),
      normalizeBuildLotCosts, buildMillsToRoundedCents,
    });
    const command = { buildOrderId: 10, buildsCompleted: 1, idempotencyKey: "build-run-synthetic", actorId: "integration-test" };
    const result = await repository.executeOrder(command);
    expect(result).toMatchObject({ totalComponentCostMills: "625", outputQty: 4, alreadyPosted: false });
    const outputs = (await pool.query("SELECT id,qty_received FROM inventory.inventory_lots WHERE build_run_id=$1 ORDER BY id", [result.buildRunId])).rows;
    expect(outputs.map((output) => output.qty_received)).toEqual([1, 3]);
    const edges = (await pool.query("SELECT source_lot_id,output_lot_id,source_qty,output_qty,output_start_qty,operation_kind FROM inventory.lot_cost_contributions ORDER BY output_lot_id,source_lot_id")).rows;
    expect(edges).toEqual(outputs.flatMap((output, index) => [
      { source_lot_id: 101, output_lot_id: output.id, source_qty: 2, output_qty: 4, output_start_qty: index === 0 ? 0 : 1, operation_kind: "build" },
      { source_lot_id: 102, output_lot_id: output.id, source_qty: 3, output_qty: 4, output_start_qty: index === 0 ? 0 : 1, operation_kind: "build" },
    ]));
    expect((await pool.query("SELECT SUM(total_unit_cost_mills*qty_received)::text AS total FROM inventory.inventory_lots WHERE build_run_id=$1", [result.buildRunId])).rows[0].total).toBe("625");
    expect((await repository.executeOrder(command)).alreadyPosted).toBe(true);
    expect((await pool.query("SELECT count(*)::integer AS count FROM inventory.lot_cost_contributions")).rows[0].count).toBe(edges.length);
  });

  it.each(["break_pack", "assemble_pack", "component_build"] as const)("records canonical %s contributions for committed and surplus cost layers", async (operationType) => {
    await seedLot(101, 5, 5);
    await pool.query("INSERT INTO inventory.inventory_levels(product_variant_id,warehouse_location_id,variant_qty,reserved_qty) VALUES (101,20,5,5)");
    const writer = new PostgresCanonicalClaimInventoryRepository();
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      const input = {
        client, claimId: BigInt(9), claimOperationId: BigInt(10), operationKey: "synthetic-operation",
        resources: [{ claimResourceId: BigInt(11), inventoryLevelId: 1, warehouseLocationId: 20,
          sourceVariantId: 101, consumeQty: BigInt(5), lotAllocations: [{
            claimLotAllocationId: BigInt(12), inventoryLotId: 101, consumeQty: BigInt(5),
            unitCostMills: BigInt(125), poUnitCostMills: BigInt(100), packagingUnitCostMills: BigInt(20), landedUnitCostMills: BigInt(5),
          }] }],
        destinationVariantId: 105, outputLocationId: 30, outputQty: BigInt(4), committedOutputQty: BigInt(3),
        orderId: 70, orderItemId: 71, actor: "integration-test", reason: "synthetic evidence", occurredAt,
      };
      if (operationType === "component_build") await writer.executeBuildOperation({
        ...input, operationType, build: { buildOrderId: 10, buildRunId: 20, buildRunNumber: 1,
          buildSystemNumber: "BUILD-SYNTHETIC", components: [{ sourceVariantId: 101, buildOrderComponentId: 11 }] },
      });
      else await writer.executePackageOperation({ ...input, operationType });
      await client.query("COMMIT");
      const edges = (await pool.query("SELECT source_lot_id,source_qty,output_qty,output_start_qty,operation_kind FROM inventory.lot_cost_contributions ORDER BY output_lot_id")).rows;
      expect(edges).toHaveLength(3);
      expect(edges).toEqual(Array.from({ length: 3 }, (_, index) => ({ source_lot_id: 101, source_qty: 5, output_qty: 4, output_start_qty: [0, 1, 3][index], operation_kind: operationType === "component_build" ? "build" : operationType === "assemble_pack" ? "assembly" : "conversion" })));
      expect((await pool.query("SELECT SUM(total_unit_cost_mills*qty_received)::text AS total FROM inventory.inventory_lots WHERE warehouse_location_id=30")).rows[0].total).toBe("625");
    } finally {
      await client.query("ROLLBACK");
      client.release();
    }
  });
});
