import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { getTableConfig } from "drizzle-orm/pg-core";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import * as inventorySchema from "@shared/schema";

import {
  inventoryLevels,
  inventoryLots,
  productVariants,
  products,
  replenTasks,
  replenRules,
  warehouseLocations,
  warehouses,
} from "@shared/schema";
import { createQuantityLedgerTestContext, prepareQuantityLotCreationMetadata, type QuantityLedgerTestContext } from "../fixtures/quantity-ledger-database";
import { InventoryUseCases } from "../../application/inventory.use-cases";
import { createReplenishmentService } from "../../application/replenishment.use-cases";
import { createInventoryMethods } from "../../infrastructure/inventory.repository";
import { createInventoryLotService } from "../../lots.service";
import { PickingUseCases } from "../../../orders/picking.use-cases";

vi.mock("../../../../db", () => ({ pool: {} }));
const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const dbDescribe = databaseUrl && disposable ? describe : describe.skip;

dbDescribe("Replenishment canonical-claim safety / legacy compatibility", () => {
  let db: any;
  let context: QuantityLedgerTestContext;
  let legacyTask: Record<string, unknown>;

  beforeEach(async () => {
    context = await createQuantityLedgerTestContext(databaseUrl, disposable);
    await prepareQuantityLotCreationMetadata(context.pool);
    const ruleColumns = getTableConfig(replenRules).columns;
    await context.pool.query(`CREATE TABLE inventory.replen_rules (${ruleColumns.map(column => `"${column.name}" ${column.getSQLType()}`).join(",")})`);
    // Use the migration's real varchar(20) boundary, not an ORM-shaped table
    // that would silently inherit the fix and conceal a missing migration.
    const original = readFileSync(resolve(process.cwd(), "migrations/0002_concerned_darwin.sql"), "utf8")
      .match(/CREATE TABLE "replen_tasks" \([\s\S]*?\n\);/);
    if (!original) throw new Error("Replenishment base migration definition was not found");
    await context.pool.query(original[0].replace('CREATE TABLE "replen_tasks"', 'CREATE TABLE inventory."replen_tasks"'));
    await context.pool.query(readFileSync(resolve(process.cwd(), "migrations/077_replen_task_order_linkage.sql"), "utf8"));
    legacyTask = (await context.pool.query(`INSERT INTO inventory.replen_tasks
      (from_location_id,to_location_id,qty_target_units,status,triggered_by,notes)
      VALUES(100,100,1,'cancelled','legacy_reason','Preserve historical provenance') RETURNING *`)).rows[0];
    await context.pool.query(readFileSync(resolve(process.cwd(), "migrations/0700_replenishment_trigger_text.sql"), "utf8"));
    for (const column of ["variant_qty", "reserved_qty", "picked_qty", "packed_qty", "backorder_qty"]) {
      await context.pool.query(`ALTER TABLE inventory.inventory_levels ALTER COLUMN ${column} SET DEFAULT 0`);
    }
    // The isolated fixture deliberately remains before the quantity opening.
    // Identity defaults support the original workflow seed below; no production
    // source or shared named-schema test data is read or reset.
    for (const table of ["warehouse.warehouses", "warehouse.warehouse_locations", "catalog.products", "catalog.product_variants"]) {
      await context.pool.query(`ALTER TABLE ${table} ALTER COLUMN id SET NOT NULL;
        ALTER TABLE ${table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2000)`);
    }
    db = drizzle(context.pool, { schema: inventorySchema });
  }, 30_000);

  afterEach(async () => {
    vi.restoreAllMocks();
    await context?.close();
  });

  it("preserves history, defaults and nullability when the migration is reapplied", async () => {
    await context.pool.query(readFileSync(resolve(process.cwd(), "migrations/0700_replenishment_trigger_text.sql"), "utf8"));
    expect((await context.pool.query("SELECT * FROM inventory.replen_tasks WHERE id=$1", [legacyTask.id])).rows)
      .toEqual([legacyTask]);
    expect((await context.pool.query(`SELECT data_type,character_maximum_length,is_nullable
      FROM information_schema.columns WHERE table_schema='inventory' AND table_name='replen_tasks' AND column_name='triggered_by'`)).rows)
      .toEqual([{ data_type: "text", character_maximum_length: null, is_nullable: "NO" }]);
    expect((await context.pool.query(`INSERT INTO inventory.replen_tasks(from_location_id,to_location_id,qty_target_units)
      VALUES(100,100,1) RETURNING triggered_by`)).rows).toEqual([{ triggered_by: "min_max" }]);
    await expect(context.pool.query(`INSERT INTO inventory.replen_tasks(from_location_id,to_location_id,qty_target_units,triggered_by)
      VALUES(100,100,1,NULL)`)).rejects.toMatchObject({ code: "23502" });
  });

  it("persists a long future reason intact and reuses one task across concurrent requests and retry", async () => {
    const [destination] = await db.insert(warehouseLocations).values({ warehouseId: 1, code: "LONG-REASON", name: "Destination",
      locationType: "pick", isActive: 1, isPickable: 1 }).returning();
    const replenishment = createReplenishmentService(db, {} as any);
    vi.spyOn(replenishment, "checkReplenNeeded").mockResolvedValue({
      needed: true, stockout: false, sourceLocationId: 100, sourceLocationCode: "PICK",
      sourceVariantId: 101, sourceVariantSku: "P5", sourceVariantName: "Pack", pickVariantId: 101,
      qtySourceUnits: 1, qtyTargetUnits: 1, replenMethod: "full_case", executionMode: "queue",
      taskNotes: "Queued movement", triggerValue: 1, autoReplen: 0, evaluatedQty: 0,
    });
    const reason = "future_workflow:仓库:".repeat(1000);
    const input = Object.freeze({ triggeredBy: reason });
    const results = await Promise.all([
      replenishment.createAndExecuteReplen(101, destination.id, "system:test", input),
      replenishment.createAndExecuteReplen(101, destination.id, "system:test", input),
    ]);
    const replay = await replenishment.createAndExecuteReplen(101, destination.id, "system:test", input);
    expect(results[0]?.task.id).toBe(results[1]?.task.id);
    expect(replay?.task.id).toBe(results[0]?.task.id);
    expect((await context.pool.query("SELECT triggered_by,status FROM inventory.replen_tasks WHERE to_location_id=$1", [destination.id])).rows)
      .toEqual([{ triggered_by: reason, status: "pending" }]);
    expect(input.triggeredBy).toBe(reason);
  });

  it.each(["existing task", "picker shortage"] as const)("completes an exact case break without consuming reserved stock: %s", async (entryPoint) => {
    expect((await context.pool.query("SELECT * FROM inventory.quantity_ledger_opening")).rows).toEqual([]);
    const executionAt = new Date("2026-09-03T13:15:30.000Z");
    const [warehouse] = await db.insert(warehouses).values({
      code: "RPL-CLAIM",
      name: "Replen claim safety",
      isActive: 1,
    }).returning();
    const [sourceLocation] = await db.insert(warehouseLocations).values({
      warehouseId: warehouse.id,
      code: "RPL-CASE-01",
      name: "RPL-CASE-01",
      locationType: "pick",
      zone: "R",
      isActive: 1,
      isPickable: 1,
    }).returning();
    const [pickLocation] = await db.insert(warehouseLocations).values({
      warehouseId: warehouse.id,
      code: "RPL-PICK-01",
      name: "RPL-PICK-01",
      locationType: "pick",
      zone: "R",
      isActive: 1,
      isPickable: 1,
    }).returning();
    const [product] = await db.insert(products).values({
      name: "Replenishment claim safety product",
      baseUnit: "piece",
      inventoryType: "inventory",
    }).returning();
    const [sourceVariant] = await db.insert(productVariants).values({
      productId: product.id,
      name: "Case of 10",
      sku: "RPL-CLAIM-C10",
      unitsPerVariant: 10,
      hierarchyLevel: 1,
      isActive: true,
    }).returning();
    const [pickVariant] = await db.insert(productVariants).values({
      productId: product.id,
      name: "Each",
      sku: "RPL-CLAIM-EA",
      unitsPerVariant: 1,
      hierarchyLevel: 0,
      isActive: true,
    }).returning();
    await db.insert(inventoryLevels).values({
      warehouseLocationId: sourceLocation.id,
      productVariantId: sourceVariant.id,
      variantQty: 2,
      reservedQty: 1,
      pickedQty: 0,
      packedQty: 0,
      backorderQty: 0,
    });
    await db.insert(inventoryLots).values({
      lotNumber: "RPL-CLAIM-SOURCE-01",
      productVariantId: sourceVariant.id,
      warehouseLocationId: sourceLocation.id,
      unitCostCents: 500,
      poUnitCostCents: "490",
      packagingCostCents: "10",
      landedCostCents: "0",
      totalUnitCostCents: "500",
      unitCostMills: 50_000,
      poUnitCostMills: 49_000,
      packagingCostMills: 1_000,
      landedCostMills: 0,
      totalUnitCostMills: 50_000,
      qtyReceived: 2,
      qtyOnHand: 2,
      qtyReserved: 1,
      qtyPicked: 0,
      receivedAt: new Date("2026-09-03T12:00:00.000Z"),
      status: "active",
      costProvisional: 0,
      costSource: "po",
    });
    const taskInput = {
      fromLocationId: sourceLocation.id,
      toLocationId: pickLocation.id,
      warehouseId: warehouse.id,
      productId: product.id,
      sourceProductVariantId: sourceVariant.id,
      pickProductVariantId: pickVariant.id,
      qtySourceUnits: 1,
      qtyTargetUnits: 10,
      qtyCompleted: 0,
      status: "pending",
      executionMode: "inline",
      replenMethod: "case_break",
      autoReplen: 1,
      priority: 1,
      triggeredBy: "integration_test",
    };

    const inventory = new InventoryUseCases(
      db,
      createInventoryMethods(db),
      createInventoryLotService(db),
    );
    const replenishment = createReplenishmentService(db, inventory, () => executionAt);

    let task: typeof replenTasks.$inferSelect;
    if (entryPoint === "existing task") {
      [task] = await db.insert(replenTasks).values(taskInput).returning();
      await expect(replenishment.executeTask(task.id, "system:test"))
        .resolves.toEqual({ moved: 10 });
    } else {
      await context.pool.query(`INSERT INTO wms.orders(id,warehouse_id,warehouse_status,on_hold) VALUES(10000,$1,'picking',0);
      `, [warehouse.id]);
      await context.pool.query(`INSERT INTO wms.order_items(id,order_id,product_id,sku,quantity,picked_quantity,status)
        VALUES(10000,10000,$1,$2,1,0,'pending')`, [pickVariant.id, pickVariant.sku]);
      // Only source discovery is controlled; task insertion, case break, FIFO
      // costs and the subsequent pick all use the real application and database.
      vi.spyOn(replenishment, "checkReplenNeeded").mockResolvedValue({
        needed: true, stockout: false, sourceLocationId: sourceLocation.id,
        sourceLocationCode: sourceLocation.code, sourceVariantId: sourceVariant.id,
        sourceVariantSku: sourceVariant.sku, sourceVariantName: sourceVariant.name,
        pickVariantId: pickVariant.id, qtySourceUnits: 1, qtyTargetUnits: 10,
        replenMethod: "case_break", executionMode: "inline", taskNotes: "Empty pick bin",
        triggerValue: 0, autoReplen: 1, evaluatedQty: 0,
      });
      const picker = new PickingUseCases(db, inventory as any, replenishment as any, {
        getProductVariantBySku: async () => pickVariant,
        getInventoryLevelsByProductVariantId: () => inventory.getLevelsByVariant(pickVariant.id),
        getAllWarehouseLocations: async () => [sourceLocation, pickLocation],
        getOrderById: async () => ({ id: 10000, orderNumber: "TEST-SHORTAGE", warehouseId: warehouse.id }),
      } as any);
      const item = { id: 10000, orderId: 10000, productId: pickVariant.id, sku: pickVariant.sku,
        quantity: 1, pickedQuantity: 0, location: pickLocation.code, requiresShipping: 1 };
      const result = await (picker as any)._deductInventory(item, item, {
        quantity: 1, expectedPriorPickedQuantity: 0, pickMethod: "scan", userId: "system:test", warehouseId: warehouse.id,
      });
      expect(result).toMatchObject({ success: true, systemQtyAfter: 9 });
      task = result.prePickReplen.task;
      expect(task).toMatchObject({ triggeredBy: "pick_shortage_case_break", status: "completed", orderItemId: 10000 });
      const costs = await context.pool.query("SELECT qty,total_cost_mills FROM oms.order_item_costs WHERE order_item_id=10000");
      expect(costs.rows).toEqual([{ qty: 1, total_cost_mills: "5000" }]);
      const picks = await context.pool.query("SELECT variant_qty_delta FROM inventory.inventory_transactions WHERE order_item_id=10000 AND transaction_type='pick'");
      expect(picks.rows).toEqual([{ variant_qty_delta: -1 }]);
    }
    const remainingTargetQty = entryPoint === "picker shortage" ? 9 : 10;

    const balances = await db.execute(sql`
      SELECT product_variant_id, warehouse_location_id, variant_qty, reserved_qty
      FROM inventory.inventory_levels
      WHERE (product_variant_id = ${sourceVariant.id} AND warehouse_location_id = ${sourceLocation.id})
         OR (product_variant_id = ${pickVariant.id} AND warehouse_location_id = ${pickLocation.id})
      ORDER BY product_variant_id, warehouse_location_id
    `);
    expect(balances.rows).toEqual(expect.arrayContaining([
      expect.objectContaining({
        product_variant_id: sourceVariant.id,
        warehouse_location_id: sourceLocation.id,
        variant_qty: 1,
        reserved_qty: 1,
      }),
      expect.objectContaining({
        product_variant_id: pickVariant.id,
        warehouse_location_id: pickLocation.id,
        variant_qty: remainingTargetQty,
        reserved_qty: 0,
      }),
    ]));

    const lotBalances = await db.execute(sql`
      SELECT product_variant_id,
             SUM(qty_on_hand)::integer AS qty_on_hand,
             SUM(qty_reserved)::integer AS qty_reserved,
             SUM(qty_on_hand * total_unit_cost_mills)::bigint AS value_mills
      FROM inventory.inventory_lots
      WHERE (product_variant_id = ${sourceVariant.id} AND warehouse_location_id = ${sourceLocation.id})
         OR (product_variant_id = ${pickVariant.id} AND warehouse_location_id = ${pickLocation.id})
      GROUP BY product_variant_id
      ORDER BY product_variant_id
    `);
    expect(lotBalances.rows).toEqual(expect.arrayContaining([
      expect.objectContaining({
        product_variant_id: sourceVariant.id,
        qty_on_hand: 1,
        qty_reserved: 1,
        value_mills: "50000",
      }),
      expect.objectContaining({
        product_variant_id: pickVariant.id,
        qty_on_hand: remainingTargetQty,
        qty_reserved: 0,
        value_mills: String(remainingTargetQty * 5000),
      }),
    ]));

    const taskReadback = await db.execute(sql`
      SELECT status, qty_completed, EXTRACT(EPOCH FROM completed_at AT TIME ZONE 'UTC')::double precision AS completed_epoch
      FROM inventory.replen_tasks
      WHERE id = ${task.id}
    `);
    expect(taskReadback.rows[0]).toMatchObject({
      status: "completed",
      qty_completed: 10,
      completed_epoch: executionAt.getTime() / 1000,
    });

    const outputLotReadback = await db.execute(sql`
      SELECT EXTRACT(EPOCH FROM received_at)::double precision AS received_epoch
      FROM inventory.inventory_lots
      WHERE product_variant_id = ${pickVariant.id}
        AND warehouse_location_id = ${pickLocation.id}
      ORDER BY id
    `);
    expect(outputLotReadback.rows).not.toHaveLength(0);
    expect(outputLotReadback.rows).toEqual(
      expect.arrayContaining([expect.objectContaining({ received_epoch: executionAt.getTime() / 1000 })]),
    );

    const auditRows = await db.execute(sql`
      SELECT product_variant_id, transaction_type, reference_type, reference_id
      FROM inventory.inventory_transactions
      WHERE reference_type = 'replenishment_task' AND reference_id = ${String(task.id)}
      ORDER BY id
    `);
    expect(auditRows.rows).toEqual([
      expect.objectContaining({ product_variant_id: sourceVariant.id, transaction_type: "break" }),
      expect.objectContaining({ product_variant_id: pickVariant.id, transaction_type: "break" }),
    ]);
  });
});
