import { SQL, getTableColumns, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { getTableConfig, PgDialect, type PgTable } from "drizzle-orm/pg-core";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import * as schema from "@shared/schema";
import { createInventoryCutoverTestDatabase, type InventoryCutoverTestDatabase } from "../../../inventory/__tests__/fixtures/inventory-cutover-database";
import { releaseLineItemFromHold } from "../../line-item-hold";
import { releaseWmsOrderHold, type OrderHoldReleaseTransaction } from "../../order-hold-release";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const describeDatabase = databaseUrl && disposable ? describe.sequential : describe.skip;
const quote = (name: string) => `"${name.replaceAll('"', '""')}"`;
const NOW = new Date("2026-10-01T12:00:00Z");

// Current-column read fixture for the tables the commands read through
// Drizzle (same approach as order-list.integration.test.ts). Shipments carry
// only the columns the release touches. No production records are used.
function readFixture(table: PgTable): string {
  const config = getTableConfig(table);
  const columns = Object.values(getTableColumns(table)).map(column => {
    let definition = `${quote(column.name)} ${column.getSQLType()}`;
    if (column.primary) return `${definition} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    if (column.default !== undefined) {
      const literal = column.default instanceof SQL
        ? new PgDialect().sqlToQuery(column.default).sql
        : typeof column.default === "string" ? `'${column.default.replaceAll("'", "''")}'` : String(column.default);
      definition += ` DEFAULT ${literal}`;
    }
    return definition + (column.notNull ? " NOT NULL" : "");
  });
  return `CREATE TABLE ${quote(config.schema!)}.${quote(config.name)} (${columns.join(",")});`;
}

const fixture = `CREATE SCHEMA wms;
  ${readFixture(schema.wmsOrders)}
  ${readFixture(schema.wmsOrderItems)}
  CREATE TABLE wms.outbound_shipments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES wms.orders(id),
    status text NOT NULL DEFAULT 'planned',
    held boolean NOT NULL DEFAULT false,
    held_at timestamp,
    on_hold_reason varchar(200),
    updated_at timestamp
  );
  CREATE TABLE wms.outbound_shipment_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id integer NOT NULL REFERENCES wms.outbound_shipments(id),
    order_item_id integer NOT NULL REFERENCES wms.order_items(id)
  );
  CREATE TABLE wms.release_follow_ups (order_id integer NOT NULL);
`;

describeDatabase("hold release PostgreSQL guarantees", () => {
  let database: InventoryCutoverTestDatabase;
  let orm: ReturnType<typeof drizzle<typeof schema>>;

  beforeAll(async () => {
    database = await createInventoryCutoverTestDatabase(databaseUrl, disposable, fixture);
    orm = drizzle(database.pool, { schema });
  });
  beforeEach(async () => {
    await database.pool.query(
      "TRUNCATE wms.release_follow_ups, wms.outbound_shipment_items, wms.outbound_shipments, wms.order_items, wms.orders RESTART IDENTITY CASCADE",
    );
  });
  afterAll(async () => { await database?.close(); });

  async function seedOrder(values: Partial<typeof schema.wmsOrders.$inferInsert> = {}) {
    const [order] = await orm.insert(schema.wmsOrders).values({
      orderNumber: "#63570", customerName: "Test customer", warehouseStatus: "ready", onHold: 0, ...values,
    }).returning();
    return order;
  }

  async function seedHeldLine(orderId: number) {
    const [line] = await orm.insert(schema.wmsOrderItems).values({
      orderId, sku: "SLV-100", name: "Sleeves", quantity: 2, onHold: true, holdReason: "Awaiting restock",
    }).returning();
    const shipment = await database.pool.query(
      "INSERT INTO wms.outbound_shipments (order_id, held, held_at, on_hold_reason) VALUES ($1, true, $2, 'Awaiting restock') RETURNING id",
      [orderId, new Date("2026-09-30T08:00:00Z")],
    );
    const shipmentId = Number(shipment.rows[0].id);
    await database.pool.query("INSERT INTO wms.outbound_shipment_items (shipment_id, order_item_id) VALUES ($1, $2)", [shipmentId, line.id]);
    return { line, shipmentId };
  }

  const recordFollowUp = (orderId: number) => async (tx: OrderHoldReleaseTransaction) => {
    await tx.execute(sql`INSERT INTO wms.release_follow_ups (order_id) VALUES (${orderId})`);
  };
  const followUps = async () =>
    (await database.pool.query("SELECT order_id FROM wms.release_follow_ups ORDER BY order_id")).rows.map(row => row.order_id);
  // Naive timestamps are read as text: node-pg would parse them in the
  // machine's local zone.
  const orderRow = async (id: number) =>
    (await database.pool.query(
      "SELECT on_hold, held_at::text AS held_at, updated_at::text AS updated_at FROM wms.orders WHERE id = $1",
      [id],
    )).rows[0];
  const lineState = async (lineId: number, shipmentId: number) => ({
    line: (await database.pool.query("SELECT on_hold, hold_reason FROM wms.order_items WHERE id = $1", [lineId])).rows[0],
    shipment: (await database.pool.query(
      "SELECT held, held_at::text AS held_at, on_hold_reason, updated_at IS NOT NULL AS touched FROM wms.outbound_shipments WHERE id = $1",
      [shipmentId],
    )).rows[0],
  });

  // Proves the command really waited on the row lock: commit the blocker only
  // once Postgres reports a backend in this database waiting for a lock.
  async function waitForLockWait(): Promise<void> {
    for (let attempt = 0; attempt < 100; attempt += 1) {
      const { rows } = await database.pool.query(
        "SELECT count(*)::int AS waiting FROM pg_stat_activity WHERE datname = current_database() AND wait_event_type = 'Lock'",
      );
      if (rows[0].waiting > 0) return;
      await new Promise(resolve => setTimeout(resolve, 50));
    }
    throw new Error("the release never waited on the row lock");
  }

  describe("releaseWmsOrderHold", () => {
    it("clears the hold and commits the follow-up with it", async () => {
      const order = await seedOrder({ onHold: 1, heldAt: new Date("2026-09-30T08:00:00Z") });

      const result = await releaseWmsOrderHold(orm, { orderId: order.id, now: NOW, followUp: recordFollowUp(order.id) });

      expect(result.outcome).toBe("released");
      expect(result.before).toMatchObject({ onHold: 1, warehouseStatus: "ready" });
      // Drizzle writes the injected clock as UTC; the column keeps that wall time.
      expect(await orderRow(order.id)).toEqual({ on_hold: 0, held_at: null, updated_at: "2026-10-01 12:00:00" });
      expect(await followUps()).toEqual([order.id]);
    });

    it("rolls the release back when its follow-up fails", async () => {
      const order = await seedOrder({ onHold: 1 });
      const failing = async (tx: OrderHoldReleaseTransaction) => {
        await recordFollowUp(order.id)(tx);
        throw new Error("retry queue unavailable");
      };

      await expect(releaseWmsOrderHold(orm, { orderId: order.id, now: NOW, followUp: failing })).rejects.toThrow("retry queue unavailable");

      expect((await orderRow(order.id)).on_hold).toBe(1);
      expect(await followUps()).toEqual([]);
    });

    it("changes nothing for an order that is not held, one that already shipped, or one that does not exist", async () => {
      const open = await seedOrder();
      const shipped = await seedOrder({ onHold: 1, warehouseStatus: "shipped" });
      const openBefore = await orderRow(open.id);

      expect((await releaseWmsOrderHold(orm, { orderId: open.id, now: NOW, followUp: recordFollowUp(open.id) })).outcome).toBe("not_held");
      expect((await releaseWmsOrderHold(orm, { orderId: shipped.id, now: NOW, followUp: recordFollowUp(shipped.id) })).outcome).toBe("order_terminal");
      expect((await releaseWmsOrderHold(orm, { orderId: 999_999, now: NOW })).outcome).toBe("not_found");

      expect(await orderRow(open.id)).toEqual(openBefore);
      expect((await orderRow(shipped.id)).on_hold).toBe(1);
      expect(await followUps()).toEqual([]);
    });

    it("lets exactly one of two concurrent releases act", async () => {
      const order = await seedOrder({ onHold: 1 });

      const results = await Promise.all([1, 2].map(() =>
        releaseWmsOrderHold(orm, { orderId: order.id, now: NOW, followUp: recordFollowUp(order.id) })));

      expect(results.map(result => result.outcome).sort()).toEqual(["not_held", "released"]);
      expect(await followUps()).toEqual([order.id]);
    });

    it("waits for a concurrent writer and decides on what it committed", async () => {
      const order = await seedOrder({ onHold: 1 });
      const blocker = await database.pool.connect();
      try {
        await blocker.query("BEGIN");
        await blocker.query("UPDATE wms.orders SET on_hold = 0, held_at = NULL WHERE id = $1", [order.id]);
        const pending = releaseWmsOrderHold(orm, { orderId: order.id, now: NOW, followUp: recordFollowUp(order.id) });
        await waitForLockWait();
        await blocker.query("COMMIT");
        expect((await pending).outcome).toBe("not_held");
      } finally {
        blocker.release();
      }
      expect(await followUps()).toEqual([]);
    });
  });

  describe("releaseLineItemFromHold", () => {
    it("releases the line and un-holds its shipment together", async () => {
      const order = await seedOrder({ warehouseStatus: "partially_shipped" });
      const { line, shipmentId } = await seedHeldLine(order.id);

      const result = await releaseLineItemFromHold(orm, { wmsOrderId: order.id, orderItemId: line.id, now: NOW });

      expect(result).toEqual({ outcome: "released", heldShipmentId: shipmentId, orderStatus: "partially_shipped", lineWasHeld: true });
      expect(await lineState(line.id, shipmentId)).toEqual({
        line: { on_hold: false, hold_reason: null },
        shipment: { held: false, held_at: null, on_hold_reason: null, touched: true },
      });
    });

    it("refuses while the whole order is held, leaving the line and its shipment held", async () => {
      const order = await seedOrder({ onHold: 1 });
      const { line, shipmentId } = await seedHeldLine(order.id);
      const before = await lineState(line.id, shipmentId);

      const result = await releaseLineItemFromHold(orm, { wmsOrderId: order.id, orderItemId: line.id, now: NOW });

      expect(result.outcome).toBe("order_on_hold");
      expect(await lineState(line.id, shipmentId)).toEqual(before);
    });

    it("lets exactly one of two concurrent line releases act", async () => {
      const order = await seedOrder();
      const { line } = await seedHeldLine(order.id);

      const results = await Promise.all([1, 2].map(() =>
        releaseLineItemFromHold(orm, { wmsOrderId: order.id, orderItemId: line.id, now: NOW })));

      expect(results.map(result => result.outcome).sort()).toEqual(["not_held", "released"]);
    });

    it("sees a whole-order hold that commits while it waits for the order lock", async () => {
      const order = await seedOrder();
      const { line, shipmentId } = await seedHeldLine(order.id);
      const blocker = await database.pool.connect();
      try {
        await blocker.query("BEGIN");
        await blocker.query("UPDATE wms.orders SET on_hold = 1, held_at = now() WHERE id = $1", [order.id]);
        const pending = releaseLineItemFromHold(orm, { wmsOrderId: order.id, orderItemId: line.id, now: NOW });
        await waitForLockWait();
        await blocker.query("COMMIT");
        expect((await pending).outcome).toBe("order_on_hold");
      } finally {
        blocker.release();
      }
      expect((await lineState(line.id, shipmentId)).shipment.held).toBe(true);
    });
  });
});
