/** Reduced query fixture for the OMS cutover reader, not migration/trigger proof.
 * Keep the queried receipt and latest-attempt types aligned with migration 0593.
 * Unrelated provider/WMS foreign keys are intentionally outside this fixture.
 */
export const cutoverReceiptSchemaFixtureSql = `
CREATE TABLE oms.channel_fulfillment_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  processing_status varchar(30) NOT NULL DEFAULT 'pending',
  source_provider varchar(40), source_channel_id integer,
  source_order_id varchar(200), source_fulfillment_id varchar(200),
  oms_order_id bigint, physical_shipment_id bigint,
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  error_code varchar(100), error_message text,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  lease_token varchar(100), lease_expires_at timestamptz,
  CONSTRAINT cutover_receipt_status_check CHECK (
    processing_status IN ('pending','processing','processed','ignored','review')
  )
);
CREATE TABLE oms.channel_fulfillment_receipt_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id bigint NOT NULL REFERENCES oms.channel_fulfillment_receipts(id),
  attempt_number integer NOT NULL CHECK (attempt_number > 0),
  outcome varchar(30) NOT NULL CHECK (outcome IN ('processed','ignored','review','lease_expired')),
  error_code varchar(100), error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (receipt_id, attempt_number)
);
`;
