import { cutoverShipmentSchemaFixtureSql } from "./inventory-cutover-shipment-schema.fixture";

/** Reduced owner-query fixture. Actual 0640/0642/0647/0649/233 DDL is applied by the suite. */
export const reconstructionDatabaseFixtureSql = `
CREATE SCHEMA inventory; CREATE SCHEMA wms; CREATE SCHEMA oms; CREATE SCHEMA warehouse; CREATE SCHEMA catalog;
CREATE TABLE warehouse.warehouses(id integer PRIMARY KEY);
CREATE TABLE warehouse.warehouse_locations(id integer PRIMARY KEY, warehouse_id integer,is_active integer DEFAULT 1,is_pickable integer DEFAULT 1,cycle_count_freeze_id integer);
CREATE TABLE catalog.product_variants(id integer PRIMARY KEY,product_id integer,sku text,is_active boolean,requires_shipping boolean,track_inventory boolean,sales_eligibility text);
CREATE TABLE wms.orders(id integer PRIMARY KEY,warehouse_id integer,warehouse_status text,on_hold integer,channel_id integer,source text,external_order_id text,oms_fulfillment_order_id text,fulfillment_partition_key text);
CREATE TABLE wms.order_items(id integer PRIMARY KEY,order_id integer,oms_order_line_id bigint,source_item_id text,sku text,product_id integer,quantity integer,picked_quantity integer,fulfilled_quantity integer,status text,on_hold boolean,requires_shipping integer,location text,short_reason text);
${cutoverShipmentSchemaFixtureSql}
CREATE TABLE wms.order_build_demands(id integer PRIMARY KEY,order_id integer,order_item_id integer,target_variant_id integer,root_build_order_id integer,status text,requested_qty integer,promised_qty integer);
CREATE TABLE oms.oms_orders(id bigint PRIMARY KEY,status text);
CREATE TABLE oms.oms_order_lines(id bigint PRIMARY KEY,order_id bigint,product_variant_id integer,sku text,requires_shipping boolean,quantity integer,authority_fulfillable_quantity integer,wms_materialized_quantity integer,authorization_status text);
CREATE TABLE oms.channel_fulfillment_receipts(id integer PRIMARY KEY,processing_status text);
CREATE TABLE oms.order_item_costs(id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY,order_id integer,order_item_id integer,inventory_lot_id integer,product_variant_id integer,qty integer,unit_cost_mills bigint,total_cost_mills bigint,created_at timestamptz,unit_cost_cents bigint,total_cost_cents bigint);
ALTER TABLE wms.order_items ADD COLUMN picked_at timestamptz;
CREATE TABLE inventory.availability_runtime_authority(singleton_key boolean PRIMARY KEY,authority text,activation_run_id bigint,revision bigint);
CREATE TABLE inventory.transformation_model_heads(product_id integer PRIMARY KEY);
CREATE TABLE inventory.availability_activation_runs(id bigint PRIMARY KEY);
CREATE TABLE inventory.inventory_levels(id integer PRIMARY KEY,warehouse_location_id integer,product_variant_id integer,variant_qty integer,reserved_qty integer,picked_qty integer,packed_qty integer,backorder_qty integer DEFAULT 0,updated_at timestamptz);
CREATE TABLE inventory.inventory_lots(id integer PRIMARY KEY,warehouse_location_id integer,product_variant_id integer,qty_on_hand integer,qty_reserved integer,qty_picked integer,status text,received_at timestamptz,
 unit_cost_mills bigint,po_unit_cost_mills bigint,packaging_cost_mills bigint,landed_cost_mills bigint,total_unit_cost_mills bigint,
 unit_cost_cents bigint DEFAULT 0,po_unit_cost_cents bigint DEFAULT 0,packaging_cost_cents bigint DEFAULT 0,landed_cost_cents bigint DEFAULT 0,total_unit_cost_cents bigint DEFAULT 0);
CREATE TABLE inventory.inventory_transactions(id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,order_id integer,order_item_id integer,product_variant_id integer,to_location_id integer,from_location_id integer,
 transaction_type text,variant_qty_delta integer,variant_qty_before integer,variant_qty_after integer,reserved_qty_delta integer,source_state text,target_state text,reference_type text,reference_id text,
 user_id text,notes text,voided_at timestamptz,created_at timestamptz DEFAULT now(),unit_cost_cents bigint,inventory_lot_id integer);
CREATE TABLE inventory.build_orders(id integer PRIMARY KEY,status text,warehouse_id integer);
CREATE TABLE inventory.build_order_components(id integer PRIMARY KEY,build_order_id integer,component_variant_id integer,source_location_id integer);
CREATE TABLE inventory.build_component_reservations(id integer PRIMARY KEY,build_order_component_id integer,inventory_lot_id integer,reserved_qty integer,consumed_qty integer,released_qty integer,reservation_owner text,availability_claim_id bigint,availability_claim_lot_allocation_id bigint);
-- Only assertion shape is substituted here. Real global admission races are
-- covered by the admission owner suite, not represented by this query fixture.
CREATE FUNCTION inventory.assert_cutover_admission_fence_owner() RETURNS bigint LANGUAGE plpgsql AS $$
BEGIN IF current_setting('test.cutover_admitted',true) IS DISTINCT FROM 'yes' THEN RAISE EXCEPTION 'exclusive fence required'; END IF; RETURN 1; END $$;
`;
export const reconstructionDatabaseSeedSql = `
INSERT INTO warehouse.warehouses VALUES(1); INSERT INTO warehouse.warehouse_locations(id,warehouse_id) VALUES(100,1);
INSERT INTO catalog.product_variants VALUES(101,20,'P5',true,true,true,'sellable');
INSERT INTO wms.orders VALUES(1,1,'ready',0,36,'shopify','example-1','fo-1','default');
INSERT INTO wms.order_items(id,order_id,oms_order_line_id,source_item_id,sku,product_id,quantity,picked_quantity,fulfilled_quantity,status,on_hold,requires_shipping,location,short_reason) VALUES(11,1,11,'source-11','P5',101,6,2,0,'pending',false,1,'PICK',NULL);
INSERT INTO inventory.availability_activation_runs VALUES(1);
INSERT INTO inventory.availability_runtime_authority VALUES(true,'canonical',1,2);
INSERT INTO inventory.transformation_model_heads VALUES(20);
INSERT INTO inventory.inventory_levels(id,warehouse_location_id,product_variant_id,variant_qty,reserved_qty,picked_qty,packed_qty) VALUES(10,100,101,20,3,2,0);
INSERT INTO inventory.inventory_lots(id,warehouse_location_id,product_variant_id,qty_on_hand,qty_reserved,qty_picked,status,received_at,unit_cost_mills,po_unit_cost_mills,packaging_cost_mills,landed_cost_mills,total_unit_cost_mills)
 VALUES(4,100,101,20,3,2,'active','2026-09-01T00:00:00Z',9007199254740995,9007199254740995,0,0,9007199254740995);
INSERT INTO inventory.inventory_transactions(order_id,order_item_id,product_variant_id,to_location_id,from_location_id,transaction_type,variant_qty_delta,reserved_qty_delta,source_state,target_state)
 VALUES(1,11,101,100,NULL,'reserve',0,5,'on_hand','committed'),(1,11,101,NULL,100,'pick',-2,-2,'on_hand','picked');
INSERT INTO oms.order_item_costs(id,order_id,order_item_id,inventory_lot_id,product_variant_id,qty,unit_cost_mills,total_cost_mills,created_at) VALUES(9,1,11,4,101,2,9007199254740995,18014398509481990,'2026-09-06T12:00:00Z');
`;
