import type { InsertAuthPermission, InsertAdjustmentReason } from "@shared/schema";

export const DEFAULT_ADJUSTMENT_REASONS: InsertAdjustmentReason[] = [
  { code: "PO_RECEIVED", name: "PO Received", description: "Inventory received from purchase order", transactionType: "receipt", requiresNote: 0, sortOrder: 10 },
  { code: "RMA_RETURN", name: "RMA Return", description: "Customer return received", transactionType: "receipt", requiresNote: 1, sortOrder: 20 },
  { code: "CYCLE_COUNT", name: "Cycle Count", description: "Variance found during cycle count", transactionType: "adjustment", requiresNote: 0, sortOrder: 30 },
  { code: "DAMAGED", name: "Damaged", description: "Product damaged and removed from inventory", transactionType: "adjustment", requiresNote: 1, sortOrder: 40 },
  { code: "SHRINKAGE", name: "Shrinkage", description: "Inventory loss (theft, miscount)", transactionType: "adjustment", requiresNote: 1, sortOrder: 50 },
  { code: "FOUND", name: "Found Stock", description: "Additional stock found during audit", transactionType: "adjustment", requiresNote: 0, sortOrder: 60 },
  { code: "EXPIRED", name: "Expired", description: "Product expired and disposed", transactionType: "adjustment", requiresNote: 0, sortOrder: 70 },
  { code: "SAMPLE", name: "Sample", description: "Product removed as sample", transactionType: "adjustment", requiresNote: 0, sortOrder: 80 },
  { code: "DONATION", name: "Donation", description: "Product donated", transactionType: "adjustment", requiresNote: 0, sortOrder: 90 },
  { code: "REPLENISHMENT", name: "Replenishment", description: "Moved from bulk to pick location", transactionType: "replenish", requiresNote: 0, sortOrder: 100 },
  { code: "RELOCATION", name: "Relocation", description: "Moved to different bin", transactionType: "transfer", requiresNote: 0, sortOrder: 110 },
  { code: "MISPLACED", name: "Misplaced", description: "Found in wrong location", transactionType: "adjustment", requiresNote: 1, sortOrder: 120 },
  { code: "RECEIVING_ERROR", name: "Receiving Error", description: "Variance due to incorrect receiving", transactionType: "adjustment", requiresNote: 1, sortOrder: 130 },
  { code: "PICKING_ERROR", name: "Picking Error", description: "Variance due to incorrect pick", transactionType: "adjustment", requiresNote: 1, sortOrder: 140 },
  { code: "WITHIN_TOLERANCE", name: "Within Tolerance", description: "Small variance auto-approved within tolerance", transactionType: "adjustment", requiresNote: 0, sortOrder: 150 },
];

export const DEFAULT_PERMISSIONS: InsertAuthPermission[] = [
  { resource: "dashboard", action: "view", description: "View dashboard and analytics", category: "dashboard" },
  { resource: "inventory", action: "view", description: "View inventory levels and items", category: "inventory" },
  { resource: "inventory", action: "create", description: "Create new inventory items", category: "inventory" },
  { resource: "inventory", action: "edit", description: "Edit inventory items", category: "inventory" },
  { resource: "inventory", action: "adjust", description: "Make inventory adjustments", category: "inventory" },
  { resource: "inventory", action: "delete", description: "Delete inventory and product records", category: "inventory" },
  { resource: "inventory", action: "upload", description: "Bulk upload inventory via CSV", category: "inventory" },
  { resource: "inventory", action: "receive", description: "Receive inventory shipments", category: "inventory" },
  { resource: "inventory", action: "audit", description: "View inventory transaction history and audit logs", category: "inventory" },
  { resource: "orders", action: "view", description: "View orders list", category: "orders" },
  { resource: "orders", action: "claim", description: "Claim orders for picking", category: "orders" },
  { resource: "orders", action: "edit", description: "Edit order details", category: "orders" },
  { resource: "orders", action: "cancel", description: "Cancel orders", category: "orders" },
  { resource: "orders", action: "hold", description: "Put orders on hold", category: "orders" },
  { resource: "orders", action: "priority", description: "Change order priority", category: "orders" },
  { resource: "orders", action: "resolve_exception", description: "Resolve order exceptions", category: "orders" },
  { resource: "picking", action: "view", description: "View picking queue", category: "picking" },
  { resource: "picking", action: "perform", description: "Perform picking operations", category: "picking" },
  { resource: "picking", action: "complete", description: "Mark picks as complete", category: "picking" },
  { resource: "channels", action: "view", description: "View sales channels", category: "channels" },
  { resource: "channels", action: "create", description: "Create new channels", category: "channels" },
  { resource: "channels", action: "edit", description: "Edit channel settings", category: "channels" },
  { resource: "channels", action: "sync", description: "Sync channel data", category: "channels" },
  { resource: "channels", action: "delete", description: "Delete channels", category: "channels" },
  { resource: "reports", action: "view", description: "View reports", category: "reports" },
  { resource: "reports", action: "export", description: "Export report data", category: "reports" },
  { resource: "users", action: "view", description: "View user list", category: "users" },
  { resource: "users", action: "create", description: "Create new users", category: "users" },
  { resource: "users", action: "edit", description: "Edit user details", category: "users" },
  { resource: "users", action: "delete", description: "Delete users", category: "users" },
  { resource: "users", action: "manage_roles", description: "Assign roles to users", category: "users" },
  { resource: "roles", action: "view", description: "View roles", category: "users" },
  { resource: "roles", action: "create", description: "Create custom roles", category: "users" },
  { resource: "roles", action: "edit", description: "Edit role permissions", category: "users" },
  { resource: "roles", action: "delete", description: "Delete custom roles", category: "users" },
  { resource: "purchasing", action: "view", description: "View purchase orders and vendor products", category: "purchasing" },
  { resource: "purchasing", action: "create", description: "Create purchase orders", category: "purchasing" },
  { resource: "purchasing", action: "edit", description: "Edit purchase orders and vendor products", category: "purchasing" },
  { resource: "purchasing", action: "approve", description: "Approve purchase orders (multi-level)", category: "purchasing" },
  { resource: "purchasing", action: "cancel", description: "Cancel purchase orders", category: "purchasing" },
  { resource: "settings", action: "view", description: "View system settings", category: "settings" },
  { resource: "settings", action: "edit", description: "Edit system settings", category: "settings" },
  { resource: "shopify", action: "view", description: "View Shopify sync status", category: "shopify" },
  { resource: "shopify", action: "sync", description: "Trigger Shopify sync", category: "shopify" },
  { resource: "locations", action: "view", description: "View warehouse locations", category: "inventory" },
  { resource: "locations", action: "create", description: "Create locations", category: "inventory" },
  { resource: "locations", action: "edit", description: "Edit locations", category: "inventory" },
  { resource: "warehouse", action: "read", description: "View warehouse settings", category: "warehouse" },
  { resource: "warehouse", action: "manage", description: "Manage warehouse settings and replenishment rules", category: "warehouse" },
];

export const SYSTEM_ROLES = {
  admin: {
    name: "Administrator",
    description: "Full system access",
    permissions: DEFAULT_PERMISSIONS.map((p: any) => `${p.resource}:${p.action}`),
  },
  lead: {
    name: "Team Lead",
    description: "Manage picking operations and resolve exceptions",
    permissions: [
      "dashboard:view", "inventory:view", "orders:view", "orders:claim", "orders:hold", "orders:priority", "orders:resolve_exception",
      "picking:view", "picking:perform", "picking:complete", "purchasing:view", "purchasing:create", "purchasing:edit", "purchasing:cancel",
      "reports:view", "users:view", "shopify:view", "locations:view",
    ],
  },
  picker: {
    name: "Picker",
    description: "Perform picking operations",
    permissions: ["dashboard:view", "orders:view", "orders:claim", "picking:view", "picking:perform", "picking:complete"],
  },
};
