// GENERATED by gen_data.py - do not hand-edit numbers; they follow the real engine formulas.
window.MOCK = {
 "asOf": "2026-07-26",
 "horizonDays": 90,
 "confidenceWeights": {
  "high": 100,
  "medium": 70,
  "low": 40
 },
 "policy": {
  "method": "weighted_blend_v1",
  "windows": {
   "short": 7,
   "standard": 30,
   "long": 90,
   "seasonal": 30
  },
  "weights": {
   "short": 30,
   "standard": 35,
   "long": 20,
   "seasonal": 15
  },
  "cohort": "3f9a2c1e",
  "forecastVersion": 2
 },
 "vendors": [
  {
   "id": 1,
   "code": "GTS",
   "name": "GTS Distribution",
   "leadTimeDays": 7,
   "terms": "Net 30",
   "email": "orders@gtsdistribution.com",
   "stage": 3,
   "caps": {
    "maxPoCents": 250000,
    "maxDayCents": 500000,
    "maxLinesRun": 25
   }
  },
  {
   "id": 2,
   "code": "SHD",
   "name": "Southern Hobby",
   "leadTimeDays": 10,
   "terms": "Net 30",
   "email": "sales@southernhobby.com",
   "stage": 2,
   "caps": {
    "maxPoCents": 150000,
    "maxDayCents": 300000,
    "maxLinesRun": 25
   }
  },
  {
   "id": 3,
   "code": "PSC",
   "name": "Peach State Cards",
   "leadTimeDays": 12,
   "terms": "Net 15",
   "email": "po@peachstatecards.com",
   "stage": 1,
   "caps": null
  },
  {
   "id": 4,
   "code": "BCW",
   "name": "BCW Direct",
   "leadTimeDays": 5,
   "terms": "Net 30",
   "email": "wholesale@bcwsupplies.com",
   "stage": 3,
   "caps": {
    "maxPoCents": 200000,
    "maxDayCents": 250000,
    "maxLinesRun": 25
   }
  },
  {
   "id": 5,
   "code": "MEX",
   "name": "Magazine Exchange",
   "leadTimeDays": 14,
   "terms": "Prepaid",
   "email": "orders@magazineexchange.com",
   "stage": 1,
   "caps": null
  }
 ],
 "adjustments": [
  {
   "id": 1,
   "scope": "category",
   "target": "Sealed - Pokemon",
   "pct": 20,
   "start": "2026-07-15",
   "end": "2026-08-31",
   "reason": "Summer set surge - Destined Rivals wave 2",
   "active": true,
   "createdBy": "owner"
  },
  {
   "id": 2,
   "scope": "business",
   "target": "All SKUs",
   "pct": 15,
   "start": "2026-11-01",
   "end": "2026-12-24",
   "reason": "Holiday season baseline lift",
   "active": false,
   "createdBy": "owner"
  },
  {
   "id": 3,
   "scope": "category",
   "target": "Sealed - Pokemon",
   "pct": 40,
   "start": "2026-11-01",
   "end": "2026-11-30",
   "reason": "Black Friday + Mega Evolution launch",
   "active": false,
   "createdBy": "owner"
  }
 ],
 "events": [
  {
   "id": 11,
   "name": "Mega Evolution ETB preorder drop",
   "type": "preorder",
   "status": "active",
   "sku": "PKM-MEGA-ETB",
   "pieces": 900,
   "confidence": "high",
   "start": "2026-09-26",
   "end": "2026-10-10"
  },
  {
   "id": 12,
   "name": "Collect-A-Con wholesale order",
   "type": "wholesale",
   "status": "planned",
   "sku": "PKM-PRE-ETB",
   "pieces": 300,
   "confidence": "high",
   "start": "2026-08-14",
   "end": "2026-08-16"
  },
  {
   "id": 13,
   "name": "Black Friday supplies push",
   "type": "promotion",
   "status": "planned",
   "sku": null,
   "category": "Supplies",
   "pieces": 2500,
   "confidence": "medium",
   "start": "2026-11-27",
   "end": "2026-12-01"
  }
 ],
 "exclusionRules": [
  {
   "id": 1,
   "field": "category",
   "value": "Singles",
   "excludedCount": 34,
   "addedBy": "owner",
   "addedAt": "2026-05-02"
  },
  {
   "id": 2,
   "field": "tag",
   "value": "discontinued",
   "excludedCount": 2,
   "addedBy": "owner",
   "addedAt": "2026-05-02"
  },
  {
   "id": 3,
   "field": "sku_prefix",
   "value": "GRD-",
   "excludedCount": 1,
   "addedBy": "auto-suggest, approved by owner",
   "addedAt": "2026-06-18"
  }
 ],
 "items": [
  {
   "sku": "PKM-PRE-ETB",
   "name": "Prismatic Evolutions Elite Trainer Box",
   "category": "Sealed - Pokemon",
   "productLine": "Prismatic Evolutions",
   "vendor": "GTS Distribution",
   "vendorCode": "GTS",
   "leadTimeDays": 7,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 4650,
   "moq": 10,
   "increment": 10,
   "usage": {
    "d7": 96,
    "d30": 342,
    "d90": 810,
    "seasonal30": 168,
    "prior30": 236
   },
   "windowAdu": {
    "d7": 13.71,
    "d30": 11.4,
    "d90": 9.0,
    "seasonal": 5.6
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 10.74,
   "growthMultiplier": 1.2,
   "growthAdjustments": [
    {
     "label": "+20% Sealed - Pokemon",
     "pct": 20,
     "id": 1,
     "reason": "Summer set surge - Destined Rivals wave 2",
     "range": "2026-07-15 to 2026-08-31"
    }
   ],
   "adjustedAdu": 12.89,
   "onHand": 118,
   "reserved": 22,
   "available": 96,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 300,
   "forwardDemandRows": [
    {
     "event": "Collect-A-Con wholesale order",
     "type": "wholesale",
     "raw": 300,
     "confidence": "high",
     "weighted": 300,
     "allocated": false
    }
   ],
   "reorderPoint": 181,
   "adjustedReorderPoint": 481,
   "effectiveSupply": 96,
   "gap": 385,
   "suggestedPieces": 390,
   "suggestedValueCents": 1813500,
   "baseline": {
    "reorderPoint": 151,
    "adjustedReorderPoint": 451,
    "gap": 355,
    "suggestedPieces": 360
   },
   "daysOfSupply": 7,
   "trend": "flat",
   "trendRatio": 1.45,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 12,
   "status": "order_now",
   "excluded": false
  },
  {
   "sku": "PKM-PRE-BB",
   "name": "Prismatic Evolutions Booster Bundle",
   "category": "Sealed - Pokemon",
   "productLine": "Prismatic Evolutions",
   "vendor": "GTS Distribution",
   "vendorCode": "GTS",
   "leadTimeDays": 7,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 2350,
   "moq": 12,
   "increment": 6,
   "usage": {
    "d7": 58,
    "d30": 214,
    "d90": 566,
    "seasonal30": 121,
    "prior30": 189
   },
   "windowAdu": {
    "d7": 8.29,
    "d30": 7.13,
    "d90": 6.29,
    "seasonal": 4.03
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 6.85,
   "growthMultiplier": 1.2,
   "growthAdjustments": [
    {
     "label": "+20% Sealed - Pokemon",
     "pct": 20,
     "id": 1,
     "reason": "Summer set surge - Destined Rivals wave 2",
     "range": "2026-07-15 to 2026-08-31"
    }
   ],
   "adjustedAdu": 8.21,
   "onHand": 176,
   "reserved": 14,
   "available": 162,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 115,
   "adjustedReorderPoint": 115,
   "effectiveSupply": 162,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 96,
    "adjustedReorderPoint": 96,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 20,
   "trend": "flat",
   "trendRatio": 1.13,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 9,
   "status": "ok",
   "excluded": false
  },
  {
   "sku": "PKM-DRI-BB36",
   "name": "Destined Rivals Booster Box (36ct)",
   "category": "Sealed - Pokemon",
   "productLine": "Destined Rivals",
   "vendor": "GTS Distribution",
   "vendorCode": "GTS",
   "leadTimeDays": 7,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 10800,
   "moq": 6,
   "increment": 6,
   "usage": {
    "d7": 41,
    "d30": 150,
    "d90": 366,
    "seasonal30": 0,
    "prior30": 139
   },
   "windowAdu": {
    "d7": 5.86,
    "d30": 5.0,
    "d90": 4.07,
    "seasonal": 0.0
   },
   "blendWeights": {
    "short": 35.3,
    "standard": 41.2,
    "long": 23.5,
    "seasonal": 0
   },
   "adu": 5.08,
   "growthMultiplier": 1.2,
   "growthAdjustments": [
    {
     "label": "+20% Sealed - Pokemon",
     "pct": 20,
     "id": 1,
     "reason": "Summer set surge - Destined Rivals wave 2",
     "range": "2026-07-15 to 2026-08-31"
    }
   ],
   "adjustedAdu": 6.1,
   "onHand": 84,
   "reserved": 8,
   "available": 76,
   "onOrder": 144,
   "openPoCount": 2,
   "poEta": "2026-08-04",
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 86,
   "adjustedReorderPoint": 86,
   "effectiveSupply": 220,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 72,
    "adjustedReorderPoint": 72,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 12,
   "trend": "flat",
   "trendRatio": 1.08,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 31,
   "status": "on_order",
   "excluded": false
  },
  {
   "sku": "PKM-151-UPC",
   "name": "151 Ultra Premium Collection",
   "category": "Sealed - Pokemon",
   "productLine": "Scarlet & Violet",
   "vendor": "Southern Hobby",
   "vendorCode": "SHD",
   "leadTimeDays": 10,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 9200,
   "moq": 6,
   "increment": 6,
   "usage": {
    "d7": 18,
    "d30": 74,
    "d90": 231,
    "seasonal30": 89,
    "prior30": 81
   },
   "windowAdu": {
    "d7": 2.57,
    "d30": 2.47,
    "d90": 2.57,
    "seasonal": 2.97
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 2.59,
   "growthMultiplier": 1.2,
   "growthAdjustments": [
    {
     "label": "+20% Sealed - Pokemon",
     "pct": 20,
     "id": 1,
     "reason": "Summer set surge - Destined Rivals wave 2",
     "range": "2026-07-15 to 2026-08-31"
    }
   ],
   "adjustedAdu": 3.11,
   "onHand": 6,
   "reserved": 6,
   "available": 0,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 53,
   "adjustedReorderPoint": 53,
   "effectiveSupply": 0,
   "gap": 53,
   "suggestedPieces": 54,
   "suggestedValueCents": 496800,
   "baseline": {
    "reorderPoint": 45,
    "adjustedReorderPoint": 45,
    "gap": 45,
    "suggestedPieces": 48
   },
   "daysOfSupply": 0,
   "trend": "flat",
   "trendRatio": 0.91,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 44,
   "status": "stockout",
   "excluded": false
  },
  {
   "sku": "PKM-SVP-TIN",
   "name": "Paldea Adventure Chest Tin",
   "category": "Sealed - Pokemon",
   "productLine": "Scarlet & Violet",
   "vendor": "Southern Hobby",
   "vendorCode": "SHD",
   "leadTimeDays": 10,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 2100,
   "moq": 12,
   "increment": 12,
   "usage": {
    "d7": 22,
    "d30": 96,
    "d90": 270,
    "seasonal30": 208,
    "prior30": 90
   },
   "windowAdu": {
    "d7": 3.14,
    "d30": 3.2,
    "d90": 3.0,
    "seasonal": 6.93
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 3.7,
   "growthMultiplier": 1.2,
   "growthAdjustments": [
    {
     "label": "+20% Sealed - Pokemon",
     "pct": 20,
     "id": 1,
     "reason": "Summer set surge - Destined Rivals wave 2",
     "range": "2026-07-15 to 2026-08-31"
    }
   ],
   "adjustedAdu": 4.44,
   "onHand": 310,
   "reserved": 12,
   "available": 298,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 76,
   "adjustedReorderPoint": 76,
   "effectiveSupply": 298,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 63,
    "adjustedReorderPoint": 63,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 67,
   "trend": "flat",
   "trendRatio": 1.07,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 61,
   "status": "ok",
   "excluded": false
  },
  {
   "sku": "PKM-MEGA-ETB",
   "name": "Mega Evolution ETB (Preorder)",
   "category": "Sealed - Pokemon",
   "productLine": "Mega Evolution",
   "vendor": "GTS Distribution",
   "vendorCode": "GTS",
   "leadTimeDays": 21,
   "leadTimeSource": "override",
   "safetyStockDays": 7,
   "unitCostCents": 5200,
   "moq": 10,
   "increment": 10,
   "usage": {
    "d7": 4,
    "d30": 9,
    "d90": 9,
    "seasonal30": 0,
    "prior30": 0
   },
   "windowAdu": {
    "d7": 0.57,
    "d30": 0.3,
    "d90": 0.1,
    "seasonal": 0.0
   },
   "blendWeights": {
    "short": 35.3,
    "standard": 41.2,
    "long": 23.5,
    "seasonal": 0
   },
   "adu": 0.35,
   "growthMultiplier": 1.2,
   "growthAdjustments": [
    {
     "label": "+20% Sealed - Pokemon",
     "pct": 20,
     "id": 1,
     "reason": "Summer set surge - Destined Rivals wave 2",
     "range": "2026-07-15 to 2026-08-31"
    }
   ],
   "adjustedAdu": 0.42,
   "onHand": 0,
   "reserved": 0,
   "available": 0,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 900,
   "forwardDemandRows": [
    {
     "event": "Mega Evolution ETB preorder drop",
     "type": "preorder",
     "raw": 900,
     "confidence": "high",
     "weighted": 900,
     "allocated": false
    }
   ],
   "reorderPoint": 12,
   "adjustedReorderPoint": 912,
   "effectiveSupply": 0,
   "gap": 912,
   "suggestedPieces": 920,
   "suggestedValueCents": 4784000,
   "baseline": {
    "reorderPoint": 10,
    "adjustedReorderPoint": 910,
    "gap": 910,
    "suggestedPieces": 910
   },
   "daysOfSupply": 0,
   "trend": "rising",
   "trendRatio": 99,
   "demandQuality": "thin_history",
   "confidence": "low",
   "lastSaleDaysAgo": 6,
   "status": "stockout",
   "excluded": false
  },
  {
   "sku": "TOP-25C-HOB",
   "name": "2025 Topps Chrome Hobby Box",
   "category": "Sealed - Sports",
   "productLine": "2025 Topps Chrome",
   "vendor": "Peach State Cards",
   "vendorCode": "PSC",
   "leadTimeDays": 12,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 7400,
   "moq": 8,
   "increment": 8,
   "usage": {
    "d7": 26,
    "d30": 118,
    "d90": 342,
    "seasonal30": 96,
    "prior30": 124
   },
   "windowAdu": {
    "d7": 3.71,
    "d30": 3.93,
    "d90": 3.8,
    "seasonal": 3.2
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 3.73,
   "growthMultiplier": 1.0,
   "growthAdjustments": [],
   "adjustedAdu": 3.73,
   "onHand": 214,
   "reserved": 10,
   "available": 204,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 71,
   "adjustedReorderPoint": 71,
   "effectiveSupply": 204,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 71,
    "adjustedReorderPoint": 71,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 55,
   "trend": "flat",
   "trendRatio": 0.95,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 27,
   "status": "ok",
   "excluded": false
  },
  {
   "sku": "TOP-25S1-BL",
   "name": "2025 Topps Series One Blaster",
   "category": "Sealed - Sports",
   "productLine": "2025 Topps Chrome",
   "vendor": "Peach State Cards",
   "vendorCode": "PSC",
   "leadTimeDays": 12,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 1950,
   "moq": 24,
   "increment": 12,
   "usage": {
    "d7": 9,
    "d30": 62,
    "d90": 294,
    "seasonal30": 88,
    "prior30": 131
   },
   "windowAdu": {
    "d7": 1.29,
    "d30": 2.07,
    "d90": 3.27,
    "seasonal": 2.93
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 2.2,
   "growthMultiplier": 1.0,
   "growthAdjustments": [],
   "adjustedAdu": 2.2,
   "onHand": 342,
   "reserved": 4,
   "available": 338,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 42,
   "adjustedReorderPoint": 42,
   "effectiveSupply": 338,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 42,
    "adjustedReorderPoint": 42,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 153,
   "trend": "falling",
   "trendRatio": 0.47,
   "demandQuality": "normal",
   "confidence": "medium",
   "lastSaleDaysAgo": 88,
   "status": "ok",
   "excluded": false
  },
  {
   "sku": "TOP-25B-JMB",
   "name": "2025 Bowman Jumbo Hobby Box",
   "category": "Sealed - Sports",
   "productLine": "2025 Bowman",
   "vendor": "Magazine Exchange",
   "vendorCode": "MEX",
   "leadTimeDays": 14,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 15800,
   "moq": 4,
   "increment": 4,
   "usage": {
    "d7": 3,
    "d30": 17,
    "d90": 92,
    "seasonal30": 41,
    "prior30": 46
   },
   "windowAdu": {
    "d7": 0.43,
    "d30": 0.57,
    "d90": 1.02,
    "seasonal": 1.37
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 0.74,
   "growthMultiplier": 1.0,
   "growthAdjustments": [],
   "adjustedAdu": 0.74,
   "onHand": 164,
   "reserved": 2,
   "available": 162,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 16,
   "adjustedReorderPoint": 16,
   "effectiveSupply": 162,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 16,
    "adjustedReorderPoint": 16,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 220,
   "trend": "falling",
   "trendRatio": 0.37,
   "demandQuality": "normal",
   "confidence": "medium",
   "lastSaleDaysAgo": 196,
   "status": "ok",
   "excluded": false
  },
  {
   "sku": "PAN-PRZ-HOB",
   "name": "Prizm Basketball Hobby Box",
   "category": "Sealed - Sports",
   "productLine": "Prizm Basketball",
   "vendor": "Peach State Cards",
   "vendorCode": "PSC",
   "leadTimeDays": 25,
   "leadTimeSource": "override",
   "safetyStockDays": 7,
   "unitCostCents": 12600,
   "moq": 4,
   "increment": 4,
   "usage": {
    "d7": 19,
    "d30": 74,
    "d90": 198,
    "seasonal30": 66,
    "prior30": 70
   },
   "windowAdu": {
    "d7": 2.71,
    "d30": 2.47,
    "d90": 2.2,
    "seasonal": 2.2
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 2.45,
   "growthMultiplier": 1.0,
   "growthAdjustments": [],
   "adjustedAdu": 2.45,
   "onHand": 92,
   "reserved": 6,
   "available": 86,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 79,
   "adjustedReorderPoint": 79,
   "effectiveSupply": 86,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 79,
    "adjustedReorderPoint": 79,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 35,
   "trend": "flat",
   "trendRatio": 1.06,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 33,
   "status": "order_soon",
   "excluded": false
  },
  {
   "sku": "BCW-TL-100",
   "name": "BCW Toploaders 3x4 (100ct pack)",
   "category": "Supplies",
   "productLine": "BCW Essentials",
   "vendor": "BCW Direct",
   "vendorCode": "BCW",
   "leadTimeDays": 5,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 680,
   "moq": 50,
   "increment": 25,
   "usage": {
    "d7": 210,
    "d30": 884,
    "d90": 2561,
    "seasonal30": 792,
    "prior30": 858
   },
   "windowAdu": {
    "d7": 30.0,
    "d30": 29.47,
    "d90": 28.46,
    "seasonal": 26.4
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 28.96,
   "growthMultiplier": 1.0,
   "growthAdjustments": [],
   "adjustedAdu": 28.96,
   "onHand": 1120,
   "reserved": 96,
   "available": 1024,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 348,
   "adjustedReorderPoint": 348,
   "effectiveSupply": 1024,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 348,
    "adjustedReorderPoint": 348,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 35,
   "trend": "flat",
   "trendRatio": 1.03,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 15,
   "status": "ok",
   "excluded": false
  },
  {
   "sku": "ULP-DS-100",
   "name": "Ultra Pro Deck Sleeves (100ct)",
   "category": "Supplies",
   "productLine": "Ultra Pro Core",
   "vendor": "BCW Direct",
   "vendorCode": "BCW",
   "leadTimeDays": 5,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 420,
   "moq": 72,
   "increment": 36,
   "usage": {
    "d7": 118,
    "d30": 501,
    "d90": 1489,
    "seasonal30": 468,
    "prior30": 512
   },
   "windowAdu": {
    "d7": 16.86,
    "d30": 16.7,
    "d90": 16.54,
    "seasonal": 15.6
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 16.55,
   "growthMultiplier": 1.0,
   "growthAdjustments": [],
   "adjustedAdu": 16.55,
   "onHand": 1490,
   "reserved": 60,
   "available": 1430,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 199,
   "adjustedReorderPoint": 199,
   "effectiveSupply": 1430,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 199,
    "adjustedReorderPoint": 199,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 86,
   "trend": "flat",
   "trendRatio": 0.98,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 19,
   "status": "ok",
   "excluded": false
  },
  {
   "sku": "BCW-GB-200",
   "name": "BCW Graded Card Box (200ct)",
   "category": "Supplies",
   "productLine": "BCW Essentials",
   "vendor": "BCW Direct",
   "vendorCode": "BCW",
   "leadTimeDays": 5,
   "leadTimeSource": "vendor",
   "safetyStockDays": 7,
   "unitCostCents": 1150,
   "moq": 20,
   "increment": 10,
   "usage": {
    "d7": 0,
    "d30": 0,
    "d90": 0,
    "seasonal30": 0,
    "prior30": 2
   },
   "windowAdu": {
    "d7": 0.0,
    "d30": 0.0,
    "d90": 0.0,
    "seasonal": 0.0
   },
   "blendWeights": {
    "short": 35.3,
    "standard": 41.2,
    "long": 23.5,
    "seasonal": 0
   },
   "adu": 0.0,
   "growthMultiplier": 1.0,
   "growthAdjustments": [],
   "adjustedAdu": 0.0,
   "onHand": 86,
   "reserved": 0,
   "available": 86,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 0,
   "adjustedReorderPoint": 0,
   "effectiveSupply": 86,
   "gap": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 0,
    "adjustedReorderPoint": 0,
    "gap": 0,
    "suggestedPieces": 0
   },
   "daysOfSupply": 9999,
   "trend": "falling",
   "trendRatio": 0.0,
   "demandQuality": "no_recent_demand",
   "confidence": "low",
   "lastSaleDaysAgo": 214,
   "status": "no_movement",
   "excluded": false
  },
  {
   "sku": "SGL-CHZ-PIKA",
   "name": "Pikachu ex 238/191 (Single)",
   "category": "Singles",
   "productLine": "Singles Inventory",
   "vendor": null,
   "vendorCode": null,
   "leadTimeDays": 14,
   "leadTimeSource": "default",
   "safetyStockDays": 7,
   "unitCostCents": 0,
   "moq": 1,
   "increment": 1,
   "usage": {
    "d7": 5,
    "d30": 21,
    "d90": 60,
    "seasonal30": 18,
    "prior30": 24
   },
   "windowAdu": {
    "d7": 0.71,
    "d30": 0.7,
    "d90": 0.67,
    "seasonal": 0.6
   },
   "blendWeights": {
    "short": 30,
    "standard": 35,
    "long": 20,
    "seasonal": 15
   },
   "adu": 0.68,
   "growthMultiplier": 1.0,
   "growthAdjustments": [],
   "adjustedAdu": 0.68,
   "onHand": 3,
   "reserved": 0,
   "available": 3,
   "onOrder": 0,
   "openPoCount": 0,
   "poEta": null,
   "forwardDemandPieces": 0,
   "forwardDemandRows": [],
   "reorderPoint": 15,
   "adjustedReorderPoint": 15,
   "effectiveSupply": 3,
   "gap": 12,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "baseline": {
    "reorderPoint": 15,
    "adjustedReorderPoint": 15,
    "gap": 12,
    "suggestedPieces": 0
   },
   "daysOfSupply": 4,
   "trend": "flat",
   "trendRatio": 0.88,
   "demandQuality": "normal",
   "confidence": "high",
   "lastSaleDaysAgo": 5,
   "status": "excluded",
   "excluded": true
  }
 ],
 "byCategory": {
  "Sealed - Pokemon": {
   "skus": 6,
   "belowRp": 3,
   "suggestedPieces": 1364,
   "suggestedValueCents": 7094300,
   "availableValueCents": 2273700,
   "onOrderValueCents": 1555200,
   "statuses": {
    "order_now": 1,
    "ok": 2,
    "on_order": 1,
    "stockout": 2
   }
  },
  "Sealed - Sports": {
   "skus": 4,
   "belowRp": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "availableValueCents": 5811900,
   "onOrderValueCents": 0,
   "statuses": {
    "ok": 3,
    "order_soon": 1
   }
  },
  "Supplies": {
   "skus": 3,
   "belowRp": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "availableValueCents": 1395820,
   "onOrderValueCents": 0,
   "statuses": {
    "ok": 2,
    "no_movement": 1
   }
  }
 },
 "byProductLine": {
  "Prismatic Evolutions": {
   "skus": 2,
   "belowRp": 1,
   "suggestedPieces": 390,
   "suggestedValueCents": 1813500,
   "availableValueCents": 827100,
   "onOrderValueCents": 0,
   "statuses": {
    "order_now": 1,
    "ok": 1
   }
  },
  "Destined Rivals": {
   "skus": 1,
   "belowRp": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "availableValueCents": 820800,
   "onOrderValueCents": 1555200,
   "statuses": {
    "on_order": 1
   }
  },
  "Scarlet & Violet": {
   "skus": 2,
   "belowRp": 1,
   "suggestedPieces": 54,
   "suggestedValueCents": 496800,
   "availableValueCents": 625800,
   "onOrderValueCents": 0,
   "statuses": {
    "stockout": 1,
    "ok": 1
   }
  },
  "Mega Evolution": {
   "skus": 1,
   "belowRp": 1,
   "suggestedPieces": 920,
   "suggestedValueCents": 4784000,
   "availableValueCents": 0,
   "onOrderValueCents": 0,
   "statuses": {
    "stockout": 1
   }
  },
  "2025 Topps Chrome": {
   "skus": 2,
   "belowRp": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "availableValueCents": 2168700,
   "onOrderValueCents": 0,
   "statuses": {
    "ok": 2
   }
  },
  "2025 Bowman": {
   "skus": 1,
   "belowRp": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "availableValueCents": 2559600,
   "onOrderValueCents": 0,
   "statuses": {
    "ok": 1
   }
  },
  "Prizm Basketball": {
   "skus": 1,
   "belowRp": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "availableValueCents": 1083600,
   "onOrderValueCents": 0,
   "statuses": {
    "order_soon": 1
   }
  },
  "BCW Essentials": {
   "skus": 2,
   "belowRp": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "availableValueCents": 795220,
   "onOrderValueCents": 0,
   "statuses": {
    "ok": 1,
    "no_movement": 1
   }
  },
  "Ultra Pro Core": {
   "skus": 1,
   "belowRp": 0,
   "suggestedPieces": 0,
   "suggestedValueCents": 0,
   "availableValueCents": 600600,
   "onOrderValueCents": 0,
   "statuses": {
    "ok": 1
   }
  }
 }
};
