import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from "dotenv";

dotenv.config();
process.env.PGSSLMODE = "require";
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

function toCamelCase(str: string) {
  return str.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
}

async function run() {
  const { db } = await import("../server/db");
  const { sql } = await import("drizzle-orm");

  const tables = [
    "access_rules", "portal_config", "product_collections",
    "notification_templates", "back_in_stock_sends", "back_in_stock_subscriptions",
    "collection_alert_notification_queue", "collection_alert_settings", "collection_alert_subscriptions",
    "member_current_membership", "member_shopify_customer_ids", "member_stats",
    "subscription_billing_attempts", "subscription_contracts", "subscription_events",
    "subscription_ledger", "selling_plan_groups",
    "plan_collection_exclusions", "plan_earning_rules", "plan_feature_grants",
    "plan_features", "plan_medal_benefits", "plan_redemption_rules", "plan_variant_overrides",
    "earning_activities", "member_earning_events", "member_medal_achievements",
    "member_referrals", "medal_benefit_grants", "redemption_options",
    "reward_ledger", "reward_medals", "reward_overrides", "reward_redemptions",
    "social_accounts", "social_action_verifications", "social_verifications",
    "token_transactions", "marketplace_exclusions"
  ];

  let output = `\n// ============================================\n// INTROSPECTED AUTOGENERATED MEMBERSHIP TABLES\n// ============================================\n\n`;

  for (const table of tables) {
    const res = await db.execute(sql.raw(`
      SELECT column_name, data_type, is_nullable, character_maximum_length, column_default
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = '${table}'
      ORDER BY ordinal_position;
    `));

    if (res.rows.length === 0) {
      console.log(`Warning: Table ${table} not found in public schema.`);
      continue;
    }

    const varName = toCamelCase(table);
    output += `export const ${varName} = membershipSchema.table("${table}", {\n`;

    for (const row of res.rows) {
      const colName = row.column_name as string;
      const dataType = row.data_type as string;
      const isNullable = row.is_nullable === 'YES';
      
      const colCamel = toCamelCase(colName);
      
      let typeDef = "text";
      if (dataType.includes("int")) typeDef = "integer";
      else if (dataType.includes("timestamp")) typeDef = "timestamp";
      else if (dataType.includes("boolean")) typeDef = "boolean";
      else if (dataType.includes("json")) typeDef = "jsonb";
      else if (dataType.includes("numeric") || dataType.includes("double")) typeDef = "numeric";
      // else varchar or text default

      let fieldStr = `  ${colCamel}: ${typeDef}("${colName}")`;
      if (colName === "id") fieldStr += `.primaryKey()`;
      // We'll skip complex .notNull() or .default() to keep the initial schema flexible
      fieldStr += ",\n";
      output += fieldStr;
    }

    output += `});\n\n`;
  }

  fs.writeFileSync(path.join(import.meta.dirname, '../scripts/membership-schema-dump.ts'), output);
  console.log("Dumped types to scripts/membership-schema-dump.ts");
  process.exit();
}
run();
