import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { planReceiptUnits } from "../../../procurement/receiving-unit-contract";
import {
  createInventoryCutoverTestDatabase,
  type InventoryCutoverTestDatabase,
} from "../../../inventory/__tests__/fixtures/inventory-cutover-database";
import {
  applyPieceVariantBackfill,
  previewPieceVariantBackfill,
} from "../../piece-variant-backfill.service";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const describeDatabase = databaseUrl && disposable ? describe : describe.skip;
const FIXED_CLOCK = () => new Date("2026-09-16T12:00:00.000Z");

/**
 * Reduced catalog schema carrying the real invariants the backfill must
 * satisfy: the single-unit UOM check (migration 202), the internal-only
 * identity check, the digital/untracked check, and the case-insensitive
 * active-SKU unique index (migration 0251).
 */
const fixtureSql = `
  CREATE SCHEMA catalog;

  CREATE TABLE public.users (id varchar PRIMARY KEY);

  CREATE TABLE public.audit_events (
    id bigserial PRIMARY KEY,
    timestamp timestamptz NOT NULL DEFAULT now(),
    level text NOT NULL DEFAULT 'AUDIT',
    actor text NOT NULL,
    action text NOT NULL,
    target text,
    changes jsonb,
    context jsonb
  );

  CREATE TABLE catalog.products (
    id integer PRIMARY KEY,
    sku varchar(100),
    name text NOT NULL,
    inventory_strategy varchar(30) NOT NULL DEFAULT 'physical_fungible',
    status varchar(20) DEFAULT 'active',
    is_active boolean NOT NULL DEFAULT true
  );

  CREATE TABLE catalog.product_variants (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES catalog.products(id),
    sku varchar(100),
    name text NOT NULL,
    uom_type varchar(20) NOT NULL DEFAULT 'pack',
    units_per_variant integer NOT NULL DEFAULT 1,
    hierarchy_level integer NOT NULL DEFAULT 1,
    parent_variant_id integer,
    is_base_unit boolean NOT NULL DEFAULT false,
    requires_shipping boolean NOT NULL DEFAULT true,
    track_inventory boolean DEFAULT true,
    sales_eligibility varchar(20) NOT NULL DEFAULT 'sellable',
    shopify_variant_id varchar(100),
    shopify_inventory_item_id varchar(100),
    is_active boolean NOT NULL DEFAULT true,
    dropship_eligible boolean DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT product_variants_uom_type_chk
      CHECK (uom_type IN ('piece', 'each', 'pack', 'inner_pack', 'case', 'skid')),
    CONSTRAINT product_variants_single_unit_uom_invariants_chk CHECK (
      uom_type NOT IN ('piece', 'each')
      OR (
        units_per_variant = 1
        AND hierarchy_level = 1
        AND parent_variant_id IS NULL
        AND is_base_unit = true
      )
    ),
    CONSTRAINT product_variants_sales_eligibility_chk
      CHECK (sales_eligibility IN ('sellable', 'internal_only')),
    CONSTRAINT product_variants_internal_only_identity_chk CHECK (
      sales_eligibility = 'sellable' OR (
        shopify_variant_id IS NULL
        AND shopify_inventory_item_id IS NULL
        AND COALESCE(dropship_eligible, false) = false
      )
    ),
    CONSTRAINT product_variants_digital_untracked_chk
      CHECK (requires_shipping = true OR track_inventory IS FALSE)
  );

  CREATE UNIQUE INDEX product_variants_sku_active_unique
    ON catalog.product_variants (UPPER(sku))
    WHERE is_active = true AND sku IS NOT NULL;

  INSERT INTO public.users (id) VALUES ('operator-1');

  INSERT INTO catalog.products (id, sku, name, inventory_strategy, status, is_active) VALUES
    (1, 'SHLZ-TOP-35PT-BLU', 'Toploader 35pt Blue', 'physical_fungible', 'active', true),
    (2, 'SHLZ-SINGLE', 'Sold as singles', 'physical_fungible', 'active', true),
    (3, NULL, 'No family SKU', 'physical_fungible', 'active', true),
    (4, 'SHLZ-OLDPC', 'Retired piece', 'physical_fungible', 'active', true),
    (5, 'SHLZ-FLAG', 'Mis-flagged pack', 'physical_fungible', 'active', true),
    (6, 'SHLZ-CONFLICT', 'Colliding family', 'physical_fungible', 'active', true),
    (7, 'OTHER', 'Owner of the colliding SKU', 'physical_fungible', 'active', true),
    (8, 'SHLZ-ARCHIVED', 'Archived', 'physical_fungible', 'archived', true),
    (9, 'SHLZ-DIGITAL', 'Digital only', 'physical_fungible', 'active', true),
    (10, 'SHLZ-INACTIVE', 'Inactive product', 'physical_fungible', 'active', false),
    (11, 'SHLZ-KIT', 'Assembled kit', 'recipe_managed', 'draft', true),
    (12, ' shlz-lower ', 'Lower-case family SKU', 'physical_fungible', NULL, true),
    (13, 'SHLZ-CASEY', 'Case-insensitive collision', 'physical_fungible', 'active', true);

  INSERT INTO catalog.product_variants (
    id, product_id, sku, name, uom_type, units_per_variant, hierarchy_level,
    parent_variant_id, is_base_unit, requires_shipping, track_inventory,
    sales_eligibility, is_active
  ) VALUES
    (101, 1, 'SHLZ-TOP-35PT-BLU-P25', 'Pack of 25', 'pack', 25, 1, NULL, false, true, true, 'sellable', true),
    (102, 1, 'SHLZ-TOP-35PT-BLU-C1000', 'Case of 1000', 'case', 1000, 3, 101, false, true, true, 'internal_only', true),
    (201, 2, 'SHLZ-SINGLE', 'Each', 'each', 1, 1, NULL, true, true, true, 'sellable', true),
    (301, 3, 'ORPHAN-P10', 'Pack of 10', 'pack', 10, 1, NULL, false, true, true, 'sellable', true),
    (401, 4, 'SHLZ-OLDPC-P5', 'Pack of 5', 'pack', 5, 1, NULL, false, true, true, 'sellable', true),
    (402, 4, 'SHLZ-OLDPC-PC1', 'Piece', 'piece', 1, 1, NULL, true, true, true, 'internal_only', false),
    (501, 5, 'SHLZ-FLAG-P12', 'Pack of 12', 'pack', 12, 1, NULL, true, true, true, 'sellable', true),
    (601, 6, 'SHLZ-CONFLICT-P4', 'Pack of 4', 'pack', 4, 1, NULL, false, true, true, 'sellable', true),
    (701, 7, 'SHLZ-CONFLICT-PC1', 'Each', 'each', 1, 1, NULL, true, true, true, 'sellable', true),
    (801, 8, 'SHLZ-ARCHIVED-P3', 'Pack of 3', 'pack', 3, 1, NULL, false, true, true, 'sellable', true),
    (901, 9, 'SHLZ-DIGITAL-D5', 'Digital bundle', 'pack', 5, 1, NULL, false, false, false, 'sellable', true),
    (1001, 10, 'SHLZ-INACTIVE-P6', 'Pack of 6', 'pack', 6, 1, NULL, false, true, true, 'sellable', true),
    (1101, 11, 'SHLZ-KIT-P5', 'Pack of 5', 'pack', 5, 1, NULL, false, true, true, 'sellable', true),
    (1201, 12, 'shlz-lower-P2', 'Pack of 2', 'pack', 2, 1, NULL, false, true, true, 'sellable', true),
    (1301, 13, 'SHLZ-CASEY-P9', 'Pack of 9', 'pack', 9, 1, NULL, false, true, true, 'sellable', true),
    (1302, 7, 'shlz-casey-pc1', 'Each', 'each', 1, 1, NULL, true, true, true, 'sellable', true);

  SELECT setval(pg_get_serial_sequence('catalog.product_variants', 'id'), 5000);
`;

describeDatabase.sequential("piece variant backfill PostgreSQL guarantees", () => {
  let database: InventoryCutoverTestDatabase;

  beforeAll(async () => {
    database = await createInventoryCutoverTestDatabase(databaseUrl, disposable, fixtureSql);
  });

  afterAll(async () => {
    await database?.close();
  });

  async function countVariants(): Promise<number> {
    const result = await database.pool.query("SELECT COUNT(*)::int AS count FROM catalog.product_variants");
    return result.rows[0].count;
  }

  async function countAudits(): Promise<number> {
    const result = await database.pool.query("SELECT COUNT(*)::int AS count FROM public.audit_events");
    return result.rows[0].count;
  }

  it("carries the real single-unit invariant so a mis-shaped piece cannot exist", async () => {
    await expect(database.pool.query(`
      INSERT INTO catalog.product_variants (product_id, sku, name, uom_type, units_per_variant, is_base_unit)
      VALUES (1, 'BAD-PC1', 'Piece', 'piece', 1, false)
    `)).rejects.toMatchObject({ code: "23514" });
  });

  it("previews exactly the pack-only live products and blocks the ones it cannot mint safely", async () => {
    const preview = await previewPieceVariantBackfill(database.pool, { clock: FIXED_CLOCK });
    const byProduct = new Map(preview.targets.map((target) => [target.productId, target]));

    expect([...byProduct.keys()]).toEqual([1, 3, 4, 5, 6, 11, 12, 13]);
    expect(preview.summary).toMatchObject({
      candidateProducts: 8,
      productsToCreate: 3,
      blockedProducts: 5,
      blockerCounts: {
        product_sku_missing: 1,
        proposed_sku_too_long: 0,
        proposed_sku_already_used: 3,
        inactive_single_unit_variant_exists: 1,
        base_unit_flag_on_multi_unit_variant: 1,
      },
      warningCounts: { recipe_managed_product: 1, product_status_not_active: 1 },
    });

    expect(byProduct.get(1)).toMatchObject({
      action: "create_piece_variant",
      proposedVariant: { sku: "SHLZ-TOP-35PT-BLU-PC1", uomType: "piece", salesEligibility: "internal_only" },
    });
    expect(byProduct.get(3)?.blockers).toEqual(["product_sku_missing"]);
    expect(byProduct.get(4)).toMatchObject({
      blockers: ["proposed_sku_already_used", "inactive_single_unit_variant_exists"],
      skuConflict: { variantId: 402, productId: 4, isActive: false },
    });
    expect(byProduct.get(5)?.blockers).toEqual(["base_unit_flag_on_multi_unit_variant"]);
    expect(byProduct.get(6)).toMatchObject({
      blockers: ["proposed_sku_already_used"],
      skuConflict: { variantId: 701, productId: 7, isActive: true },
    });
    expect(byProduct.get(11)).toMatchObject({
      action: "create_piece_variant",
      warnings: ["recipe_managed_product", "product_status_not_active"],
    });
    // Family SKU whitespace is trimmed; case is preserved, collisions are not.
    expect(byProduct.get(12)).toMatchObject({
      productSku: "shlz-lower",
      proposedVariant: { sku: "shlz-lower-PC1" },
    });
    expect(byProduct.get(13)).toMatchObject({
      blockers: ["proposed_sku_already_used"],
      skuConflict: { variantId: 1302, productId: 7, isActive: true },
    });

    const again = await previewPieceVariantBackfill(database.pool, { clock: () => new Date() });
    expect(again.previewHash).toBe(preview.previewHash);
  });

  it("refuses to write against a stale preview hash", async () => {
    const variantsBefore = await countVariants();
    await expect(applyPieceVariantBackfill({
      pool: database.pool,
      actorId: "operator-1",
      expectedPreviewHash: "c".repeat(64),
      clock: FIXED_CLOCK,
    })).rejects.toThrow("Catalog changed after preview");
    expect(await countVariants()).toBe(variantsBefore);
    expect(await countAudits()).toBe(0);
  });

  it("refuses an actor that is not an application user", async () => {
    const preview = await previewPieceVariantBackfill(database.pool, { clock: FIXED_CLOCK });
    await expect(applyPieceVariantBackfill({
      pool: database.pool,
      actorId: "nobody",
      expectedPreviewHash: preview.previewHash,
      clock: FIXED_CLOCK,
    })).rejects.toThrow("existing application user");
    expect(await countAudits()).toBe(0);
  });

  it("rolls the variant back when its audit row cannot be written", async () => {
    const preview = await previewPieceVariantBackfill(database.pool, { clock: FIXED_CLOCK });
    const variantsBefore = await countVariants();
    await database.pool.query("ALTER TABLE public.audit_events RENAME TO audit_events_offline");
    try {
      await expect(applyPieceVariantBackfill({
        pool: database.pool,
        actorId: "operator-1",
        expectedPreviewHash: preview.previewHash,
        clock: FIXED_CLOCK,
      })).rejects.toMatchObject({ code: "42P01" });
    } finally {
      await database.pool.query("ALTER TABLE public.audit_events_offline RENAME TO audit_events");
    }
    // The first piece was inserted before its audit insert failed; the
    // rollback must have taken it with it.
    expect(await countVariants()).toBe(variantsBefore);
    expect(await countAudits()).toBe(0);
  });

  it("creates one audited internal-only piece per safe product and leaves blocked products untouched", async () => {
    const preview = await previewPieceVariantBackfill(database.pool, { clock: FIXED_CLOCK });
    const variantsBefore = await countVariants();

    const result = await applyPieceVariantBackfill({
      pool: database.pool,
      actorId: "operator-1",
      expectedPreviewHash: preview.previewHash,
      clock: FIXED_CLOCK,
    });

    expect(result).toMatchObject({
      mode: "apply",
      previewHash: preview.previewHash,
      actorId: "operator-1",
      blockedProducts: 5,
      auditedVariants: 3,
    });
    expect(result.createdVariants.map((entry) => [entry.productId, entry.sku])).toEqual([
      [1, "SHLZ-TOP-35PT-BLU-PC1"],
      [11, "SHLZ-KIT-PC1"],
      [12, "shlz-lower-PC1"],
    ]);
    expect(await countVariants()).toBe(variantsBefore + 3);

    const created = await database.pool.query(`
      SELECT id, product_id, sku, name, uom_type, units_per_variant, hierarchy_level,
             parent_variant_id, is_base_unit, sales_eligibility, requires_shipping,
             track_inventory, is_active, dropship_eligible, shopify_variant_id
      FROM catalog.product_variants
      WHERE id > 5000
      ORDER BY id
    `);
    expect(created.rows).toHaveLength(3);
    for (const row of created.rows) {
      expect(row).toMatchObject({
        name: "Piece",
        uom_type: "piece",
        units_per_variant: 1,
        hierarchy_level: 1,
        parent_variant_id: null,
        is_base_unit: true,
        sales_eligibility: "internal_only",
        requires_shipping: true,
        track_inventory: true,
        is_active: true,
        dropship_eligible: false,
        shopify_variant_id: null,
      });
    }

    const audits = await database.pool.query(`
      SELECT timestamp, level, actor, action, target, changes, context
      FROM public.audit_events
      ORDER BY id
    `);
    expect(audits.rows).toHaveLength(3);
    expect(audits.rows[0]).toMatchObject({
      level: "AUDIT",
      actor: "user:operator-1",
      action: "product_variant.piece_unit_backfilled",
      target: `product_variant:${result.createdVariants[0].variantId}`,
    });
    expect(audits.rows[0].timestamp.toISOString()).toBe("2026-09-16T12:00:00.000Z");
    expect(audits.rows[0].changes.before).toBeNull();
    expect(audits.rows[0].changes.after).toMatchObject({
      id: result.createdVariants[0].variantId,
      product_id: 1,
      sku: "SHLZ-TOP-35PT-BLU-PC1",
      uom_type: "piece",
    });
    expect(audits.rows[0].context).toMatchObject({
      contractVersion: 1,
      source: "piece_variant_backfill",
      reason: "receiving_piece_variant_required",
      previewHash: preview.previewHash,
      productId: 1,
      productSku: "SHLZ-TOP-35PT-BLU",
      existingVariantIds: [101, 102],
    });
  });

  it("lets receiving count loose pieces for the backfilled product without touching whole-pack receipts", async () => {
    const variants = await database.pool.query(`
      SELECT id, product_id, units_per_variant, is_active, sku, name
      FROM catalog.product_variants
      WHERE product_id = 1
      ORDER BY id
    `);
    const receiptVariants = variants.rows.map((row) => ({
      id: row.id,
      productId: row.product_id,
      unitsPerVariant: row.units_per_variant,
      isActive: row.is_active,
      sku: row.sku,
      name: row.name,
    }));
    const piece = receiptVariants.find((entry) => entry.unitsPerVariant === 1);
    expect(piece?.sku).toBe("SHLZ-TOP-35PT-BLU-PC1");

    // 10,013 pieces against a P25 line: 400 full packs plus 13 loose, so the
    // whole quantity is counted in the piece variant rather than rounded.
    expect(planReceiptUnits({
      baseQty: 10_013,
      productId: 1,
      preferredVariantId: 101,
      variants: receiptVariants,
    })).toMatchObject({ productVariantId: piece?.id, unitsPerVariant: 1, expectedQty: 10_013, countsAsPieces: true });

    // 10,000 pieces still land as 400 packs; the piece never hijacks exact receipts.
    expect(planReceiptUnits({
      baseQty: 10_000,
      productId: 1,
      preferredVariantId: 101,
      variants: receiptVariants,
    })).toMatchObject({ productVariantId: 101, unitsPerVariant: 25, expectedQty: 400, countsAsPieces: false });
  });

  it("is idempotent: a second run finds only the blocked products and writes nothing", async () => {
    const variantsBefore = await countVariants();
    const auditsBefore = await countAudits();
    const preview = await previewPieceVariantBackfill(database.pool, { clock: FIXED_CLOCK });
    expect(preview.summary).toMatchObject({ candidateProducts: 5, productsToCreate: 0, blockedProducts: 5 });

    const result = await applyPieceVariantBackfill({
      pool: database.pool,
      actorId: "operator-1",
      expectedPreviewHash: preview.previewHash,
      clock: FIXED_CLOCK,
    });

    expect(result).toMatchObject({ createdVariants: [], blockedProducts: 5, auditedVariants: 0 });
    expect(await countVariants()).toBe(variantsBefore);
    expect(await countAudits()).toBe(auditsBefore);
  });

  it("aborts when a one-piece variant appears between preview and apply", async () => {
    await database.pool.query(`
      INSERT INTO catalog.products (id, sku, name) VALUES (20, 'SHLZ-RACE', 'Raced product');
      INSERT INTO catalog.product_variants (product_id, sku, name, uom_type, units_per_variant)
      VALUES (20, 'SHLZ-RACE-P8', 'Pack of 8', 'pack', 8);
    `);
    const preview = await previewPieceVariantBackfill(database.pool, { clock: FIXED_CLOCK });
    expect(preview.targets.some((target) => target.productId === 20 && target.action === "create_piece_variant")).toBe(true);

    // Another operator adds an each by hand after the preview was taken.
    await database.pool.query(`
      INSERT INTO catalog.product_variants (product_id, sku, name, uom_type, units_per_variant, is_base_unit)
      VALUES (20, 'SHLZ-RACE', 'Each', 'each', 1, true)
    `);
    const auditsBefore = await countAudits();

    await expect(applyPieceVariantBackfill({
      pool: database.pool,
      actorId: "operator-1",
      expectedPreviewHash: preview.previewHash,
      clock: FIXED_CLOCK,
    })).rejects.toThrow("Catalog changed after preview");

    const pieces = await database.pool.query(
      "SELECT id FROM catalog.product_variants WHERE product_id = 20 AND sku = 'SHLZ-RACE-PC1'",
    );
    expect(pieces.rowCount).toBe(0);
    expect(await countAudits()).toBe(auditsBefore);
  });
});
