import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { drizzle } from "drizzle-orm/node-postgres";
import * as schema from "@shared/schema";
import { createSharedProductPhotoImporter } from "../../shared-product-photos.service";
import { PgCatalogVariantPublicationPhotoReader } from "../../catalog-publication-images.reader";
import { createCatalogPublicImageUrl } from "../../catalog-public-image";
import { createInventoryCutoverTestDatabase, type InventoryCutoverTestDatabase } from "../../../inventory/__tests__/fixtures/inventory-cutover-database";
vi.mock("../../../../db", () => ({ db: {} }));
const url = process.env.ECHELON_TEST_DATABASE_URL, disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const fixture = `
CREATE SCHEMA catalog;
CREATE TABLE catalog.products(id integer PRIMARY KEY);
CREATE TABLE catalog.product_variants(id integer PRIMARY KEY,product_id integer NOT NULL REFERENCES catalog.products,UNIQUE(id,product_id));
CREATE TABLE catalog.product_assets(
 id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
 product_id integer NOT NULL REFERENCES catalog.products,product_variant_id integer REFERENCES catalog.product_variants,
 asset_type varchar(20) NOT NULL DEFAULT 'image',url text,alt_text varchar(500),position integer NOT NULL DEFAULT 0,
 is_primary integer NOT NULL DEFAULT 0,width integer,height integer,file_size integer,mime_type varchar(100),
 storage_type varchar(20) NOT NULL DEFAULT 'url',created_at timestamp NOT NULL DEFAULT now(),file_data bytea
);
CREATE TABLE public.audit_events(id bigserial PRIMARY KEY,timestamp timestamptz NOT NULL DEFAULT now(),level text NOT NULL DEFAULT 'AUDIT',
 actor text NOT NULL,action text NOT NULL,target text,changes jsonb,context jsonb);
INSERT INTO catalog.products VALUES(1),(2);
INSERT INTO catalog.product_variants VALUES(10,1),(11,1),(20,2);
` + readFileSync(resolve(process.cwd(), "migrations/0727_product_asset_variant_ownership.sql"), "utf8");
const photos = [{ url: "https://cdn.example.com/shared.jpg", position: 0, altText: "Front" },
{ url: "https://cdn.example.com/shared.jpg", position: 0 },
{ url: "https://cdn.example.com/detail.jpg", position: 1 }];
const now = new Date("2026-10-08T12:00:00Z");
(url && disposable ? describe : describe.skip).sequential("shared Catalog import defaults (PostgreSQL)", () => {
  let database: InventoryCutoverTestDatabase;
  let importer: ReturnType<typeof createSharedProductPhotoImporter>;
  beforeAll(async () => {
    database = await createInventoryCutoverTestDatabase(url, disposable, fixture);
    importer = createSharedProductPhotoImporter(drizzle(database.pool, { schema }), () => now);
  });
  afterAll(async () => { await database?.close(); });
  beforeEach(async () => {
    await database.pool.query(`TRUNCATE catalog.product_assets RESTART IDENTITY;TRUNCATE public.audit_events;
    INSERT INTO catalog.product_assets(id,product_id,product_variant_id,url,position,is_primary,storage_type,mime_type,file_data)
    VALUES(1,1,10,'https://cdn.example.com/manual.jpg',7,1,'both','image/png',decode('89504e470d0a1a0a0000000d49484452','hex')),
    (2,2,NULL,'https://cdn.example.com/other.jpg',0,1,'url',NULL,NULL);`);
  });
  async function rows() { return (await database.pool.query("SELECT * FROM catalog.product_assets ORDER BY id")).rows; }
  const append = (input = photos) => importer.append({ productId: 1, photos: input, actor: "service:shopify_content_sync" });
  it("defaults imported photos to shared and preserves exact existing assignments, bytes, primary and order", async () => {
    const before = await rows();
    const input = structuredClone(photos);
    expect(await append()).toEqual({ created: 2 });
    expect(photos).toEqual(input);
    const after = await rows();
    expect(after.slice(0, 2)).toEqual(before);
    expect(after.slice(2)).toEqual([
      expect.objectContaining({ product_id: 1, product_variant_id: null, url: photos[0].url, position: 8, is_primary: 0 }),
      expect.objectContaining({ product_id: 1, product_variant_id: null, url: photos[2].url, position: 9, is_primary: 0 }),
    ]);
    const selected = await new PgCatalogVariantPublicationPhotoReader(database.pool, createCatalogPublicImageUrl({}))
      .listPublicationPhotos({ productVariantIds: [10, 11], maxPhotosPerVariant: 12 });
    expect(selected.get(10)!.photos.map(photo => photo.url)).toEqual(["https://cdn.example.com/manual.jpg", photos[0].url, photos[2].url]);
    expect(selected.get(11)!.photos.map(photo => photo.url)).toEqual([photos[0].url, photos[2].url]);
    const audit = (await database.pool.query("SELECT * FROM public.audit_events")).rows;
    expect(audit).toEqual([expect.objectContaining({
      actor: "service:shopify_content_sync", action: "catalog.photos.imported_shared", timestamp: now,
      changes: { before: { assetIds: [1] }, after: { addedAssetIds: after.slice(2).map(photo => photo.id), productVariantId: null } }
    })]);
  });
  it("replay and simultaneous imports do not duplicate photos or audits", async () => {
    const outcomes = await Promise.all([append(), append()]);
    expect(outcomes.map(result => result.created).sort()).toEqual([0, 2]);
    expect(await append()).toEqual({ created: 0 });
    expect(await rows()).toHaveLength(4);
    expect((await database.pool.query("SELECT count(*)::int AS count FROM public.audit_events")).rows[0].count).toBe(1);
  });
  it("a matching existing variant photo is retained rather than silently promoted", async () => {
    expect(await append([{ url: "https://cdn.example.com/manual.jpg", position: 0 }])).toEqual({ created: 0 });
    expect((await rows())[0].product_variant_id).toBe(10);
  });
  it("no source photos cannot erase a gallery", async () => {
    const before = await rows();
    expect(await append([])).toEqual({ created: 0 });
    expect(await rows()).toEqual(before);
  });
  it("creates exactly one shared primary when the product has no photos", async () => {
    await database.pool.query("DELETE FROM catalog.product_assets WHERE product_id=1");
    await append();
    const created = (await rows()).filter(photo => photo.product_id === 1);
    expect(created.map(photo => photo.is_primary)).toEqual([1, 0]);
    expect(created.map(photo => photo.product_variant_id)).toEqual([null, null]);
    expect(created.map(photo => photo.position)).toEqual([0, 1]);
  });
  it("rolls back all new photos when audit persistence fails and then safely retries", async () => {
    const before = await rows();
    await database.pool.query(`CREATE FUNCTION public.fail_import_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit unavailable';END $$;
   CREATE TRIGGER fail_import_audit BEFORE INSERT ON public.audit_events FOR EACH ROW EXECUTE FUNCTION public.fail_import_audit();`);
    try {
      await expect(append()).rejects.toThrow("audit unavailable");
      expect(await rows()).toEqual(before);
    }
    finally {
      await database.pool.query("DROP TRIGGER fail_import_audit ON public.audit_events;DROP FUNCTION public.fail_import_audit()");
    }
    expect(await append()).toEqual({ created: 2 });
  });
  it("rejects a missing product without photos or audit writes", async () => {
    await expect(importer.append({ productId: 999, photos, actor: "operator" })).rejects.toMatchObject({ code: "PRODUCT_NOT_FOUND" });
    expect(await rows()).toHaveLength(2);
  });
});
