import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { drizzle } from "drizzle-orm/node-postgres";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import * as schema from "@shared/schema";
import {
  buildShopifyProductConsolidationPlan,
  shopifyProductConsolidationRequestHash,
  type ShopifyProductConsolidationApplyRequest,
  type ShopifyProductConsolidationEvidence,
} from "../../shopify-product-consolidation.domain";
import {
  createShopifyProductConsolidationRepository,
} from "../../shopify-product-consolidation.repository";
import {
  createInventoryCutoverTestDatabase,
  type InventoryCutoverTestDatabase,
} from "../../../inventory/__tests__/fixtures/inventory-cutover-database";

const databaseUrl = process.env.ECHELON_TEST_DATABASE_URL;
const disposable = process.env.ECHELON_TEST_DATABASE_DISPOSABLE === "true";
const describeDatabase = databaseUrl && disposable ? describe : describe.skip;
const commandMigration = readFileSync(
  resolve(process.cwd(), "migrations/0667_shopify_product_consolidation_commands.sql"),
  "utf8",
);

const fixtureSql = `
  CREATE SCHEMA catalog;
  CREATE SCHEMA channels;
  CREATE SCHEMA inventory;
  CREATE SCHEMA warehouse;
  CREATE SCHEMA marketplace;
  CREATE SCHEMA procurement;
  CREATE SCHEMA oms;
  CREATE SCHEMA wms;
  CREATE SCHEMA dropship;
  CREATE SCHEMA shipping;
  CREATE SCHEMA ebay;

  CREATE TABLE catalog.shipping_groups (
    id integer PRIMARY KEY,
    code varchar(50) NOT NULL
  );
  CREATE TABLE catalog.products (
    id integer PRIMARY KEY,
    sku varchar(100),
    name text NOT NULL,
    status varchar(20),
    is_active boolean NOT NULL,
    shopify_product_id varchar(100),
    shipping_group_id integer,
    inventory_strategy varchar(30) NOT NULL,
    base_unit varchar(20) NOT NULL,
    inventory_type varchar(20) NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp()
  );
  CREATE TABLE catalog.product_variants (
    id integer PRIMARY KEY,
    product_id integer NOT NULL REFERENCES catalog.products(id),
    sku varchar(100),
    name text NOT NULL,
    uom_type varchar(20) NOT NULL,
    units_per_variant integer NOT NULL,
    hierarchy_level integer NOT NULL,
    parent_variant_id integer,
    is_base_unit boolean NOT NULL,
    requires_shipping boolean NOT NULL,
    track_inventory boolean,
    sales_eligibility varchar(20) NOT NULL,
    inventory_policy varchar(20),
    dropship_eligible boolean,
    is_active boolean NOT NULL,
    shopify_variant_id varchar(100),
    shopify_inventory_item_id varchar(100),
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    UNIQUE(id, product_id)
  );
  CREATE TABLE catalog.product_assets (
    id integer PRIMARY KEY,
    product_id integer NOT NULL,
    product_variant_id integer
  );

  CREATE TABLE channels.channels (
    id integer PRIMARY KEY,
    name varchar(100) NOT NULL,
    provider varchar(30) NOT NULL,
    is_default integer NOT NULL
  );
  CREATE TABLE channels.channel_connections (
    id integer PRIMARY KEY,
    channel_id integer NOT NULL,
    shop_domain varchar(255),
    access_token text,
    api_version varchar(20),
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp()
  );
  CREATE TABLE channels.channel_feeds (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id integer,
    product_variant_id integer NOT NULL,
    channel_type varchar(30) NOT NULL,
    channel_variant_id varchar(100),
    channel_product_id varchar(100),
    channel_inventory_item_id varchar(100),
    is_active integer NOT NULL,
    last_synced_qty integer,
    consecutive_push_failures integer NOT NULL DEFAULT 0,
    quarantined_at timestamptz,
    quarantine_reason text,
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp()
  );
  CREATE TABLE channels.channel_listings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id integer NOT NULL,
    product_variant_id integer,
    external_product_id varchar(100),
    external_variant_id varchar(100),
    external_url text,
    sync_status varchar(20),
    sync_error text,
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp()
  );
  CREATE TABLE channels.channel_product_allocation (id integer PRIMARY KEY, product_id integer);
  CREATE TABLE channels.channel_product_overrides (id integer PRIMARY KEY, product_id integer);
  CREATE TABLE channels.channel_allocation_rules (
    id integer PRIMARY KEY,
    product_id integer,
    product_variant_id integer
  );
  CREATE TABLE channels.channel_reservations (id integer PRIMARY KEY, product_variant_id integer);
  CREATE TABLE channels.channel_variant_overrides (id integer PRIMARY KEY, product_variant_id integer);
  CREATE TABLE channels.channel_pricing (id integer PRIMARY KEY, product_variant_id integer);
  CREATE TABLE channels.channel_pricing_rules (
    id integer PRIMARY KEY,
    scope varchar(20),
    scope_id varchar(100)
  );
  CREATE TABLE channels.channel_variant_availability_sync (
    channel_id integer,
    product_variant_id integer,
    status varchar(20)
  );

  CREATE TABLE warehouse.product_locations (
    id integer PRIMARY KEY,
    product_id integer,
    product_variant_id integer,
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp()
  );
  CREATE TABLE warehouse.work_items (
    id bigint PRIMARY KEY,
    claim_operation_id bigint,
    state varchar(30)
  );

  CREATE TABLE inventory.inventory_levels (
    id integer PRIMARY KEY,
    product_variant_id integer NOT NULL,
    warehouse_location_id integer NOT NULL,
    variant_qty bigint NOT NULL,
    reserved_qty bigint NOT NULL,
    picked_qty bigint NOT NULL,
    packed_qty bigint NOT NULL,
    backorder_qty bigint NOT NULL
  );
  CREATE TABLE inventory.replen_rules (
    id integer PRIMARY KEY,
    product_id integer,
    is_active integer
  );
  CREATE TABLE inventory.replen_tasks (
    id integer PRIMARY KEY,
    product_id integer,
    status varchar(30),
    source_product_variant_id integer,
    pick_product_variant_id integer
  );
  CREATE TABLE inventory.build_orders (
    id integer PRIMARY KEY,
    status varchar(30),
    output_variant_id integer
  );
  CREATE TABLE inventory.build_order_components (
    id integer PRIMARY KEY,
    build_order_id integer,
    component_variant_id integer
  );
  CREATE TABLE inventory.build_recipes (
    id integer PRIMARY KEY,
    output_variant_id integer
  );
  CREATE TABLE inventory.build_recipe_components (
    id integer PRIMARY KEY,
    recipe_id integer,
    component_variant_id integer
  );
  CREATE TABLE inventory.transformation_model_versions (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    product_id integer NOT NULL,
    version integer NOT NULL,
    lifecycle_status varchar(20) NOT NULL,
    build_to_promise_enabled boolean NOT NULL,
    definition_hash varchar(64) NOT NULL,
    validation_state varchar(20) NOT NULL,
    validation_errors jsonb NOT NULL,
    supersedes_model_id integer,
    change_reason varchar(1000) NOT NULL,
    idempotency_key varchar(120) NOT NULL UNIQUE,
    request_hash varchar(64) NOT NULL,
    origin varchar(30) NOT NULL,
    origin_input_hash varchar(64),
    origin_result_hash varchar(64),
    operator_input_hash varchar(64),
    created_by varchar(100) NOT NULL,
    sealed_by varchar(100),
    sealed_at timestamptz,
    retired_by varchar(100),
    retired_at timestamptz,
    superseded_by varchar(100),
    superseded_at timestamptz,
    supersession_reason varchar(1000),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE(product_id, version)
  );
  CREATE UNIQUE INDEX one_transformation_draft_per_product
    ON inventory.transformation_model_versions(product_id)
    WHERE lifecycle_status = 'draft';
  CREATE TABLE inventory.transformation_model_heads (
    product_id integer PRIMARY KEY,
    active_model_id integer,
    draft_model_id integer,
    revision bigint NOT NULL,
    updated_by varchar(100) NOT NULL,
    update_reason varchar(1000) NOT NULL,
    updated_at timestamptz NOT NULL
  );
  CREATE TABLE inventory.transformation_model_paths (
    id integer PRIMARY KEY,
    model_id integer,
    source_variant_id integer,
    destination_variant_id integer
  );
  CREATE TABLE inventory.transformation_recipe_bindings (
    id integer PRIMARY KEY,
    model_id integer,
    output_variant_id_snapshot integer,
    output_product_id_snapshot integer
  );
  CREATE TABLE inventory.transformation_recipe_component_snapshots (
    id integer PRIMARY KEY,
    transformation_recipe_binding_id integer,
    model_id integer,
    component_variant_id integer,
    component_product_id integer
  );
  CREATE TABLE inventory.availability_activation_freezes (
    activation_run_id bigint,
    released_at timestamptz
  );
  CREATE TABLE inventory.availability_claims (id bigint PRIMARY KEY, status varchar(30));
  CREATE TABLE inventory.availability_claim_lines (
    id bigint PRIMARY KEY,
    claim_id bigint,
    target_variant_id integer
  );
  CREATE TABLE inventory.availability_claim_resources (
    id bigint PRIMARY KEY,
    claim_id bigint,
    source_variant_id integer
  );
  CREATE TABLE inventory.availability_claim_operations (
    id bigint PRIMARY KEY,
    claim_id bigint,
    destination_variant_id integer
  );
  CREATE TABLE inventory.availability_claim_operation_inputs (
    claim_operation_id bigint,
    claim_id bigint,
    source_variant_id integer
  );
  CREATE TABLE inventory.channel_exposure_policy_versions (
    id integer PRIMARY KEY,
    product_id integer,
    product_variant_id integer
  );
  CREATE TABLE inventory.channel_exposure_policy_heads (
    scope_key text PRIMARY KEY,
    active_policy_id integer
  );
  CREATE TABLE inventory.inventory_publication_outbox (
    id bigint PRIMARY KEY,
    product_variant_id integer,
    state varchar(30)
  );

  CREATE TABLE marketplace.listing_scopes (id integer PRIMARY KEY, product_id integer);
  CREATE TABLE marketplace.listing_publication_members (
    id bigint PRIMARY KEY,
    product_id integer,
    product_variant_id integer
  );
  CREATE TABLE marketplace.listing_verification_members (
    id bigint PRIMARY KEY,
    product_id integer,
    product_variant_id integer
  );
  CREATE TABLE procurement.demand_event_lines (
    id bigint PRIMARY KEY,
    product_id integer,
    product_variant_id integer
  );
  CREATE TABLE procurement.purchase_forecast_observations (
    id bigint PRIMARY KEY,
    product_id integer,
    selected_receive_variant_id integer
  );
  CREATE TABLE procurement.vendor_products (
    id integer PRIMARY KEY,
    product_id integer,
    product_variant_id integer
  );

  CREATE TABLE dropship.dropship_catalog_rules (
    id integer PRIMARY KEY,
    scope_type varchar(30),
    product_id integer,
    product_variant_id integer,
    is_active boolean
  );
  CREATE TABLE dropship.dropship_vendor_selection_rules (
    id integer PRIMARY KEY,
    scope_type varchar(30),
    product_id integer,
    product_variant_id integer,
    is_active boolean
  );
  CREATE TABLE dropship.dropship_vendor_variant_overrides (
    id integer PRIMARY KEY,
    product_variant_id integer
  );
  CREATE TABLE dropship.dropship_pricing_policies (
    id integer PRIMARY KEY,
    scope_type varchar(30),
    product_id integer,
    product_variant_id integer,
    is_active boolean
  );
  CREATE TABLE dropship.dropship_ebay_store_category_assignments (
    id integer PRIMARY KEY,
    product_variant_id integer
  );
  CREATE TABLE dropship.dropship_ebay_listing_policy_overrides (
    id integer PRIMARY KEY,
    product_variant_id integer
  );
  CREATE TABLE dropship.dropship_listing_price_settings (
    id integer PRIMARY KEY,
    product_variant_id integer
  );
  CREATE TABLE dropship.dropship_vendor_listings (
    id integer PRIMARY KEY,
    product_variant_id integer
  );
  CREATE TABLE dropship.dropship_listing_push_job_items (
    id integer PRIMARY KEY,
    product_variant_id integer,
    status varchar(30)
  );
  CREATE TABLE dropship.dropship_package_profiles (
    id integer PRIMARY KEY,
    product_variant_id integer,
    is_active boolean
  );

  CREATE TABLE shipping.variant_shipping_attrs (id integer PRIMARY KEY, product_variant_id integer);
  CREATE TABLE shipping.product_set_members (id integer PRIMARY KEY, product_variant_id integer);
  CREATE TABLE shipping.rate_rule_members (id integer PRIMARY KEY, product_variant_id integer);
  CREATE TABLE shipping.channel_packing_preferences (id integer PRIMARY KEY, product_variant_id integer);

  CREATE TABLE ebay.ebay_product_aspect_overrides (id integer PRIMARY KEY, product_id integer);

  CREATE TABLE oms.oms_orders (id bigint PRIMARY KEY, status varchar(30));
  CREATE TABLE oms.oms_order_lines (
    id bigint PRIMARY KEY,
    order_id bigint,
    product_variant_id integer
  );
  CREATE TABLE wms.orders (id integer PRIMARY KEY, warehouse_status varchar(30));
  CREATE TABLE wms.order_items (
    id integer PRIMARY KEY,
    order_id integer,
    oms_order_line_id bigint,
    product_id integer,
    status varchar(30),
    fulfilled_quantity integer,
    quantity integer
  );
  CREATE TABLE wms.outbound_shipments (id integer PRIMARY KEY, status varchar(30));
  CREATE TABLE wms.outbound_shipment_items (
    id integer PRIMARY KEY,
    shipment_id integer,
    product_variant_id integer
  );

  CREATE TABLE public.audit_events (
    id bigserial PRIMARY KEY,
    timestamp timestamptz NOT NULL DEFAULT transaction_timestamp(),
    level text NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    target text,
    changes jsonb,
    context jsonb
  );

  ${commandMigration}

  INSERT INTO catalog.shipping_groups(id, code) VALUES (1, 'protection');
  INSERT INTO catalog.products(
    id, sku, name, status, is_active, shopify_product_id,
    shipping_group_id, inventory_strategy, base_unit, inventory_type
  ) VALUES
    (39, 'EG-SLV-STD', 'Easy Glide Standard', 'active', true, '9001', 1,
      'variant_calculated', 'piece', 'inventory'),
    (103, 'EG-SLV-STD-5PCK', 'Easy Glide Standard', 'active', true, '9001', 1,
      'variant_calculated', 'piece', 'inventory');
  INSERT INTO catalog.product_variants(
    id, product_id, sku, name, uom_type, units_per_variant,
    hierarchy_level, parent_variant_id, is_base_unit, requires_shipping,
    track_inventory, sales_eligibility, inventory_policy, dropship_eligible,
    is_active, shopify_variant_id,
    shopify_inventory_item_id
  ) VALUES
    (78, 39, 'EG-P100', 'Pack 100', 'pack', 100, 2, NULL, false, true, true,
      'sellable', 'deny', false, true, '501', '601'),
    (79, 39, 'EG-B500-OLD', 'Old box 500', 'box', 500, 3, NULL, false, true, true,
      'sellable', 'deny', false, false, NULL, NULL),
    (80, 39, 'EG-C10000-OLD', 'Old case 10000', 'case', 10000, 4, NULL, false, true, true,
      'sellable', 'deny', false, true, '999', '699'),
    (207, 103, 'EG-C10000', 'Case 10000', 'case', 10000, 4, NULL, false, true, true,
      'sellable', 'deny', false, true, '503', '603'),
    (265, 103, 'EG-B500', 'Box 500', 'box', 500, 3, NULL, false, true, true,
      'sellable', 'deny', false, true, '502', '602');
  INSERT INTO inventory.inventory_levels(
    id, product_variant_id, warehouse_location_id, variant_qty,
    reserved_qty, picked_qty, packed_qty, backorder_qty
  ) VALUES
    (1, 78, 10, 1, 1, 5, 0, 0),
    (2, 79, 11, 0, 0, 0, 0, 0),
    (3, 80, 12, 0, 0, 0, 0, 0),
    (4, 207, 13, 2, 2, 6, 0, 0),
    (5, 265, 14, 6, 0, 14, 0, 0);
  INSERT INTO warehouse.product_locations(id, product_id, product_variant_id)
    VALUES (1, 39, 78), (3, 103, 207);
  INSERT INTO catalog.product_assets(id, product_id, product_variant_id)
    VALUES (1, 39, 78), (2, 39, NULL), (3, 103, 207);
  INSERT INTO channels.channels(id, name, provider, is_default)
    VALUES (36, 'Shopify', 'shopify', 1);
  INSERT INTO channels.channel_connections(
    id, channel_id, shop_domain, access_token, api_version
  ) VALUES (1, 36, 'cardshellz.myshopify.com', 'test-token', '2024-01');
  INSERT INTO channels.channel_feeds(
    channel_id, product_variant_id, channel_type, channel_variant_id,
    channel_product_id, channel_inventory_item_id, is_active
  ) VALUES
    (36, 78, 'shopify', '501', '9001', '601', 1),
    (36, 79, 'shopify', NULL, '9001', NULL, 0),
    (36, 80, 'shopify', '999', '9999', '699', 0),
    (36, 207, 'shopify', '503', '9001', '603', 1),
    (36, 265, 'shopify', '502', '9001', '602', 1);
  INSERT INTO channels.channel_listings(
    channel_id, product_variant_id, external_product_id,
    external_variant_id, external_url, sync_status
  ) VALUES
    (36, 78, '9001', '501', 'https://example.test/501', 'synced'),
    (36, 79, '9001', NULL, NULL, 'error'),
    (36, 80, '9999', '999', 'https://example.test/999', 'synced'),
    (36, 207, '9001', '503', 'https://example.test/503', 'synced'),
    (36, 265, '9001', '502', 'https://example.test/502', 'synced');
  INSERT INTO inventory.transformation_model_versions(
    id, product_id, version, lifecycle_status, build_to_promise_enabled,
    definition_hash, validation_state, validation_errors, supersedes_model_id,
    change_reason, idempotency_key, request_hash, origin,
    operator_input_hash, created_by, created_at, updated_at
  ) VALUES
    (227, 39, 1, 'draft', false, repeat('a', 64), 'valid', '[]', NULL,
      'Existing draft', 'draft-39', repeat('b', 64), 'operator', repeat('c', 64),
      'user:prior', '2026-09-01T00:00:00Z', '2026-09-01T00:00:00Z'),
    (285, 103, 1, 'draft', false, repeat('d', 64), 'valid', '[]', NULL,
      'Existing draft', 'draft-103', repeat('e', 64), 'operator', repeat('f', 64),
      'user:prior', '2026-09-01T00:00:00Z', '2026-09-01T00:00:00Z');
  INSERT INTO inventory.transformation_model_heads(
    product_id, active_model_id, draft_model_id, revision,
    updated_by, update_reason, updated_at
  ) VALUES
    (39, NULL, 227, 0, 'user:prior', 'Existing draft', '2026-09-01T00:00:00Z'),
    (103, NULL, 285, 0, 'user:prior', 'Existing draft', '2026-09-01T00:00:00Z');
`;

describeDatabase.sequential("Shopify product consolidation PostgreSQL contract", () => {
  let database: InventoryCutoverTestDatabase;
  let repository: ReturnType<typeof createShopifyProductConsolidationRepository>;
  const remoteVariantProductIds = new Map<string, string | null>([
    ["501", "9001"],
    ["502", "9001"],
    ["503", "9001"],
    ["999", null],
  ]);

  beforeAll(async () => {
    database = await createInventoryCutoverTestDatabase(
      databaseUrl,
      disposable,
      fixtureSql,
    );
    repository = createShopifyProductConsolidationRepository(
      drizzle(database.pool, { schema }),
    );
  });

  afterAll(async () => {
    await database?.close();
  });

  it("atomically converges one product family without changing any quantity", async () => {
    const local = await repository.loadLocalEvidence({
      channelId: 36,
      shopDomain: "cardshellz.myshopify.com",
      shopifyProductId: "9001",
      canonicalProductId: 103,
    });
    const evidence: ShopifyProductConsolidationEvidence = {
      channelId: local.channelId,
      shopDomain: local.shopDomain,
      shopifyProductId: local.shopifyProductId,
      remoteProductExists: true,
      remoteProductTitle: "Easy Glide Standard",
      ownerProductIds: local.ownerProductIds,
      canonicalProductId: local.canonicalProductId,
      activeCutoverFreezeId: local.activeCutoverFreezeId,
      products: local.products,
      remoteVariantProductIds: Object.fromEntries(remoteVariantProductIds),
    };
    const plan = buildShopifyProductConsolidationPlan(evidence);
    expect(plan.canApply).toBe(true);
    const request: ShopifyProductConsolidationApplyRequest = {
      shopifyProductId: "9001",
      canonicalProductId: 103,
      expectedShopDomain: "cardshellz.myshopify.com",
      expectedPreviewHash: plan.previewHash,
      idempotencyKey: "123e4567-e89b-42d3-a456-426614174000",
      reason: "Consolidate the reviewed Easy Glide product family",
    };
    const actor = "user:integration-test";
    const requestHash = shopifyProductConsolidationRequestHash({ actor, request });
    const beforeQuantities = (await database.pool.query(`
      SELECT id, product_variant_id, warehouse_location_id, variant_qty,
             reserved_qty, picked_qty, packed_qty, backorder_qty
      FROM inventory.inventory_levels ORDER BY id
    `)).rows;

    const applied = await repository.applyConsolidation({
      channelId: 36,
      shopDomain: "cardshellz.myshopify.com",
      request,
      requestHash,
      actor,
      now: new Date("2026-09-12T20:00:00.000Z"),
      remoteProductExists: true,
      remoteProductTitle: "Easy Glide Standard",
      remoteVariantProductIds,
    });

    expect(applied).toMatchObject({
      idempotentReplay: false,
      command: {
        result: {
          canonicalProductId: 103,
          sourceProductIds: [39],
          movedVariantIds: [78],
          retiredVariantIds: [80],
          archivedVariantIds: [79],
          archivedProductIds: [39],
          reparentedLocationCount: 1,
          reparentedAssetCount: 1,
        },
      },
    });
    expect((await database.pool.query(`
      SELECT id, product_id, is_active, shopify_variant_id
      FROM catalog.product_variants ORDER BY id
    `)).rows).toEqual([
      { id: 78, product_id: 103, is_active: true, shopify_variant_id: "501" },
      { id: 79, product_id: 39, is_active: false, shopify_variant_id: null },
      { id: 80, product_id: 39, is_active: false, shopify_variant_id: null },
      { id: 207, product_id: 103, is_active: true, shopify_variant_id: "503" },
      { id: 265, product_id: 103, is_active: true, shopify_variant_id: "502" },
    ]);
    expect((await database.pool.query(`
      SELECT id, shopify_product_id, is_active, status
      FROM catalog.products ORDER BY id
    `)).rows).toEqual([
      { id: 39, shopify_product_id: null, is_active: false, status: "archived" },
      { id: 103, shopify_product_id: "9001", is_active: true, status: "active" },
    ]);
    expect((await database.pool.query(`
      SELECT id, product_id FROM warehouse.product_locations ORDER BY id
    `)).rows).toEqual([
      { id: 1, product_id: 103 },
      { id: 3, product_id: 103 },
    ]);
    expect((await database.pool.query(`
      SELECT id, product_id FROM catalog.product_assets ORDER BY id
    `)).rows).toEqual([
      { id: 1, product_id: 103 },
      { id: 2, product_id: 39 },
      { id: 3, product_id: 103 },
    ]);
    expect((await database.pool.query(`
      SELECT id, product_variant_id, channel_product_id, channel_variant_id, is_active
      FROM channels.channel_feeds ORDER BY product_variant_id
    `)).rows).toEqual([
      { id: 1, product_variant_id: 78, channel_product_id: "9001", channel_variant_id: "501", is_active: 1 },
      { id: 2, product_variant_id: 79, channel_product_id: null, channel_variant_id: null, is_active: 0 },
      { id: 3, product_variant_id: 80, channel_product_id: null, channel_variant_id: null, is_active: 0 },
      { id: 4, product_variant_id: 207, channel_product_id: "9001", channel_variant_id: "503", is_active: 1 },
      { id: 5, product_variant_id: 265, channel_product_id: "9001", channel_variant_id: "502", is_active: 1 },
    ]);
    expect((await database.pool.query(`
      SELECT id, product_id, lifecycle_status, validation_state
      FROM inventory.transformation_model_versions ORDER BY id
    `)).rows).toEqual(expect.arrayContaining([
      { id: 227, product_id: 39, lifecycle_status: "superseded", validation_state: "valid" },
      { id: 285, product_id: 103, lifecycle_status: "superseded", validation_state: "valid" },
      expect.objectContaining({ product_id: 39, lifecycle_status: "draft", validation_state: "invalid" }),
      expect.objectContaining({ product_id: 103, lifecycle_status: "draft", validation_state: "invalid" }),
    ]));
    expect((await database.pool.query(`
      SELECT id, product_variant_id, warehouse_location_id, variant_qty,
             reserved_qty, picked_qty, packed_qty, backorder_qty
      FROM inventory.inventory_levels ORDER BY id
    `)).rows).toEqual(beforeQuantities);
    expect((await database.pool.query(`
      SELECT action, actor, context FROM public.audit_events
    `)).rows[0]).toMatchObject({
      action: "catalog.shopify_product_family_consolidated",
      actor,
      context: {
        remoteMutationPerformed: false,
        inventoryQuantityMutationPerformed: false,
      },
    });

    await expect(repository.applyConsolidation({
      channelId: 36,
      shopDomain: "cardshellz.myshopify.com",
      request,
      requestHash,
      actor,
      now: new Date("2026-09-12T20:05:00.000Z"),
      remoteProductExists: true,
      remoteProductTitle: "Easy Glide Standard",
      remoteVariantProductIds,
    })).resolves.toMatchObject({ idempotentReplay: true });
    expect((await database.pool.query(`
      SELECT count(*)::integer AS count
      FROM channels.shopify_product_consolidation_commands
    `)).rows[0].count).toBe(1);
    await expect(database.pool.query(`
      UPDATE channels.shopify_product_consolidation_commands
      SET reason = 'tampered'
    `)).rejects.toMatchObject({ code: "55000" });
  });
});
