import { SQL, getTableColumns } from "drizzle-orm";
import { getTableConfig, PgDialect, type PgTable } from "drizzle-orm/pg-core";
const quote = (name: string) => `"${name.replaceAll('"', '""')}"`;
/** Current-column fixture; separate migration tests must apply the actual new DDL. */
export function operationOwnerTableFixture(
  table: PgTable,
  omitColumns: readonly string[] = [],
): string {
  const config = getTableConfig(table);
  const columns = Object.values(getTableColumns(table))
    .filter((column) => !omitColumns.includes(column.name))
    .map((column) => {
      let definition = `${quote(column.name)} ${column.getSQLType()}`;
      if (column.primary && column.getSQLType() === "integer")
        return `${definition} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
      if (column.default !== undefined) {
        const literal =
          column.default instanceof SQL
            ? new PgDialect().sqlToQuery(column.default).sql
            : typeof column.default === "string"
              ? `'${column.default.replaceAll("'", "''")}'`
              : String(column.default);
        definition += ` DEFAULT ${literal}`;
      }
      return (
        definition +
        (column.primary ? " PRIMARY KEY" : column.notNull ? " NOT NULL" : "")
      );
    });
  return `CREATE TABLE ${quote(config.schema ?? "public")}.${quote(config.name)} (${columns.join(",")});`;
}
